### ISSUE TITLE
 Failed to process Audit Spool File - Audit Logger: java.lang.NullPointerException

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4chee-arc-light#1062]
```
15:54:58,188 WARN  [org.dcm4chee.arc.audit.AuditService] (EE-ManagedScheduledExecutorService-default-Thread-14) Failed to process Audit Spool File - Audit Logger: java.lang.NullPointerException
	at org.dcm4chee.arc.audit.AuditService.callingUserIDTypeCode(AuditService.java:1730)
	at org.dcm4chee.arc.audit.AuditService.getApsForGetOrWadoRS(AuditService.java:936)
	at org.dcm4chee.arc.audit.AuditService.getApsForRetrieve(AuditService.java:856)
	at org.dcm4chee.arc.audit.AuditService.auditRetrieve(AuditService.java:847)
	at org.dcm4chee.arc.audit.AuditService.aggregateAuditMessage(AuditService.java:121)
	at org.dcm4chee.arc.audit.AuditService.auditAndProcessFile(AuditService.java:559)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.weld.bean.proxy.AbstractBeanInstance.invoke(AbstractBeanInstance.java:38)
	at org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke(ProxyMethodHandler.java:100)
	at org.dcm4chee.arc.audit.AuditService$Proxy$_$$_WeldClientProxy.auditAndProcessFile(Unknown Source)
	at org.dcm4chee.arc.audit.AuditScheduler.execute(AuditScheduler.java:130)
	at org.dcm4chee.arc.Scheduler.run(Scheduler.java:76)
```

**Comment by vrindanayak** [comment]
- As per the above server log, exception is either during C-GET or WADO RS. Cannot reproduce the issue for both scenarios using secure/unsecure versions of archive.
- For now, logging the message as warning and returning null if the calling user ID is null
