### ISSUE TITLE
Rejecting study fails with status 400 in UI when accessing over http on Safari

### ISSUE THREAD

**Issue by petrkalina** [dcm4che/dcm4chee-arc-light#1064]
When accessing via http (i.e. port 8080) request to reject a study fails with status 400:

![screen shot 2017-11-13 at 18 13 59](https://user-images.githubusercontent.com/1150350/32739004-f193c9b0-c89e-11e7-976b-8999c8d403c6.png)

The same operation works when using https (i.e. port 8443):

![screen shot 2017-11-13 at 18 20 12](https://user-images.githubusercontent.com/1150350/32739165-598af9da-c89f-11e7-8032-b461ff7a54e9.png)

**Comment by gunterze** [comment]
I cannot reproduce the issue with Firefox or Chrome.

**Comment by petrkalina** [comment]
I can also confirm that with firefox is works. With safari still not. The safari version is: Version 11.0.1 (12604.3.5.1.1).

**Comment by shral** [comment]
I pushed a change, now the url is encoded in javascript, when you use reject, maybe you (@petrkalina) can test that.

**Comment by petrkalina** [comment]
tested but the problem still persists

**Comment by petrkalina** [comment]
```2017-11-15 13:05:32,966 INFO  [org.dcm4chee.arc.qido.QidoRS] (default task-96) SearchForStudies: 3 Matches
2017-11-15 13:05:36,621 DEBUG [io.undertow.request.io] (default I/O-12) UT005014: Failed to parse request: io.undertow.util.BadRequestException: UT000165: Invalid character ^ in request-target
        at io.undertow.server.protocol.http.HttpRequestParser.handlePath(HttpRequestParser.java:376)
        at io.undertow.server.protocol.http.HttpRequestParser.handle(HttpRequestParser.java:242)
        at io.undertow.server.protocol.http.HttpReadListener.handleEventWithNoRunningRequest(HttpReadListener.java:187)
        at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:136)
        at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:59)
        at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
        at org.xnio.conduits.ReadReadyHandler$ChannelListenerHandler.readReady(ReadReadyHandler.java:66)
        at org.xnio.nio.NioSocketConduit.handleReady(NioSocketConduit.java:89)
        at org.xnio.nio.WorkerThread.run(WorkerThread.java:591)
```

**Comment by petrkalina** [comment]
with https:
```
2017-11-15 13:08:30,649 DEBUG [io.undertow.request] (default I/O-6) Matched prefix path /dcm4chee-arc for path /dcm4chee-arc/aets/DCM4CHEE/rs/studies/1.3.6.1.4.1.5962.1.2.0.1175775772.5717.0/reject/113039
^DCM
2017-11-15 13:08:30,650 DEBUG [io.undertow.request.security] (default task-123) Security constraints for request /dcm4chee-arc/aets/DCM4CHEE/rs/studies/1.3.6.1.4.1.5962.1.2.0.1175775772.5717.0/reject/1130
39^DCM are [SingleConstraintMatch{emptyRoleSemantic=PERMIT, requiredRoles=[user]}]
2017-11-15 13:08:30,650 DEBUG [io.undertow.request.security] (default task-123) Authenticating required for request HttpServerExchange{ POST /dcm4chee-arc/aets/DCM4CHEE/rs/studies/1.3.6.1.4.1.5962.1.2.0.1
175775772.5717.0/reject/113039^DCM request {accept=[application/json, text/plain, */*], accept-language=[en-us], accept-encoding=[gzip, deflate], origin=[https://test-ng:8443], user-agent=[Mozilla/5.0 (Ma
cintosh; Intel Mac OS X 10_12_6) AppleWebKit/604.3.5 (KHTML, like Gecko) Version/11.0.1 Safari/604.3.5], authorization=[Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJyc2llU3EyRHlzYmFmT1hnS0l6R
kFITnJLY2haRVRYcm05d3loTXNIbkVVIn0.eyJqdGkiOiIxOGQxOTcwMi01ZGZhLTQxNTItOTMzNy1mZGViZTIxODAxNWIiLCJleHAiOjE1MTA3NDc3OTUsIm5iZiI6MCwiaWF0IjoxNTEwNzQ3NDk1LCJpc3MiOiJodHRwczovL3Rlc3Qtbmc6ODg0My9hdXRoL3JlYWxtc
y9kY200Y2hlIiwiYXVkIjoiZGNtNGNoZWUtYXJjLXVpIiwic3ViIjoiNmI4YzIxYjctYzkwZC00YWFiLTg0MTctZDdjMmM4NzQ5NDVlIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoiZGNtNGNoZWUtYXJjLXVpIiwiYXV0aF90aW1lIjoxNTEwNzQ3MTE3LCJzZXNzaW9uX3N0Y
XRlIjoiMTNjNTk5NDgtOTg4MS00OTQ0LWJjYWYtMTMxNmZmMTdlMDQ4IiwiYWNyIjoiMSIsImFsbG93ZWQtb3JpZ2lucyI6WyJodHRwczovL3Rlc3Qtbmc6ODQ0MyJdLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsiYXVkaXRsb2ciLCJhZG1pbiIsInVzZXIiXX0sInJlc
291cmNlX2FjY2VzcyI6eyJyZWFsbS1tYW5hZ2VtZW50Ijp7InJvbGVzIjpbInZpZXctaWRlbnRpdHktcHJvdmlkZXJzIiwidmlldy1yZWFsbSIsIm1hbmFnZS1pZGVudGl0eS1wcm92aWRlcnMiLCJpbXBlcnNvbmF0aW9uIiwicmVhbG0tYWRtaW4iLCJjcmVhdGUtY2xpZ
W50IiwibWFuYWdlLXVzZXJzIiwicXVlcnktcmVhbG1zIiwidmlldy1hdXRob3JpemF0aW9uIiwicXVlcnktY2xpZW50cyIsInF1ZXJ5LXVzZXJzIiwibWFuYWdlLWV2ZW50cyIsIm1hbmFnZS1yZWFsbSIsInZpZXctZXZlbnRzIiwidmlldy11c2VycyIsInZpZXctY2xpZ
W50cyIsIm1hbmFnZS1hdXRob3JpemF0aW9uIiwibWFuYWdlLWNsaWVudHMiLCJxdWVyeS1ncm91cHMiXX0sImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sInByZWZlcnJlZF91c
2VybmFtZSI6ImFkbWluIiwiZ2l2ZW5fbmFtZSI6IiIsImZhbWlseV9uYW1lIjoiIn0.VWJjCNaC6teWjRLmIH04TUODeOVOgm-4TPLnN1XAQoyQhuxUkVWEeY4dUfMc8Uurp42Vk4KXBEei3iNGjfH1EzFYNZ-EIG8ls6vxmDfTIzxFS_-wP0Fw7WrxrdrA5PxTgvDlb2A1J
eQTLxzH1dN-1aXgrr6tvb6QOEUG4ACCazwpSPVYdMd3029h2BlCtvA18xoNgsrAqX3WsnNVaFIk--xweAo2zM7SbnHToCAoRR6uBRX1VJ-zl7i6svnwJdmRxuB4KXuDHQokutdMagqNRd2rFUuJUoE3XD3vl_e0WoeG9c3mMMDfDgbdD3GR4Tw0E0Give-pGhuc5JHlZfMKG
Q], content-type=[application/json], content-length=[2], cookie=[__utma=213118225.281623409.1507905348.1510666329.1510747263.3; __utmb=213118225.11.8.1510747263; __utmc=213118225; __utmz=213118225.1507905
348.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); __utmt=1], referer=[https://test-ng:8443/dcm4chee-arc/ui2/], Host=[test-ng:8443]} response {X-Powered-By=[Undertow/1], Server=[WildFly/11]}}
2017-11-15 13:08:30,650 DEBUG [io.undertow.request.security] (default task-123) Setting authentication required for exchange HttpServerExchange{ POST /dcm4chee-arc/aets/DCM4CHEE/rs/studies/1.3.6.1.4.1.596
2.1.2.0.1175775772.5717.0/reject/113039^DCM request {accept=[application/json, text/plain, */*], accept-language=[en-us], accept-encoding=[gzip, deflate], origin=[https://test-ng:8443], user-agent=[Mozill
a/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/604.3.5 (KHTML, like Gecko) Version/11.0.1 Safari/604.3.5], authorization=[Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJyc2llU3EyRHlzYmFm
T1hnS0l6RkFITnJLY2haRVRYcm05d3loTXNIbkVVIn0.eyJqdGkiOiIxOGQxOTcwMi01ZGZhLTQxNTItOTMzNy1mZGViZTIxODAxNWIiLCJleHAiOjE1MTA3NDc3OTUsIm5iZiI6MCwiaWF0IjoxNTEwNzQ3NDk1LCJpc3MiOiJodHRwczovL3Rlc3Qtbmc6ODg0My9hdXRo
L3JlYWxtcy9kY200Y2hlIiwiYXVkIjoiZGNtNGNoZWUtYXJjLXVpIiwic3ViIjoiNmI4YzIxYjctYzkwZC00YWFiLTg0MTctZDdjMmM4NzQ5NDVlIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoiZGNtNGNoZWUtYXJjLXVpIiwiYXV0aF90aW1lIjoxNTEwNzQ3MTE3LCJzZXNz
aW9uX3N0YXRlIjoiMTNjNTk5NDgtOTg4MS00OTQ0LWJjYWYtMTMxNmZmMTdlMDQ4IiwiYWNyIjoiMSIsImFsbG93ZWQtb3JpZ2lucyI6WyJodHRwczovL3Rlc3Qtbmc6ODQ0MyJdLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsiYXVkaXRsb2ciLCJhZG1pbiIsInVzZXIi
XX0sInJlc291cmNlX2FjY2VzcyI6eyJyZWFsbS1tYW5hZ2VtZW50Ijp7InJvbGVzIjpbInZpZXctaWRlbnRpdHktcHJvdmlkZXJzIiwidmlldy1yZWFsbSIsIm1hbmFnZS1pZGVudGl0eS1wcm92aWRlcnMiLCJpbXBlcnNvbmF0aW9uIiwicmVhbG0tYWRtaW4iLCJjcmVh
dGUtY2xpZW50IiwibWFuYWdlLXVzZXJzIiwicXVlcnktcmVhbG1zIiwidmlldy1hdXRob3JpemF0aW9uIiwicXVlcnktY2xpZW50cyIsInF1ZXJ5LXVzZXJzIiwibWFuYWdlLWV2ZW50cyIsIm1hbmFnZS1yZWFsbSIsInZpZXctZXZlbnRzIiwidmlldy11c2VycyIsInZp
ZXctY2xpZW50cyIsIm1hbmFnZS1hdXRob3JpemF0aW9uIiwibWFuYWdlLWNsaWVudHMiLCJxdWVyeS1ncm91cHMiXX0sImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sInByZWZl
cnJlZF91c2VybmFtZSI6ImFkbWluIiwiZ2l2ZW5fbmFtZSI6IiIsImZhbWlseV9uYW1lIjoiIn0.VWJjCNaC6teWjRLmIH04TUODeOVOgm-4TPLnN1XAQoyQhuxUkVWEeY4dUfMc8Uurp42Vk4KXBEei3iNGjfH1EzFYNZ-EIG8ls6vxmDfTIzxFS_-wP0Fw7WrxrdrA5PxT
gvDlb2A1JeQTLxzH1dN-1aXgrr6tvb6QOEUG4ACCazwpSPVYdMd3029h2BlCtvA18xoNgsrAqX3WsnNVaFIk--xweAo2zM7SbnHToCAoRR6uBRX1VJ-zl7i6svnwJdmRxuB4KXuDHQokutdMagqNRd2rFUuJUoE3XD3vl_e0WoeG9c3mMMDfDgbdD3GR4Tw0E0Give-pGhuc
5JHlZfMKGQ], content-type=[application/json], content-length=[2], cookie=[__utma=213118225.281623409.1507905348.1510666329.1510747263.3; __utmb=213118225.11.8.1510747263; __utmc=213118225; __utmz=21311822
5.1507905348.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); __utmt=1], referer=[https://test-ng:8443/dcm4chee-arc/ui2/], Host=[test-ng:8443]} response {X-Powered-By=[Undertow/1], Server=[WildFly/11]}}
2017-11-15 13:08:30,671 DEBUG [io.undertow.request.security] (default task-123) Authenticated as 6b8c21b7-c90d-4aab-8417-d7c2c874945e, roles [auditlog, admin, user]
2017-11-15 13:08:30,724 INFO  [org.dcm4chee.arc.iocm.rs.IocmRS] (default task-123) Process POST /dcm4chee-arc/aets/DCM4CHEE/rs/studies/1.3.6.1.4.1.5962.1.2.0.1175775772.5717.0/reject/113039^DCM from 6b8c2
1b7-c90d-4aab-8417-d7c2c874945e@10.155.113.22
2017-11-15 13:08:30,814 INFO  [org.dcm4chee.arc.store.impl.StoreServiceImpl] (default task-123) 6b8c21b7-c90d-4aab-8417-d7c2c874945e@10.155.113.22->DCM4CHEE: Reject Instance[pk=4, uid=1.3.6.1.4.1.5962.1.1
.0.1.1.1175775772.5717.0, class=1.2.840.10008.5.1.4.1.1.7, no=1] by (113039, DCM, "Data Retention Policy Expired")
2017-11-15 13:08:30,897 INFO  [org.dcm4chee.arc.store.impl.StoreServiceImpl] (default task-123) 6b8c21b7-c90d-4aab-8417-d7c2c874945e@10.155.113.22->DCM4CHEE: Create Series[pk=20, uid=2.25.1135691858039237
77382133678796845645507, no=0, mod=KO]
2017-11-15 13:08:30,899 INFO  [org.dcm4chee.arc.store.impl.StoreServiceImpl] (default task-123) 6b8c21b7-c90d-4aab-8417-d7c2c874945e@10.155.113.22->DCM4CHEE: Create Instance[pk=20, uid=2.25.69841763391749
835533771063838320621320, class=1.2.840.10008.5.1.4.1.1.88.59, no=0]
```

**Comment by gunterze** [comment]
Seems that the HTTPS listener of undertow does not check for invalid characters in the URL. (s. `POST /dcm4chee-arc/aets/DCM4CHEE/rs/studies/1.3.6.1.4.1.5962.1.2.0.1175775772.5717.0/reject/113039^DCM`)
` and that the patch did not get applied by the browser

**Comment by sgala** [comment]
Sorry I commented on the commit instead of here, got lost in navigation.

I'm seeing the same bug in 5.22.3, and I'm seeing that ``dcm4chee-arc-ui2/src/app/study/study/study.service.ts`` doesn't have encodeURI calls, though I'm not sure if the problem is the same or not...

In my case, API calls using http to

```
curl -v 'http:///dcm4chee-arc/aets//rs/studies//reject/113001%5EDCM'
```

fails silently with zero information in browser or server logs, giving error 400 and an empty response. The UI fails in the same way, also using plain HTTP.

**Comment by shral** [comment]
> Sorry I commented on the commit instead of here, got lost in navigation.
> 
> I'm seeing the same bug in 5.22.3, and I'm seeing that `dcm4chee-arc-ui2/src/app/study/study/study.service.ts` doesn't have encodeURI calls, though I'm not sure if the problem is the same or not...
> 
> In my case, API calls using http to
> 
> ```
> curl -v 'http:///dcm4chee-arc/aets//rs/studies//reject/113001%5EDCM'
> ```
> 
> fails silently with zero information in browser or server logs, giving error 400 and an empty response. The UI fails in the same way, also using plain HTTP.
Hi @sgala 
First of all you for your report!
In the new version every URL request is encoded see [hier](https://github.com/dcm4che/dcm4chee-arc-light/blob/ccfc4d11d79996ae3f53402b72f07e409f8275aa/dcm4chee-arc-ui2/src/app/helpers/j4care-http.service.ts#L77), that's why you did not find `encodeURI` in `study.service.ts`.
The fact that the curl method with the encoded part `113001%5EDCM` is failing too, shows that the problem in your case is not the encoding and probably nor the UI. I can not reproduce the bug, to be able to debug the bug, you have to provide us with more information (like server logs etc).

**Comment by Christian-e-S** [comment]
Hi  @shral ,
I ran exactly into the same problem with version 5.23.2. 

The chrome development tools tell me that the POST request to
https://mydomain.com/dcm4chee-arc/aets/DCM4CHEE/rs/studies/1.113654.3.13.1026/reject/113039%5EDCM fails with HTTP code 400.

The problem is, that this event is not at all logged in the server log file. Other data manipulation command (e.g. changing physician name of the study).

Do you have any idea how I could provide additional debugging information when the server.log file shows nothing?
