### ISSUE TITLE
Purge Instance Records from database service throws NoSuchFileException

### ISSUE THREAD

**Issue by vrindanayak** [dcm4che/dcm4chee-arc-light#1073]
````
2017-11-20 09:21:36,867 WARN  [org.dcm4chee.arc.delete.impl.PurgeStorageScheduler] (EE-ManagedScheduledExecutorService-default-Thread-10) Failed to delete Metadata[pk=689, storageID=series-metadata, path=2017/11/17/1.3.12.2.1107.5.8.1.12345678.199508041416590859569/1.3.12.2.1107.5.8.1.12345678.199508041416590860429/metadata.zip, size=23946, status=FAILED_TO_DELETE] from file:/home/vrinda/work/wildfly-11.0.0.Final/standalone/data/series-metadata/: java.nio.file.NoSuchFileException: /home/vrinda/work/wildfly-11.0.0.Final/standalone/data/series-metadata/2017/11/17/1.3.12.2.1107.5.8.1.12345678.199508041416590859569/1.3.12.2.1107.5.8.1.12345678.199508041416590860429/metadata.zip
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:244)
	at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:103)
	at java.nio.file.Files.delete(Files.java:1126)
	at org.dcm4chee.arc.storage.filesystem.FileSystemStorage.deleteObject(FileSystemStorage.java:129)
	at org.dcm4chee.arc.delete.impl.PurgeStorageScheduler.deleteSeriesMetadata(PurgeStorageScheduler.java:221)
	at org.dcm4chee.arc.delete.impl.PurgeStorageScheduler.execute(PurgeStorageScheduler.java:135)
	at org.dcm4chee.arc.Scheduler.run(Scheduler.java:76)
	at org.jboss.as.ee.concurrent.ControlPointUtils$ControlledScheduledRunnable.run(ControlPointUtils.java:158)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at org.glassfish.enterprise.concurrent.internal.ManagedScheduledThreadPoolExecutor$ManagedScheduledFutureTask.access$201(ManagedScheduledThreadPoolExecutor.java:383)
	at org.glassfish.enterprise.concurrent.internal.ManagedScheduledThreadPoolExecutor$ManagedScheduledFutureTask.run(ManagedScheduledThreadPoolExecutor.java:534)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at org.glassfish.enterprise.concurrent.ManagedThreadFactoryImpl$ManagedThread.run(ManagedThreadFactoryImpl.java:250)
	at org.jboss.as.ee.concurrent.service.ElytronManagedThreadFactory$ElytronManagedThread.run(ElytronManagedThreadFactory.java:78)

2017-11-20 09:21:36,934 WARN  [org.dcm4chee.arc.delete.impl.PurgeStorageScheduler] (EE-ManagedScheduledExecutorService-default-Thread-10) Failed to delete Location[pk=5767, systemID=metadata, path=2017/11/20/5E9204E8/616C94F2/E88A5581.json, tsuid=null, size=5715, status=FAILED_TO_DELETE, objectType=METADATA] from file:/home/vrinda/work/wildfly-11.0.0.Final/standalone/data/metadata/: java.nio.file.NoSuchFileException: /home/vrinda/work/wildfly-11.0.0.Final/standalone/data/metadata/2017/11/20/5E9204E8/616C94F2/E88A5581.json
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:244)
	at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:103)
	at java.nio.file.Files.delete(Files.java:1126)
	at org.dcm4chee.arc.storage.filesystem.FileSystemStorage.deleteObject(FileSystemStorage.java:129)
	at org.dcm4chee.arc.delete.impl.PurgeStorageScheduler.deleteNextObjectsFromStorage(PurgeStorageScheduler.java:243)
	at org.dcm4chee.arc.delete.impl.PurgeStorageScheduler.execute(PurgeStorageScheduler.java:130)
	at org.dcm4chee.arc.Scheduler.run(Scheduler.java:76)
	at org.jboss.as.ee.concurrent.ControlPointUtils$ControlledScheduledRunnable.run(ControlPointUtils.java:158)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at org.glassfish.enterprise.concurrent.internal.ManagedScheduledThreadPoolExecutor$ManagedScheduledFutureTask.access$201(ManagedScheduledThreadPoolExecutor.java:383)
	at org.glassfish.enterprise.concurrent.internal.ManagedScheduledThreadPoolExecutor$ManagedScheduledFutureTask.run(ManagedScheduledThreadPoolExecutor.java:534)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at org.glassfish.enterprise.concurrent.ManagedThreadFactoryImpl$ManagedThread.run(ManagedThreadFactoryImpl.java:250)
	at org.jboss.as.ee.concurrent.service.ElytronManagedThreadFactory$ElytronManagedThread.run(ElytronManagedThreadFactory.java:78)
````

**Comment by vrindanayak** [comment]
Also causes rejection of the study to fail with 409-Conflict

**Comment by vrindanayak** [comment]
Invalid
