### ISSUE TITLE
Provide check for existence of AE configuration(s) in DIMSE RESTful services

### ISSUE THREAD

**Issue by vrindanayak** [dcm4che/dcm4chee-arc-light#1109]
````
Caused by: java.lang.NullPointerException
        at org.dcm4che3.net.ApplicationEntity.findCompatibelConnection(ApplicationEntity.java:630)
        at org.dcm4che3.net.ApplicationEntity.connect(ApplicationEntity.java:641)
        at org.dcm4chee.arc.query.scu.impl.CFindSCUImpl.openAssociation(CFindSCUImpl.java:101)
        at org.dcm4chee.arc.query.scu.impl.CFindSCUImpl$Proxy$_$$_WeldClientProxy.openAssociation(Unknown Source)
        at org.dcm4chee.arc.dimse.rs.QueryRS.search(QueryRS.java:273)
        at org.dcm4chee.arc.dimse.rs.QueryRS.searchForStudiesJSON(QueryRS.java:141)
        at org.dcm4chee.arc.dimse.rs.QueryRS$Proxy$_$$_WeldClientProxy.searchForStudiesJSON(Unknown Source)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
````

**Comment by gunterze** [comment]
There is no need that the Move Destination is known by the Archive acting as C-Move SCU. So the check for the destination AET shall be removed again
