### ISSUE TITLE
 Failed to read Audit Spool File

### ISSUE THREAD

**Issue by dhanzhang** [dcm4che/dcm4chee-arc-light#117]
@gunterze  
when  user command  : $WILDFLY_HOME/bin/standalone.sh -c dcm4chee-arc.xml
the console ui output is :
23:38:25,811 INFO  [org.hibernate.dialect.Dialect] (ServerService Thread Pool -- 67) HHH000400: Using dialect: org.hibernate.dialect.MySQL5Dialect
23:38:25,890 WARN  [org.hibernate.cfg.annotations.reflection.JPAOverriddenAnnotationReader] (ServerService Thread Pool -- 67) HHH000207: Property org.dcm4chee.arc.entity.Study.failedSOPInstanceUIDList not found in class but described in <mapping-file/> (possible typo error)
23:38:26,340 INFO  [org.hibernate.hql.internal.ast.ASTQueryTranslatorFactory] (ServerService Thread Pool -- 67) HHH000397: Using ASTQueryTranslatorFactory
23:38:30,309 INFO  [javax.enterprise.resource.webcontainer.jsf.config] (ServerService Thread Pool -- 71) Initializing Mojarra 2.2.12-jbossorg-2 20150729-1131 for context '/dcm4chee-arc/ui'
23:38:30,323 INFO  [javax.enterprise.resource.webcontainer.jsf.config] (ServerService Thread Pool -- 64) Initializing Mojarra 2.2.12-jbossorg-2 20150729-1131 for context '/dcm4chee-arc'
23:38:31,543 WARN  [org.dcm4che3.imageio.codec.ImageWriterFactory] (ServerService Thread Pool -- 70) No preferred Writer com.sun.media.imageioimpl.plugins.jpeg.CLibJPEGImageWriter for format: jpeg - use com.sun.imageio.plugins.jpeg.JPEGImageWriter
**23:38:31,548 WARN  [org.dcm4chee.arc.impl.ArchiveDeviceProducer] (ServerService Thread Pool -- 70) UnzipVendorDataToURI=${jboss.server.temp.url}/dcm4chee-arc, but no Vendor Data**
23:38:32,305 WARN  [org.dcm4chee.arc.audit.AuditService] (EE-ManagedScheduledExecutorService-default-Thread-2) Failed to read Audit Spool File - /home/sv/dev/wildfly-9.0.2.Final/standalone/data/audit-spool/QUERY_QIDO2879467148414962087.tmp : java.io.EOFException
	at java.io.DataInputStream.readUnsignedShort(DataInputStream.java:340)
	at java.io.DataInputStream.readUTF(DataInputStream.java:589)
	at java.io.DataInputStream.readUTF(DataInputStream.java:564)
	at org.dcm4chee.arc.audit.AuditService.auditQuery(AuditService.java:433)
	at org.dcm4chee.arc.audit.AuditService.aggregateAuditMessage(AuditService.java:137)
	at org.dcm4chee.arc.audit.AuditService$Proxy$_$$_WeldClientProxy.aggregateAuditMessage(Unknown Source)
	at org.dcm4chee.arc.audit.AuditScheduler.execute(AuditScheduler.java:115)
	at org.dcm4chee.arc.Scheduler.run(Scheduler.java:65)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at org.glassfish.enterprise.concurrent.internal.ManagedScheduledThreadPoolExecutor$ManagedScheduledFutureTask.access$201(ManagedScheduledThreadPoolExecutor.java:383)
	at org.glassfish.enterprise.concurrent.internal.ManagedScheduledThreadPoolExecutor$ManagedScheduledFutureTask.run(ManagedScheduledThreadPoolExecutor.java:534)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
	at org.glassfish.enterprise.concurrent.ManagedThreadFactoryImpl$ManagedThread.run(ManagedThreadFactoryImpl.java:250)

23:38:32,353 INFO  [org.dcm4che3.net.Connection] (EE-ManagedExecutorService-default-Thread-1) Start TCP Listener on /0.0.0.0:11112
23:38:32,715 INFO  [org.dcm4che3.net.Connection] (EE-ManagedExecutorService-default-Thread-2) Start TCP Listener on /0.0.0.0:2762
23:38:32,739 INFO  [org.dcm4che3.net.Connection] (EE-ManagedExecutorService-default-Thread-3) Start TCP Listener on /0.0.0.0:2575
23:38:32,752 INFO  [org.dcm4che3.net.Connection] (EE-ManagedExecutorService-default-Thread-4) Start TCP Listener on /0.0.0.0:12575
23:38:32,971 INFO  [org.wildfly.extension.undertow] (ServerService Thread Pool -- 71) WFLYUT0021: Registered web context: /dcm4chee-arc/ui
23:38:32,972 INFO  [org.wildfly.extension.undertow] (ServerService Thread Pool -- 64) WFLYUT0021: Registered web context: /dcm4chee-arc
23:38:33,350 INFO  [org.dcm4che3.net.audit.AuditLogger] (ServerService Thread Pool -- 70) Send audit message to localhost/127.0.0.1:514
23:38:33,422 INFO  [org.jboss.as.server] (Controller Boot Thread) WFLYSRV0010: Deployed "dcm4chee-arc" (runtime-name : "dcm4chee-arc-ear-5.1.0-mysql.ear")
23:38:33,829 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0060: Http management interface listening on http://127.0.0.1:9990/management
23:38:33,829 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0051: Admin console listening on http://127.0.0.1:9990
23:38:33,830 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0025: WildFly Full 9.0.2.Final (WildFly Core 1.0.2.Final) started in 18972ms - Started 1474 of 1734 services (366 services are lazy, passive or on-demand)
23:39:32,318 WARN  [org.dcm4chee.arc.audit.AuditService] (EE-ManagedScheduledExecutorService-default-Thread-1) Failed to read Audit Spool File - /home/sv/dev/wildfly-9.0.2.Final/standalone/data/audit-spool/QUERY_QIDO2879467148414962087.tmp : java.io.EOFException
	at java.io.DataInputStream.readUnsignedShort(DataInputStream.java:340)
	at java.io.DataInputStream.readUTF(DataInputStream.java:589)
	at java.io.DataInputStream.readUTF(DataInputStream.java:564)
	at org.dcm4chee.arc.audit.AuditService.auditQuery(AuditService.java:433)
	at org.dcm4chee.arc.audit.AuditService.aggregateAuditMessage(AuditService.java:137)
	at org.dcm4chee.arc.audit.AuditService$Proxy$_$$_WeldClientProxy.aggregateAuditMessage(Unknown Source)
	at org.dcm4chee.arc.audit.AuditScheduler.execute(AuditScheduler.java:115)
	at org.dcm4chee.arc.Scheduler.run(Scheduler.java:65)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at org.glassfish.enterprise.concurrent.internal.ManagedScheduledThreadPoolExecutor$ManagedScheduledFutureTask.access$201(ManagedScheduledThreadPoolExecutor.java:383)
	at org.glassfish.enterprise.concurrent.internal.ManagedScheduledThreadPoolExecutor$ManagedScheduledFutureTask.run(ManagedScheduledThreadPoolExecutor.java:534)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
	at org.glassfish.enterprise.concurrent.ManagedThreadFactoryImpl$ManagedThread.run(ManagedThreadFactoryImpl.java:250)

23:40:32,328 WARN  [org.dcm4chee.arc.audit.AuditService] (EE-ManagedScheduledExecutorService-default-Thread-1) Failed to read Audit Spool File - /home/sv/dev/wildfly-9.0.2.Final/standalone/data/audit-spool/QUERY_QIDO2879467148414962087.tmp : java.io.EOFException
	at java.io.DataInputStream.readUnsignedShort(DataInputStream.java:340)
	at java.io.DataInputStream.readUTF(DataInputStream.java:589)
	at java.io.DataInputStream.readUTF(DataInputStream.java:564)
	at org.dcm4chee.arc.audit.AuditService.auditQuery(AuditService.java:433)
	at org.dcm4chee.arc.audit.AuditService.aggregateAuditMessage(AuditService.java:137)
	at org.dcm4chee.arc.audit.AuditService$Proxy$_$$_WeldClientProxy.aggregateAuditMessage(Unknown Source)
	at org.dcm4chee.arc.audit.AuditScheduler.execute(AuditScheduler.java:115)
	at org.dcm4chee.arc.Scheduler.run(Scheduler.java:65)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at org.glassfish.enterprise.concurrent.internal.ManagedScheduledThreadPoolExecutor$ManagedScheduledFutureTask.access$201(ManagedScheduledThreadPoolExecutor.java:383)
	at org.glassfish.enterprise.concurrent.internal.ManagedScheduledThreadPoolExecutor$ManagedScheduledFutureTask.run(ManagedScheduledThreadPoolExecutor.java:534)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
	at org.glassfish.enterprise.concurrent.ManagedThreadFactoryImpl$ManagedThread.run(ManagedThreadFactoryImpl.java:250)

**Comment by vrindanayak** [comment]
Can you please update to the latest version of dcm4chee-arc-light 5.2.0 and retry?

**Comment by dhanzhang** [comment]
@vrindanayak   OK  ， And so I tried to use the 5.2 version after feedback。

**Comment by dhanzhang** [comment]
@vrindanayak   when setup   5.2    ,can't deploy !


[standalone@localhost:9990 /] deploy  ~/dev/dcm4chee-arc-5.2.0-mysql/deploy/dcm4chee-arc-ear-5.2.0-mysql.ear
{"WFLYCTL0062: Composite operation failed and was rolled back. Steps that failed:" => {"Operation step-2" => {"WFLYCTL0080: Failed services" => {"jboss.module.service.\"deployment.dcm4chee-arc-ear-5.2.0-mysql.ear.dcm4chee-arc-code-5.2.0.jar\".main" => "org.jboss.msc.service.StartException in service jboss.module.service.\"deployment.dcm4chee-arc-ear-5.2.0-mysql.ear.dcm4chee-arc-code-5.2.0.jar\".main: WFLYSRV0179: Failed to load module: deployment.dcm4chee-arc-ear-5.2.0-mysql.ear.dcm4chee-arc-code-5.2.0.jar:main
    Caused by: org.jboss.modules.ModuleNotFoundException: org.keycloak.keycloak-core:main","jboss.module.service.\"deployment.dcm4chee-arc-ear-5.2.0-mysql.ear.dcm4chee-arc-patient-5.2.0.jar\".main" => "org.jboss.msc.service.StartException in service jboss.module.service.\"deployment.dcm4chee-arc-ear-5.2.0-mysql.ear.dcm4chee-arc-patient-5.2.0.jar\".main: WFLYSRV0179: Failed to load module: deployment.dcm4chee-arc-ear-5.2.0-mysql.ear.dcm4chee-arc-patient-5.2.0.jar:main
    Caused by: org.jboss.modules.ModuleNotFoundException: org.keycloak.keycloak-core:main","jboss.module.service.\"deployment.dcm4chee-arc-ear-5.2.0-mysql.ear.dcm4chee-arc-store-5.2.0.jar\".main" => "org.jboss.msc.service.StartException in service jboss.module.service.\"deployment.dcm4chee-arc-ear-5.2.0-mysql.ear.dcm4chee-arc-store-5.2.0.jar\".main: WFLYSRV0179: Failed to load module: deployment.dcm4chee-arc-ear-5.2.0-mysql.ear.dcm4chee-arc-store-5.2.0.jar:main
    Caused by: org.jboss.modules.ModuleNotFoundException: org.keycloak.keycloak-core:main","jboss.module.service.\"deployment.dcm4chee-arc-ear-5.2.0-mysql.ear.dcm4chee-arc-retrieve-5.2.0.jar\".main" => "org.jboss.msc.service.StartException in service jboss.module.service.\"deployment.dcm4chee-arc-ear-5.2.0-mysql.ear.dcm4chee-arc-retrieve-5.2.0.jar\".main: WFLYSRV0179: Failed to load module: deployment.dcm4chee-arc-ear-5.2.0-mysql.ear.dcm4chee-arc-retrieve-5.2.0.jar:main
    Caused by: org.jboss.modules.ModuleNotFoundException: org.keycloak.keycloak-core:main","jboss.module.service.\"deployment.dcm4chee-arc-ear-5.2.0-mysql.ear.dcm4chee-arc-delete-5.2.0.jar\".main" => "org.jboss.msc.service.StartException in service jboss.module.service.\"deployment.dcm4chee-arc-ear-5.2.0-mysql.ear.dcm4chee-arc-delete-5.2.0.jar\".main: WFLYSRV0179: Failed to load module: deployment.dcm4chee-arc-ear-5.2.0-mysql.ear.dcm4chee-arc-delete-5.2.0.jar:main
    Caused by: org.jboss.modules.ModuleNotFoundException: org.keycloak.keycloak-core:main","jboss.module.service.\"deployment.dcm4chee-arc-ear-5.2.0-mysql.ear.dcm4chee-arc-query-5.2.0.jar\".main" => "org.jboss.msc.service.StartException in service jboss.module.service.\"deployment.dcm4chee-arc-ear-5.2.0-mysql.ear.dcm4chee-arc-query-5.2.0.jar\".main: WFLYSRV0179: Failed to load module: deployment.dcm4chee-arc-ear-5.2.0-mysql.ear.dcm4chee-arc-query-5.2.0.jar:main
    Caused by: org.jboss.modules.ModuleNotFoundException: org.keycloak.keycloak-core:main","jboss.module.service.\"deployment.dcm4chee-arc-ear-5.2.0-mysql.ear.dcm4chee-arc-ian-scu-5.2.0.jar\".main" => "org.jboss.msc.service.StartException in service jboss.module.service.\"deployment.dcm4chee-arc-ear-5.2.0-mysql.ear.dcm4chee-arc-ian-scu-5.2.0.jar\".main: WFLYSRV0179: Failed to load module: deployment.dcm4chee-arc-ear-5.2.0-mysql.ear.dcm4chee-arc-ian-scu-5.2.0.jar:main
    Caused by: org.jboss.modules.ModuleNotFoundException: org.keycloak.keycloak-core:main","jboss.module.service.\"deployment.dcm4chee-arc-ear-5.2.0-mysql.ear.dcm4chee-arc-war-5.2.0-unsecure.war\".main" => "org.jboss.msc.service.StartException in service jboss.module.service.\"deployment.dcm4chee-arc-ear-5.2.0-mysql.ear.dcm4chee-arc-war-5.2.0-unsecure.war\".main: WFLYSRV0179: Failed to load module: deployment.dcm4chee-arc-ear-5.2.0-mysql.ear.dcm4chee-arc-war-5.2.0-unsecure.war:main
    Caused by: org.jboss.modules.ModuleNotFoundException: org.keycloak.keycloak-core:main","jboss.module.service.\"deployment.dcm4chee-arc-ear-5.2.0-mysql.ear.dcm4chee-arc-mpps-5.2.0.jar\".main" => "org.jboss.msc.service.StartException in service jboss.module.service.\"deployment.dcm4chee-arc-ear-5.2.0-mysql.ear.dcm4chee-arc-mpps-5.2.0.jar\".main: WFLYSRV0179: Failed to load module: deployment.dcm4chee-arc-ear-5.2.0-mysql.ear.dcm4chee-arc-mpps-5.2.0.jar:main
    Caused by: org.jboss.modules.ModuleNotFoundException: org.keycloak.keycloak-core:main","jboss.module.service.\"deployment.dcm4chee-arc-ear-5.2.0-mysql.ear.dcm4chee-arc-mpps-scu-5.2.0.jar\".main" => "org.jboss.msc.service.StartException in service jboss.module.service.\"deployment.dcm4chee-arc-ear-5.2.0-mysql.ear.dcm4chee-arc-mpps-scu-5.2.0.jar\".main: WFLYSRV0179: Failed to load module: deployment.dcm4chee-arc-ear-5.2.0-mysql.ear.dcm4chee-arc-mpps-scu-5.2.0.jar:main
    Caused by: org.jboss.modules.ModuleNotFoundException: org.keycloak.keycloak-core:main","jboss.module.service.\"deployment.dcm4chee-arc-ear-5.2.0-mysql.ear.dcm4chee-arc-issuer-5.2.0.jar\".main" => "org.jboss.msc.service.StartException in service jboss.module.service.\"deployment.dcm4chee-arc-ear-5.2.0-mysql.ear.dcm4chee-arc-issuer-5.2.0.jar\".main: WFLYSRV0179: Failed to load module: deployment.dcm4chee-arc-ear-5.2.0-mysql.ear.dcm4chee-arc-issuer-5.2.0.jar:main
    Caused by: org.jboss.modules.ModuleNotFoundException: org.keycloak.keycloak-core:main","jboss.module.service.\"deployment.dcm4chee-arc-ear-5.2.0-mysql.ear.dcm4chee-arc-service-5.2.0.jar\".main" => "org.jboss.msc.service.StartException in service jboss.module.service.\"deployment.dcm4chee-arc-ear-5.2.0-mysql.ear.dcm4chee-arc-service-5.2.0.jar\".main: WFLYSRV0179: Failed to load module: deployment.dcm4chee-arc-ear-5.2.0-mysql.ear.dcm4chee-arc-service-5.2.0.jar:main
    Caused by: org.jboss.modules.ModuleNotFoundException: org.keycloak.keycloak-core:main","jboss.module.service.\"deployment.dcm4chee-arc-ear-5.2.0-mysql.ear.dcm4chee-arc-stgcmt-scp-5.2.0.jar\".main" => "org.jboss.msc.service.StartException in service jboss.module.service.\"deployment.dcm4chee-arc-ear-5.2.0-mysql.ear.dcm4chee-arc-stgcmt-scp-5.2.0.jar\".main: WFLYSRV0179: Failed to load module: deployment.dcm4chee-arc-ear-5.2.0-mysql.ear.dcm4chee-arc-stgcmt-scp-5.2.0.jar:main
    Caused by: org.jboss.modules.ModuleNotFoundException: org.keycloak.keycloak-core:main","jboss.module.service.\"deployment.dcm4chee-arc-ear-5.2.0-mysql.ear\".main" => "org.jboss.msc.service.StartException in service jboss.module.service.\"deployment.dcm4chee-arc-ear-5.2.0-mysql.ear\".main: WFLYSRV0179: Failed to load module: deployment.dcm4chee-arc-ear-5.2.0-mysql.ear:main
    Caused by: org.jboss.modules.ModuleNotFoundException: org.keycloak.keycloak-core:main","jboss.module.service.\"deployment.dcm4chee-arc-ear-5.2.0-mysql.ear.dcm4chee-arc-qmgt-5.2.0.jar\".main" => "org.jboss.msc.service.StartException in service jboss.module.service.\"deployment.dcm4chee-arc-ear-5.2.0-mysql.ear.dcm4chee-arc-qmgt-5.2.0.jar\".main: WFLYSRV0179: Failed to load module: deployment.dcm4chee-arc-ear-5.2.0-mysql.ear.dcm4chee-arc-qmgt-5.2.0.jar:main
    Caused by: org.jboss.modules.ModuleNotFoundException: org.keycloak.keycloak-core:main","jboss.module.service.\"deployment.dcm4chee-arc-ear-5.2.0-mysql.ear.dcm4chee-arc-export-mgt-5.2.0.jar\".main" => "org.jboss.msc.service.StartException in service jboss.module.service.\"deployment.dcm4chee-arc-ear-5.2.0-mysql.ear.dcm4chee-arc-export-mgt-5.2.0.jar\".main: WFLYSRV0179: Failed to load module: deployment.dcm4chee-arc-ear-5.2.0-mysql.ear.dcm4chee-arc-export-mgt-5.2.0.jar:main
    Caused by: org.jboss.modules.ModuleNotFoundException: org.keycloak.keycloak-core:main","jboss.module.service.\"deployment.dcm4chee-arc-ear-5.2.0-mysql.ear.dcm4chee-arc-ui-5.2.0-unsecure.war\".main" => "org.jboss.msc.service.StartException in service jboss.module.service.\"deployment.dcm4chee-arc-ear-5.2.0-mysql.ear.dcm4chee-arc-ui-5.2.0-unsecure.war\".main: WFLYSRV0179: Failed to load module: deployment.dcm4chee-arc-ear-5.2.0-mysql.ear.dcm4chee-arc-ui-5.2.0-unsecure.war:main
    Caused by: org.jboss.modules.ModuleNotFoundException: org.keycloak.keycloak-core:main"}}}}
[standalone@localhost:9990 /] deploy  ~/dev/dcm4chee-arc-5.2.0-mysql/deploy/dcm4chee-arc-ear-5.2.0-mysql.ear
{"WFLYCTL0062: Composite operation failed and was rolled back. Steps that failed:" => {"Operation step-2" => {"WFLYCTL0080: Failed services" => {"jboss.module.service.\"deployment.dcm4chee-arc-ear-5.2.0-mysql.ear.dcm4chee-arc-ian-scu-5.2.0.jar\".main" => "org.jboss.msc.service.StartException in service jboss.module.service.\"deployment.dcm4chee-arc-ear-5.2.0-mysql.ear.dcm4chee-arc-ian-scu-5.2.0.jar\".main: WFLYSRV0179: Failed to load module: deployment.dcm4chee-arc-ear-5.2.0-mysql.ear.dcm4chee-arc-ian-scu-5.2.0.jar:main
    Caused by: org.jboss.modules.ModuleNotFoundException: org.keycloak.keycloak-core:main","jboss.module.service.\"deployment.dcm4chee-arc-ear-5.2.0-mysql.ear.dcm4chee-arc-store-5.2.0.jar\".main" => "org.jboss.msc.service.StartException in service jboss.module.service.\"deployment.dcm4chee-arc-ear-5.2.0-mysql.ear.dcm4chee-arc-store-5.2.0.jar\".main: WFLYSRV0179: Failed to load module: deployment.dcm4chee-arc-ear-5.2.0-mysql.ear.dcm4chee-arc-store-5.2.0.jar:main
    Caused by: org.jboss.modules.ModuleNotFoundException: org.keycloak.keycloak-core:main","jboss.module.service.\"deployment.dcm4chee-arc-ear-5.2.0-mysql.ear.dcm4chee-arc-code-5.2.0.jar\".main" => "org.jboss.msc.service.StartException in service jboss.module.service.\"deployment.dcm4chee-arc-ear-5.2.0-mysql.ear.dcm4chee-arc-code-5.2.0.jar\".main: WFLYSRV0179: Failed to load module: deployment.dcm4chee-arc-ear-5.2.0-mysql.ear.dcm4chee-arc-code-5.2.0.jar:main
    Caused by: org.jboss.modules.ModuleNotFoundException: org.keycloak.keycloak-core:main","jboss.module.service.\"deployment.dcm4chee-arc-ear-5.2.0-mysql.ear.dcm4chee-arc-war-5.2.0-unsecure.war\".main" => "org.jboss.msc.service.StartException in service jboss.module.service.\"deployment.dcm4chee-arc-ear-5.2.0-mysql.ear.dcm4chee-arc-war-5.2.0-unsecure.war\".main: WFLYSRV0179: Failed to load module: deployment.dcm4chee-arc-ear-5.2.0-mysql.ear.dcm4chee-arc-war-5.2.0-unsecure.war:main
    Caused by: org.jboss.modules.ModuleNotFoundException: org.keycloak.keycloak-core:main","jboss.module.service.\"deployment.dcm4chee-arc-ear-5.2.0-mysql.ear.dcm4chee-arc-export-mgt-5.2.0.jar\".main" => "org.jboss.msc.service.StartException in service jboss.module.service.\"deployment.dcm4chee-arc-ear-5.2.0-mysql.ear.dcm4chee-arc-export-mgt-5.2.0.jar\".main: WFLYSRV0179: Failed to load module: deployment.dcm4chee-arc-ear-5.2.0-mysql.ear.dcm4chee-arc-export-mgt-5.2.0.jar:main
    Caused by: org.jboss.modules.ModuleNotFoundException: org.keycloak.keycloak-core:main","jboss.module.service.\"deployment.dcm4chee-arc-ear-5.2.0-mysql.ear.dcm4chee-arc-mpps-scu-5.2.0.jar\".main" => "org.jboss.msc.service.StartException in service jboss.module.service.\"deployment.dcm4chee-arc-ear-5.2.0-mysql.ear.dcm4chee-arc-mpps-scu-5.2.0.jar\".main: WFLYSRV0179: Failed to load module: deployment.dcm4chee-arc-ear-5.2.0-mysql.ear.dcm4chee-arc-mpps-scu-5.2.0.jar:main
    Caused by: org.jboss.modules.ModuleNotFoundException: org.keycloak.keycloak-core:main","jboss.module.service.\"deployment.dcm4chee-arc-ear-5.2.0-mysql.ear.dcm4chee-arc-issuer-5.2.0.jar\".main" => "org.jboss.msc.service.StartException in service jboss.module.service.\"deployment.dcm4chee-arc-ear-5.2.0-mysql.ear.dcm4chee-arc-issuer-5.2.0.jar\".main: WFLYSRV0179: Failed to load module: deployment.dcm4chee-arc-ear-5.2.0-mysql.ear.dcm4chee-arc-issuer-5.2.0.jar:main
    Caused by: org.jboss.modules.ModuleNotFoundException: org.keycloak.keycloak-core:main","jboss.module.service.\"deployment.dcm4chee-arc-ear-5.2.0-mysql.ear.dcm4chee-arc-retrieve-5.2.0.jar\".main" => "org.jboss.msc.service.StartException in service jboss.module.service.\"deployment.dcm4chee-arc-ear-5.2.0-mysql.ear.dcm4chee-arc-retrieve-5.2.0.jar\".main: WFLYSRV0179: Failed to load module: deployment.dcm4chee-arc-ear-5.2.0-mysql.ear.dcm4chee-arc-retrieve-5.2.0.jar:main
    Caused by: org.jboss.modules.ModuleNotFoundException: org.keycloak.keycloak-core:main","jboss.module.service.\"deployment.dcm4chee-arc-ear-5.2.0-mysql.ear.dcm4chee-arc-delete-5.2.0.jar\".main" => "org.jboss.msc.service.StartException in service jboss.module.service.\"deployment.dcm4chee-arc-ear-5.2.0-mysql.ear.dcm4chee-arc-delete-5.2.0.jar\".main: WFLYSRV0179: Failed to load module: deployment.dcm4chee-arc-ear-5.2.0-mysql.ear.dcm4chee-arc-delete-5.2.0.jar:main
    Caused by: org.jboss.modules.ModuleNotFoundException: org.keycloak.keycloak-core:main","jboss.module.service.\"deployment.dcm4chee-arc-ear-5.2.0-mysql.ear.dcm4chee-arc-query-5.2.0.jar\".main" => "org.jboss.msc.service.StartException in service jboss.module.service.\"deployment.dcm4chee-arc-ear-5.2.0-mysql.ear.dcm4chee-arc-query-5.2.0.jar\".main: WFLYSRV0179: Failed to load module: deployment.dcm4chee-arc-ear-5.2.0-mysql.ear.dcm4chee-arc-query-5.2.0.jar:main
    Caused by: org.jboss.modules.ModuleNotFoundException: org.keycloak.keycloak-core:main","jboss.module.service.\"deployment.dcm4chee-arc-ear-5.2.0-mysql.ear.dcm4chee-arc-qmgt-5.2.0.jar\".main" => "org.jboss.msc.service.StartException in service jboss.module.service.\"deployment.dcm4chee-arc-ear-5.2.0-mysql.ear.dcm4chee-arc-qmgt-5.2.0.jar\".main: WFLYSRV0179: Failed to load module: deployment.dcm4chee-arc-ear-5.2.0-mysql.ear.dcm4chee-arc-qmgt-5.2.0.jar:main
    Caused by: org.jboss.modules.ModuleNotFoundException: org.keycloak.keycloak-core:main","jboss.module.service.\"deployment.dcm4chee-arc-ear-5.2.0-mysql.ear.dcm4chee-arc-mpps-5.2.0.jar\".main" => "org.jboss.msc.service.StartException in service jboss.module.service.\"deployment.dcm4chee-arc-ear-5.2.0-mysql.ear.dcm4chee-arc-mpps-5.2.0.jar\".main: WFLYSRV0179: Failed to load module: deployment.dcm4chee-arc-ear-5.2.0-mysql.ear.dcm4chee-arc-mpps-5.2.0.jar:main
    Caused by: org.jboss.modules.ModuleNotFoundException: org.keycloak.keycloak-core:main","jboss.module.service.\"deployment.dcm4chee-arc-ear-5.2.0-mysql.ear.dcm4chee-arc-stgcmt-scp-5.2.0.jar\".main" => "org.jboss.msc.service.StartException in service jboss.module.service.\"deployment.dcm4chee-arc-ear-5.2.0-mysql.ear.dcm4chee-arc-stgcmt-scp-5.2.0.jar\".main: WFLYSRV0179: Failed to load module: deployment.dcm4chee-arc-ear-5.2.0-mysql.ear.dcm4chee-arc-stgcmt-scp-5.2.0.jar:main
    Caused by: org.jboss.modules.ModuleNotFoundException: org.keycloak.keycloak-core:main","jboss.module.service.\"deployment.dcm4chee-arc-ear-5.2.0-mysql.ear.dcm4chee-arc-patient-5.2.0.jar\".main" => "org.jboss.msc.service.StartException in service jboss.module.service.\"deployment.dcm4chee-arc-ear-5.2.0-mysql.ear.dcm4chee-arc-patient-5.2.0.jar\".main: WFLYSRV0179: Failed to load module: deployment.dcm4chee-arc-ear-5.2.0-mysql.ear.dcm4chee-arc-patient-5.2.0.jar:main
    Caused by: org.jboss.modules.ModuleNotFoundException: org.keycloak.keycloak-core:main","jboss.module.service.\"deployment.dcm4chee-arc-ear-5.2.0-mysql.ear.dcm4chee-arc-ui-5.2.0-unsecure.war\".main" => "org.jboss.msc.service.StartException in service jboss.module.service.\"deployment.dcm4chee-arc-ear-5.2.0-mysql.ear.dcm4chee-arc-ui-5.2.0-unsecure.war\".main: WFLYSRV0179: Failed to load module: deployment.dcm4chee-arc-ear-5.2.0-mysql.ear.dcm4chee-arc-ui-5.2.0-unsecure.war:main
    Caused by: org.jboss.modules.ModuleNotFoundException: org.keycloak.keycloak-core:main","jboss.module.service.\"deployment.dcm4chee-arc-ear-5.2.0-mysql.ear.dcm4chee-arc-service-5.2.0.jar\".main" => "org.jboss.msc.service.StartException in service jboss.module.service.\"deployment.dcm4chee-arc-ear-5.2.0-mysql.ear.dcm4chee-arc-service-5.2.0.jar\".main: WFLYSRV0179: Failed to load module: deployment.dcm4chee-arc-ear-5.2.0-mysql.ear.dcm4chee-arc-service-5.2.0.jar:main
    Caused by: org.jboss.modules.ModuleNotFoundException: org.keycloak.keycloak-core:main","jboss.module.service.\"deployment.dcm4chee-arc-ear-5.2.0-mysql.ear\".main" => "org.jboss.msc.service.StartException in service jboss.module.service.\"deployment.dcm4chee-arc-ear-5.2.0-mysql.ear\".main: WFLYSRV0179: Failed to load module: deployment.dcm4chee-arc-ear-5.2.0-mysql.ear:main
    Caused by: org.jboss.modules.ModuleNotFoundException: org.keycloak.keycloak-core:main"}}}}
[standalone@localhost:9990 /] deploy  ~/dev/dcm4chee-arc-5.2.0-mysql/deploy/dcm4chee-arc-ear-5.2.0-mysql.ear --name=dcm4chee-arc
{"WFLYCTL0062: Composite operation failed and was rolled back. Steps that failed:" => {"Operation step-2" => {"WFLYCTL0080: Failed services" => {"jboss.module.service.\"deployment.dcm4chee-arc\".main" => "org.jboss.msc.service.StartException in service jboss.module.service.\"deployment.dcm4chee-arc\".main: WFLYSRV0179: Failed to load module: deployment.dcm4chee-arc:main
    Caused by: org.jboss.modules.ModuleNotFoundException: org.keycloak.keycloak-core:main"}}}}

**Comment by dhanzhang** [comment]
@vrindanayak  JDK version is  1.7     wildfly is  9.0.2.Final

**Comment by vrindanayak** [comment]
Maybe you have forgotten to install DCM4CHE dcm4chee-arc-light libraries as JBoss modules mentioned in Step 3 of Setup Wildfly -  https://github.com/dcm4che/dcm4chee-arc-light/wiki/Upgrade#update-wildfly-deployment

**Comment by vrindanayak** [comment]
Please update to Wildfly 10.0.0 Final and Java JDK 1.8 for using the new archive version 5.2.0

**Comment by dhanzhang** [comment]
@vrindanayak when use  JDK 1.8 ,   OpenDJ 2.6.0  is setup failed !  Open DJ 3.0.0 is not adapted with 2.6.0

**Comment by gunterze** [comment]
We have not yet found time on investigating Open DJ 3.0.0. If OpenDJ 2.6.0
does not run on Java 8, you may still run it with Java 7. Just Wildfly 10
requires Java 8.

**Comment by gunterze** [comment]
Please post further questions about update to 5.2.0 to [dcm4che google group](https://groups.google.com/forum/#!forum/dcm4che)
