### ISSUE TITLE
Proxy requests return empty Study Instance UID

### ISSUE THREAD

**Issue by ghost** [dcm4che/dcm4chee-arc-light#1263]
Hello,
I'm trying to setup the proxy retrieve requests according to the wiki page.
I'm getting the following results:

Quering the Spanning C-Find SCP directly will result in a response containing study instance UIDs
![findorig from ui](https://user-images.githubusercontent.com/178301/37031384-36a9a5aa-2147-11e8-9060-2fe4371d4cb1.png)

Querying the the DCM4CHEE will result in a response without study instance UIDs
![find from ui](https://user-images.githubusercontent.com/178301/37031390-3a909156-2147-11e8-9680-be412c20550a.png)

If study instance UIDs are empty, different clients will behave in a different way. For example RadiAnt viewer will show 0 results when querying DCM4CHEE while K-Pacs will show patient results, but fail when trying to retrieve with the following error on server.log

```
2018-03-06 13:50:38,536 INFO  [org.dcm4che3.net.Association] (EE-ManagedExecutorService-default-Thread-277) DCM4CHEE<-KPServer(241): processing 3:C-MOVE-RQ[pcid=1, prior=0
  cuid=1.2.840.10008.5.1.4.1.2.2.2 - Study Root Query/Retrieve Information Model - MOVE
  tsuid=1.2.840.10008.1.2 - Implicit VR Little Endian failed. Caused by:	: org.dcm4che3.net.service.DicomServiceException: Missing StudyInstanceUID (0020,000D)
	at org.dcm4che3.net.service.QueryRetrieveLevel2.identifierDoesNotMatchSOPClass(QueryRetrieveLevel2.java:147)
	at org.dcm4che3.net.service.QueryRetrieveLevel2.missingAttribute(QueryRetrieveLevel2.java:136)
	at org.dcm4che3.net.service.QueryRetrieveLevel2.checkUniqueKey(QueryRetrieveLevel2.java:130)
	at org.dcm4che3.net.service.QueryRetrieveLevel2.validateIdentifier(QueryRetrieveLevel2.java:119)
	at org.dcm4che3.net.service.QueryRetrieveLevel2.validateRetrieveIdentifier(QueryRetrieveLevel2.java:89)
	at org.dcm4chee.arc.retrieve.scp.CommonCMoveSCP.calculateMatches(CommonCMoveSCP.java:96)
	at org.dcm4che3.net.service.BasicCMoveSCP.onDimseRQ(BasicCMoveSCP.java:66)
	at org.dcm4che3.net.service.AbstractDicomService.onDimseRQ(AbstractDicomService.java:74)
	at sun.reflect.GeneratedMethodAccessor84.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.weld.bean.proxy.AbstractBeanInstance.invoke(AbstractBeanInstance.java:38)
	at org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke(ProxyMethodHandler.java:100)
	at org.dcm4che3.net.service.DicomService$168648098$Proxy$_$$_WeldClientProxy.onDimseRQ(Unknown Source)
	at org.dcm4che3.net.service.DicomServiceRegistry.onDimseRQ(DicomServiceRegistry.java:86)
	at org.dcm4che3.net.ApplicationEntity.onDimseRQ(ApplicationEntity.java:459)
	at org.dcm4che3.net.Association.onDimseRQ(Association.java:696)
	at org.dcm4che3.net.PDUDecoder.decodeDIMSE(PDUDecoder.java:459)
	at org.dcm4che3.net.Association.handlePDataTF(Association.java:679)
	at org.dcm4che3.net.State$4.onPDataTF(State.java:103)
	at org.dcm4che3.net.Association.onPDataTF(Association.java:675)
	at org.dcm4che3.net.PDUDecoder.nextPDU(PDUDecoder.java:177)
	at org.dcm4che3.net.Association$2.run(Association.java:518)
	at org.jboss.as.ee.concurrent.ControlPointUtils$ControlledRunnable.run(ControlPointUtils.java:105)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.glassfish.enterprise.concurrent.internal.ManagedFutureTask.run(ManagedFutureTask.java:141)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at org.glassfish.enterprise.concurrent.ManagedThreadFactoryImpl$ManagedThread.run(ManagedThreadFactoryImpl.java:250)
	at org.jboss.as.ee.concurrent.service.ElytronManagedThreadFactory$ElytronManagedThread.run(ElytronManagedThreadFactory.java:78)

2018-03-06 13:50:38,536 INFO  [org.dcm4che3.net.Dimse] (EE-ManagedExecutorService-default-Thread-277) DCM4CHEE<-KPServer(241) << 3:C-MOVE-RSP[pcid=1, status=a900H, errorComment=Missing StudyInstanceUID (0020,000D)
  tsuid=1.2.840.10008.1.2 - Implicit VR Little Endian
```

**Comment by gunterze** [comment]
Any DICOM compliant archive have to return the Study Instance UID in pending C-FIND RSPs, if the attribute was present in the C-FIND RQ - independently if it had a non empty value (=List of UID Matching) or not (=Universal Matching):

s. [DICOM PS3.4, C.4.1.1.3.2 Response Identifier Structure](http://dicom.nema.org/medical/dicom/current/output/html/part04.html#sect_C.4.1.1.3.2):

> An Identifier in a C-FIND response shall contain:
> -   Key Attributes with values corresponding to Key Attributes contained in the Identifier of the request.

**Comment by gunterze** [comment]
Which wiki page do you referring for configuration of a Spanning C-Find SCP?

**Comment by Squall5668** [comment]
I'm following this page
https://github.com/dcm4che/dcm4chee-arc-light/wiki/Proxy-retrieve-requests-to-another-Archive
The c-find requests do not contain study instance UIDs. Is this the intended behavior then?

**Comment by gunterze** [comment]
But that Wiki page currently only describe function and configuration as a Retrieve Proxy, but not how to make use of #910  - just did not yet found the time for updating the page.
So what did you have configured?

**Comment by Squall5668** [comment]
Thanks for helping, this is the relevant configuration for spanning C-Find that I have set
![span fallback](https://user-images.githubusercontent.com/178301/37235910-6678fe36-240b-11e8-8095-4726c0586793.png)
This is currently set on the archive device level

**Comment by dsims321** [comment]
Did you have any luck getting this to work? I've ran into the same issue.

 Not able to actually retrieve the studies, since I'm not getting a Study Instance UID
