### ISSUE TITLE
Storage[id=fs1, uri=file:///storage/pacs1/] not accessable

### ISSUE THREAD

**Issue by mikkeljohnsen** [dcm4che/dcm4chee-arc-light#1548]
I'm using the latest "dcm4che/dcm4chee-arc-psql:5.13.3-secure" with docker.
I'm trying to transfer some files to the new setup, but I get:

```
#storescu -c DCM4CHEE@192.168.2.7:11112 /storage/pacs1/backup/archive/2016/4/19/10/42A4EDBE/DD52A214/9007275A 
Scanning files to send
.
Scanned 1 files in 0.094s (=94ms/file)
07:22:22,666 INFO  - Initiate connection from 0.0.0.0/0.0.0.0:0 to 192.168.2.7:11112
07:22:22,677 INFO  - Established connection Socket[addr=/192.168.2.7,port=11112,localport=52857]
07:22:22,694 DEBUG - /172.17.0.7:52857->/192.168.2.7:11112(1): enter state: Sta4 - Awaiting transport connection opening to complete
07:22:22,698 INFO  - STORESCU->DCM4CHEE(1) << A-ASSOCIATE-RQ
07:22:22,711 DEBUG - A-ASSOCIATE-RQ[
  calledAET: DCM4CHEE
  callingAET: STORESCU
  applicationContext: 1.2.840.10008.3.1.1.1 - DICOM Application Context Name
  implClassUID: 1.2.40.0.13.1.3
  implVersionName: dcm4che-5.13.3
  maxPDULength: 16378
  maxOpsInvoked/maxOpsPerformed: 0/0
  PresentationContext[id: 1
    as: 1.2.840.10008.1.1 - Verification SOP Class
    ts: 1.2.840.10008.1.2 - Implicit VR Little Endian
  ]
  PresentationContext[id: 3
    as: 1.2.840.10008.5.1.4.1.1.1 - Computed Radiography Image Storage
    ts: 1.2.840.10008.1.2.1 - Explicit VR Little Endian
  ]
  PresentationContext[id: 5
    as: 1.2.840.10008.5.1.4.1.1.1 - Computed Radiography Image Storage
    ts: 1.2.840.10008.1.2 - Implicit VR Little Endian
  ]
]
07:22:22,711 DEBUG - STORESCU->DCM4CHEE(1): enter state: Sta5 - Awaiting A-ASSOCIATE-AC or A-ASSOCIATE-RJ PDU
07:22:22,714 INFO  - STORESCU->DCM4CHEE(1) >> A-ASSOCIATE-AC
07:22:22,714 DEBUG - A-ASSOCIATE-AC[
  calledAET: DCM4CHEE
  callingAET: STORESCU
  applicationContext: 1.2.840.10008.3.1.1.1 - DICOM Application Context Name
  implClassUID: 1.2.40.0.13.1.3
  implVersionName: dcm4che-5.13.3
  maxPDULength: 16378
  maxOpsInvoked/maxOpsPerformed: 0/0
  PresentationContext[id: 1
    result: 0 - acceptance
    ts: 1.2.840.10008.1.2 - Implicit VR Little Endian
  ]
  PresentationContext[id: 3
    result: 0 - acceptance
    ts: 1.2.840.10008.1.2.1 - Explicit VR Little Endian
  ]
  PresentationContext[id: 5
    result: 0 - acceptance
    ts: 1.2.840.10008.1.2 - Implicit VR Little Endian
  ]
]
07:22:22,715 DEBUG - STORESCU->DCM4CHEE(1): enter state: Sta6 - Association established and ready for data transfer
Connected to DCM4CHEE in 58ms
07:22:22,723 INFO  - STORESCU->DCM4CHEE(1) << 1:C-STORE-RQ[pcid=5, prior=0
  cuid=1.2.840.10008.5.1.4.1.1.1 - Computed Radiography Image Storage
  iuid=1.3.51.5156.1199.20160415.1181639.1 - ?
  tsuid=1.2.840.10008.1.2 - Implicit VR Little Endian
07:22:22,763 DEBUG - Command:
(0000,0002) UI [1.2.840.10008.5.1.4.1.1.1] AffectedSOPClassUID
(0000,0100) US [1] CommandField
(0000,0110) US [1] MessageID
(0000,0700) US [0] Priority
(0000,0800) US [0] CommandDataSetType
(0000,1000) UI [1.3.51.5156.1199.20160415.1181639.1] AffectedSOPInstanceUID

07:22:22,866 INFO  - STORESCU->DCM4CHEE(1) >> 1:C-STORE-RSP[pcid=5, status=110H, errorComment=java.io.IOException: Storage[id=fs1, uri=file:///storage/pacs1/]
  tsuid=1.2.840.10008.1.2 - Implicit VR Little Endian
07:22:22,867 DEBUG - Command:
(0000,0100) US [32769] CommandField
(0000,0120) US [1] MessageIDBeingRespondedTo
(0000,0800) US [257] CommandDataSetType
(0000,0900) US [272] Status
(0000,0902) LO [java.io.IOException: Storage[id=fs1, uri=file:///storage/pacs1

E"ERROR: Received C-STORE-RSP with Status 0110H for /storage/pacs1/backup/archive/2016/4/19/10/42A4EDBE/DD52A214/9007275A"
(0000,0100) US [32769] CommandField
(0000,0120) US [1] MessageIDBeingRespondedTo
(0000,0800) US [257] CommandDataSetType
(0000,0900) US [272] Status
(0000,0902) LO [java.io.IOException: Storage[id=fs1, uri=file:///storage/pacs1

07:22:22,869 INFO  - STORESCU->DCM4CHEE(1) << A-RELEASE-RQ
07:22:22,869 DEBUG - STORESCU->DCM4CHEE(1): enter state: Sta7 - Awaiting A-RELEASE-RP PDU
07:22:22,871 INFO  - STORESCU->DCM4CHEE(1) >> A-RELEASE-RP
07:22:22,871 INFO  - STORESCU->DCM4CHEE(1): close Socket[addr=/192.168.2.7,port=11112,localport=52857]
07:22:22,871 DEBUG - STORESCU->DCM4CHEE(1): enter state: Sta1 - Idle
Sent 0 objects (=0MB) in 0.154s (=0MB/s)
```
The log is:

```
2018-08-23 07:25:07,293 INFO  [org.dcm4che3.net.Connection] (EE-ManagedExecutorService-default-Thread-2) Accept connection Socket[addr=/172.18.0.1,port=53776,localport=11112]
2018-08-23 07:25:07,352 INFO  [org.dcm4che3.net.Association] (EE-ManagedExecutorService-default-Thread-20) DCM4CHEE<-STORESCU(18) >> A-ASSOCIATE-RQ
2018-08-23 07:25:07,352 INFO  [org.dcm4che3.net.Association] (EE-ManagedExecutorService-default-Thread-20) DCM4CHEE<-STORESCU(18) << A-ASSOCIATE-AC
2018-08-23 07:25:07,400 INFO  [org.dcm4che3.net.Dimse] (EE-ManagedExecutorService-default-Thread-20) DCM4CHEE<-STORESCU(18) >> 1:C-STORE-RQ[pcid=5, prior=0
  cuid=1.2.840.10008.5.1.4.1.1.1 - Computed Radiography Image Storage
  iuid=1.3.51.5156.1199.20160415.1181639.1 - ?
  tsuid=1.2.840.10008.1.2 - Implicit VR Little Endian
2018-08-23 07:25:07,506 WARN  [org.dcm4chee.arc.store.impl.StoreServiceImpl] (EE-ManagedExecutorService-default-Thread-20) DCM4CHEE<-STORESCU(18): Failed to valueOf received object:
: java.io.IOException: Storage[id=fs1, uri=file:///storage/pacs1/] not accessable
	at org.dcm4chee.arc.storage.AbstractStorage.checkAccessable(AbstractStorage.java:161)
	at org.dcm4chee.arc.storage.AbstractStorage.openOutputStream(AbstractStorage.java:110)
	at org.dcm4chee.arc.store.impl.StoreServiceImpl.openOutputStream(StoreServiceImpl.java:553)
	at org.dcm4chee.arc.store.impl.StoreServiceImpl.access$200(StoreServiceImpl.java:100)
	at org.dcm4chee.arc.store.impl.StoreServiceImpl$TranscoderHandler.newOutputStream(StoreServiceImpl.java:536)
	at org.dcm4che3.imageio.codec.Transcoder.initDicomOutputStream(Transcoder.java:701)
	at org.dcm4che3.imageio.codec.Transcoder.access$100(Transcoder.java:70)
	at org.dcm4che3.imageio.codec.Transcoder$1.readValue(Transcoder.java:352)
	at org.dcm4che3.io.DicomInputStream.readAttributes(DicomInputStream.java:533)
	at org.dcm4che3.imageio.codec.Transcoder.transcode(Transcoder.java:337)
	at org.dcm4chee.arc.store.impl.StoreServiceImpl.store(StoreServiceImpl.java:180)
	at org.dcm4chee.arc.store.impl.StoreServiceImpl$Proxy$_$$_WeldClientProxy.store(Unknown Source)
	at org.dcm4chee.arc.store.scp.CStoreSCP.store(CStoreSCP.java:36)
	at org.dcm4che3.net.service.BasicCStoreSCP.onDimseRQ(BasicCStoreSCP.java:72)
	at sun.reflect.GeneratedMethodAccessor71.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.weld.bean.proxy.AbstractBeanInstance.invoke(AbstractBeanInstance.java:38)
	at org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke(ProxyMethodHandler.java:106)
	at org.dcm4che3.net.service.DicomService$1676675649$Proxy$_$$_WeldClientProxy.onDimseRQ(Unknown Source)
	at org.dcm4che3.net.service.DicomServiceRegistry.onDimseRQ(DicomServiceRegistry.java:86)
	at org.dcm4che3.net.ApplicationEntity.onDimseRQ(ApplicationEntity.java:459)
	at org.dcm4che3.net.Association.onDimseRQ(Association.java:696)
	at org.dcm4che3.net.PDUDecoder.decodeDIMSE(PDUDecoder.java:459)
	at org.dcm4che3.net.Association.handlePDataTF(Association.java:679)
	at org.dcm4che3.net.State$4.onPDataTF(State.java:103)
	at org.dcm4che3.net.Association.onPDataTF(Association.java:675)
	at org.dcm4che3.net.PDUDecoder.nextPDU(PDUDecoder.java:177)
	at org.dcm4che3.net.Association$2.run(Association.java:518)
	at org.jboss.as.ee.concurrent.ControlPointUtils$ControlledRunnable.run(ControlPointUtils.java:105)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.glassfish.enterprise.concurrent.internal.ManagedFutureTask.run(ManagedFutureTask.java:141)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at org.glassfish.enterprise.concurrent.ManagedThreadFactoryImpl$ManagedThread.run(ManagedThreadFactoryImpl.java:250)
	at org.jboss.as.ee.concurrent.service.ElytronManagedThreadFactory$ElytronManagedThread.run(ElytronManagedThreadFactory.java:78)

2018-08-23 07:25:07,509 INFO  [org.dcm4che3.net.Association] (EE-ManagedExecutorService-default-Thread-20) DCM4CHEE<-STORESCU(18): processing 1:C-STORE-RQ[pcid=5, prior=0
  cuid=1.2.840.10008.5.1.4.1.1.1 - Computed Radiography Image Storage
  iuid=1.3.51.5156.1199.20160415.1181639.1 - ?
  tsuid=1.2.840.10008.1.2 - Implicit VR Little Endian failed. Caused by:	: org.dcm4che3.net.service.DicomServiceException: java.io.IOException: Storage[id=fs1, uri=file:///storage/pacs1/] not accessable
	at org.dcm4chee.arc.store.impl.StoreServiceImpl.store(StoreServiceImpl.java:187)
	at org.dcm4chee.arc.store.impl.StoreServiceImpl$Proxy$_$$_WeldClientProxy.store(Unknown Source)
	at org.dcm4chee.arc.store.scp.CStoreSCP.store(CStoreSCP.java:36)
	at org.dcm4che3.net.service.BasicCStoreSCP.onDimseRQ(BasicCStoreSCP.java:72)
	at sun.reflect.GeneratedMethodAccessor71.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.weld.bean.proxy.AbstractBeanInstance.invoke(AbstractBeanInstance.java:38)
	at org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke(ProxyMethodHandler.java:106)
	at org.dcm4che3.net.service.DicomService$1676675649$Proxy$_$$_WeldClientProxy.onDimseRQ(Unknown Source)
	at org.dcm4che3.net.service.DicomServiceRegistry.onDimseRQ(DicomServiceRegistry.java:86)
	at org.dcm4che3.net.ApplicationEntity.onDimseRQ(ApplicationEntity.java:459)
	at org.dcm4che3.net.Association.onDimseRQ(Association.java:696)
	at org.dcm4che3.net.PDUDecoder.decodeDIMSE(PDUDecoder.java:459)
	at org.dcm4che3.net.Association.handlePDataTF(Association.java:679)
	at org.dcm4che3.net.State$4.onPDataTF(State.java:103)
	at org.dcm4che3.net.Association.onPDataTF(Association.java:675)
	at org.dcm4che3.net.PDUDecoder.nextPDU(PDUDecoder.java:177)
	at org.dcm4che3.net.Association$2.run(Association.java:518)
	at org.jboss.as.ee.concurrent.ControlPointUtils$ControlledRunnable.run(ControlPointUtils.java:105)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.glassfish.enterprise.concurrent.internal.ManagedFutureTask.run(ManagedFutureTask.java:141)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at org.glassfish.enterprise.concurrent.ManagedThreadFactoryImpl$ManagedThread.run(ManagedThreadFactoryImpl.java:250)
	at org.jboss.as.ee.concurrent.service.ElytronManagedThreadFactory$ElytronManagedThread.run(ElytronManagedThreadFactory.java:78)
Caused by: java.io.IOException: Storage[id=fs1, uri=file:///storage/pacs1/] not accessable
	at org.dcm4chee.arc.storage.AbstractStorage.checkAccessable(AbstractStorage.java:161)
	at org.dcm4chee.arc.storage.AbstractStorage.openOutputStream(AbstractStorage.java:110)
	at org.dcm4chee.arc.store.impl.StoreServiceImpl.openOutputStream(StoreServiceImpl.java:553)
	at org.dcm4chee.arc.store.impl.StoreServiceImpl.access$200(StoreServiceImpl.java:100)
	at org.dcm4chee.arc.store.impl.StoreServiceImpl$TranscoderHandler.newOutputStream(StoreServiceImpl.java:536)
	at org.dcm4che3.imageio.codec.Transcoder.initDicomOutputStream(Transcoder.java:701)
	at org.dcm4che3.imageio.codec.Transcoder.access$100(Transcoder.java:70)
	at org.dcm4che3.imageio.codec.Transcoder$1.readValue(Transcoder.java:352)
	at org.dcm4che3.io.DicomInputStream.readAttributes(DicomInputStream.java:533)
	at org.dcm4che3.imageio.codec.Transcoder.transcode(Transcoder.java:337)
	at org.dcm4chee.arc.store.impl.StoreServiceImpl.store(StoreServiceImpl.java:180)
	... 27 more

2018-08-23 07:25:07,510 INFO  [org.dcm4che3.net.Dimse] (EE-ManagedExecutorService-default-Thread-20) DCM4CHEE<-STORESCU(18) << 1:C-STORE-RSP[pcid=5, status=110H, errorComment=java.io.IOException: Storage[id=fs1, uri=file:///storage/pacs1/]
  tsuid=1.2.840.10008.1.2 - Implicit VR Little Endian
2018-08-23 07:25:07,517 INFO  [org.dcm4che3.net.Association] (EE-ManagedExecutorService-default-Thread-20) DCM4CHEE<-STORESCU(18) >> A-RELEASE-RQ
2018-08-23 07:25:07,517 INFO  [org.dcm4che3.net.Association] (EE-ManagedExecutorService-default-Thread-20) DCM4CHEE<-STORESCU(18) << A-RELEASE-RP
2018-08-23 07:25:07,568 INFO  [org.dcm4che3.net.Association] (EE-ManagedScheduledExecutorService-default-Thread-6) DCM4CHEE<-STORESCU(18): close Socket[addr=172.18.0.1/172.18.0.1,port=53776,localport=11112]
```

I have verified that I have access to the "/storage/pacs1" filesystem from the docker instance.

Could any one help please ?

**Comment by gunterze** [comment]
Is there a file `NO_MOUNT` at the mapped out storage directory `/storage/pacs1` ? Please use the [dcm4che forum](https://groups.google.com/forum/#!forum/dcm4che), not the issuer tracker for asking for help!
