### ISSUE TITLE
DicomServiceException: Missing SeriesInstanceUID (0020,000E) (dcm4chee-arc 5.14)

### ISSUE THREAD

**Issue by rafaeldl** [dcm4che/dcm4chee-arc-light#1581]
Hi,

I'm using Horos to query dcm4chee 5, but when I try to make a retrieve to get a dicom. The server has the following error:

```
2018-09-11 19:58:44,833 INFO  [org.dcm4che3.net.Connection] (EE-ManagedExecutorService-default-Thread-2) Accept connection Socket[addr=/10.255.0.2,port=26803,localport=11112]
2018-09-11 19:58:44,836 INFO  [org.dcm4che3.net.Association] (EE-ManagedExecutorService-default-Thread-13) DCM4CHEE<-MacBook-Pro-de-R(9) >> A-ASSOCIATE-RQ
2018-09-11 19:58:44,836 INFO  [org.dcm4che3.net.Association] (EE-ManagedExecutorService-default-Thread-13) DCM4CHEE<-MacBook-Pro-de-R(9) << A-ASSOCIATE-AC
2018-09-11 19:58:45,020 INFO  [org.dcm4che3.net.Dimse] (EE-ManagedExecutorService-default-Thread-13) DCM4CHEE<-MacBook-Pro-de-R(9) >> 1:C-FIND-RQ[pcid=1, prior=2
  cuid=1.2.840.10008.5.1.4.1.2.2.1 - Study Root Query/Retrieve Information Model - FIND
  tsuid=1.2.840.10008.1.2 - Implicit VR Little Endian
2018-09-11 19:58:45,021 INFO  [org.dcm4chee.arc.query.scp.CommonCFindSCP] (EE-ManagedExecutorService-default-Thread-13) DCM4CHEE<-MacBook-Pro-de-R(9): Process C-FIND RQ:
(0008,0005) CS [ISO_IR 100] SpecificCharacterSet
(0008,0020) DA [20180811-] StudyDate
(0008,0030) TM [] StudyTime
(0008,0050) SH [] AccessionNumber
(0008,0052) CS [STUDY] QueryRetrieveLevel
(0008,0061) CS [] ModalitiesInStudy
(0008,0080) LO [] InstitutionName
(0008,0090) PN [] ReferringPhysicianName
(0008,1030) LO [] StudyDescription
(0008,1050) PN [] PerformingPhysicianName
(0010,0010) PN [] PatientName
(0010,0020) LO [] PatientID
(0010,0030) DA [] PatientBirthDate
(0020,000D) UI [] StudyInstanceUID
(0020,0010) SH [] StudyID
(0020,1208) IS [] NumberOfStudyRelatedInstances
(0032,4000) LT [] StudyComments
(4008,0212) CS [] InterpretationStatusID

2018-09-11 19:58:45,040 INFO  [org.dcm4che3.net.Dimse] (EE-ManagedExecutorService-default-Thread-14) DCM4CHEE<-MacBook-Pro-de-R(9) << 1:C-FIND-RSP[pcid=1, status=ff00H
  cuid=1.2.840.10008.5.1.4.1.2.2.1 - Study Root Query/Retrieve Information Model - FIND
  tsuid=1.2.840.10008.1.2 - Implicit VR Little Endian
2018-09-11 19:58:45,041 INFO  [org.dcm4che3.net.Dimse] (EE-ManagedExecutorService-default-Thread-14) DCM4CHEE<-MacBook-Pro-de-R(9) << 1:C-FIND-RSP[pcid=1, status=0H
  cuid=1.2.840.10008.5.1.4.1.2.2.1 - Study Root Query/Retrieve Information Model - FIND
  tsuid=1.2.840.10008.1.2 - Implicit VR Little Endian
2018-09-11 19:58:45,222 INFO  [org.dcm4che3.net.Association] (EE-ManagedExecutorService-default-Thread-13) DCM4CHEE<-MacBook-Pro-de-R(9) >> A-RELEASE-RQ
2018-09-11 19:58:45,223 INFO  [org.dcm4che3.net.Association] (EE-ManagedExecutorService-default-Thread-13) DCM4CHEE<-MacBook-Pro-de-R(9) << A-RELEASE-RP
2018-09-11 19:58:45,273 INFO  [org.dcm4che3.net.Association] (EE-ManagedScheduledExecutorService-default-Thread-1) DCM4CHEE<-MacBook-Pro-de-R(9): close Socket[addr=10.255.0.2/10.255.0.2,port=26803,localport=11112]
2018-09-11 19:58:47,564 INFO  [org.dcm4che3.net.Connection] (EE-ManagedExecutorService-default-Thread-2) Accept connection Socket[addr=/10.255.0.2,port=50352,localport=11112]
2018-09-11 19:58:47,565 INFO  [org.dcm4che3.net.Association] (EE-ManagedExecutorService-default-Thread-13) DCM4CHEE<-MacBook-Pro-de-R(10) >> A-ASSOCIATE-RQ
2018-09-11 19:58:47,565 INFO  [org.dcm4che3.net.Association] (EE-ManagedExecutorService-default-Thread-13) DCM4CHEE<-MacBook-Pro-de-R(10) << A-ASSOCIATE-AC
2018-09-11 19:58:47,766 INFO  [org.dcm4che3.net.Dimse] (EE-ManagedExecutorService-default-Thread-13) DCM4CHEE<-MacBook-Pro-de-R(10) >> 1:C-FIND-RQ[pcid=1, prior=2
  cuid=1.2.840.10008.5.1.4.1.2.2.1 - Study Root Query/Retrieve Information Model - FIND
  tsuid=1.2.840.10008.1.2 - Implicit VR Little Endian
2018-09-11 19:58:47,767 INFO  [org.dcm4chee.arc.query.scp.CommonCFindSCP] (EE-ManagedExecutorService-default-Thread-13) DCM4CHEE<-MacBook-Pro-de-R(10): Process C-FIND RQ:
(0008,0005) CS [ISO_IR 100] SpecificCharacterSet
(0008,0018) UI [] SOPInstanceUID
(0008,0052) CS [IMAGE] QueryRetrieveLevel
(0020,000D) UI [1.2.826.0.1.3680043.9.3782.1.1.15356837209521253589] StudyInst
(0020,000E) UI [] SeriesInstanceUID

2018-09-11 19:58:47,767 INFO  [org.dcm4che3.net.Association] (EE-ManagedExecutorService-default-Thread-13) DCM4CHEE<-MacBook-Pro-de-R(10): processing 1:C-FIND-RQ[pcid=1, prior=2
  cuid=1.2.840.10008.5.1.4.1.2.2.1 - Study Root Query/Retrieve Information Model - FIND
  tsuid=1.2.840.10008.1.2 - Implicit VR Little Endian failed. Caused by:	: org.dcm4che3.net.service.DicomServiceException: Missing SeriesInstanceUID (0020,000E)
	at org.dcm4che3.net.service.QueryRetrieveLevel2.identifierDoesNotMatchSOPClass(QueryRetrieveLevel2.java:147)
	at org.dcm4che3.net.service.QueryRetrieveLevel2.missingAttribute(QueryRetrieveLevel2.java:136)
	at org.dcm4che3.net.service.QueryRetrieveLevel2.checkUniqueKey(QueryRetrieveLevel2.java:130)
	at org.dcm4che3.net.service.QueryRetrieveLevel2.validateIdentifier(QueryRetrieveLevel2.java:119)
	at org.dcm4che3.net.service.QueryRetrieveLevel2.validateQueryIdentifier(QueryRetrieveLevel2.java:83)
	at org.dcm4chee.arc.query.scp.CommonCFindSCP.calculateMatches(CommonCFindSCP.java:91)
	at org.dcm4che3.net.service.BasicCFindSCP.onDimseRQ(BasicCFindSCP.java:65)
	at org.dcm4che3.net.service.AbstractDicomService.onDimseRQ(AbstractDicomService.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.weld.bean.proxy.AbstractBeanInstance.invoke(AbstractBeanInstance.java:38)
	at org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke(ProxyMethodHandler.java:106)
	at org.dcm4che3.net.service.DicomService$1478140080$Proxy$_$$_WeldClientProxy.onDimseRQ(Unknown Source)
	at org.dcm4che3.net.service.DicomServiceRegistry.onDimseRQ(DicomServiceRegistry.java:86)
	at org.dcm4che3.net.ApplicationEntity.onDimseRQ(ApplicationEntity.java:459)
	at org.dcm4che3.net.Association.onDimseRQ(Association.java:696)
	at org.dcm4che3.net.PDUDecoder.decodeDIMSE(PDUDecoder.java:459)
	at org.dcm4che3.net.Association.handlePDataTF(Association.java:679)
	at org.dcm4che3.net.State$4.onPDataTF(State.java:103)
	at org.dcm4che3.net.Association.onPDataTF(Association.java:675)
	at org.dcm4che3.net.PDUDecoder.nextPDU(PDUDecoder.java:177)
	at org.dcm4che3.net.Association$2.run(Association.java:518)
	at org.jboss.as.ee.concurrent.ControlPointUtils$ControlledRunnable.run(ControlPointUtils.java:105)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.glassfish.enterprise.concurrent.internal.ManagedFutureTask.run(ManagedFutureTask.java:141)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at org.glassfish.enterprise.concurrent.ManagedThreadFactoryImpl$ManagedThread.run(ManagedThreadFactoryImpl.java:250)
	at org.jboss.as.ee.concurrent.service.ElytronManagedThreadFactory$ElytronManagedThread.run(ElytronManagedThreadFactory.java:78)

2018-09-11 19:58:47,767 INFO  [org.dcm4che3.net.Dimse] (EE-ManagedExecutorService-default-Thread-13) DCM4CHEE<-MacBook-Pro-de-R(10) << 1:C-FIND-RSP[pcid=1, status=a900H, errorComment=Missing SeriesInstanceUID (0020,000E)
  tsuid=1.2.840.10008.1.2 - Implicit VR Little Endian
2018-09-11 19:58:47,972 INFO  [org.dcm4che3.net.Association] (EE-ManagedExecutorService-default-Thread-13) DCM4CHEE<-MacBook-Pro-de-R(10) >> A-RELEASE-RQ
2018-09-11 19:58:47,972 INFO  [org.dcm4che3.net.Association] (EE-ManagedExecutorService-default-Thread-13) DCM4CHEE<-MacBook-Pro-de-R(10) << A-RELEASE-RP
2018-09-11 19:58:48,023 INFO  [org.dcm4che3.net.Association] (EE-ManagedScheduledExecutorService-default-Thread-2) DCM4CHEE<-MacBook-Pro-de-R(10): close Socket[addr=/10.255.0.2,port=50352,localport=11112]
2

```

can anybody help me?

**Comment by gunterze** [comment]
Queries on IMAGE level requires the Study **and** Series Instance UID in the request, if relational query was not negotiated. s. [DICOM Part 4. C.4.1.2.1](http://dicom.nema.org/medical/dicom/current/output/html/part04.html#sect_C.4.1.2.1). Please use the [google forum](https://groups.google.com/forum/#!forum/dcm4che), not the issue tracker for such question.
