### ISSUE TITLE
Weasis viewer integration

### ISSUE THREAD

**Issue by karthickDhanapal** [dcm4che/dcm4chee-arc-light#1840]
**Describe the bug**
Im getting the below exception while adding the wpacs connector in dcm4che ui

Invoke Image Display Patient URL: ../../weasis-pacs-connector/IHEInvokeImageDisplay?requestType=PATIENT&patientID={}
Invoke Image Display Study URL: ../../weasis-pacs-connector/IHEInvokeImageDisplay?requestType=STUDY&studyUID={}

EXCEPTION:
org.dcm4che3.conf.api.ConfigurationException: javax.naming.directory.SchemaViolationException: [LDAP: error code 65 - Entry dicomDeviceName=dcm4chee-arc,cn=Devices,cn=DICOM Configuration,dc=dcm4che,dc=org cannot be modified because the resulting entry would have violated the server schema: Entry dicomDeviceName=dcm4chee-arc,cn=Devices,cn=DICOM Configuration,dc=dcm4che,dc=org violates the Directory Server schema configuration because it contains an unknown objectclass dcmarchivedevice]; remaining name 'dicomDeviceName=dcm4chee-arc,cn=Devices,cn=DICOM Configuration,dc=dcm4che,dc=org'
 at org.dcm4che3.conf.ldap.LdapDicomConfiguration.merge(LdapDicomConfiguration.java:687)
 at org.dcm4che3.conf.ldap.LdapDicomConfiguration.merge(LdapDicomConfiguration.java:654)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:483)
 at org.jboss.weld.bean.proxy.AbstractBeanInstance.invoke(AbstractBeanInstance.java:38)
 at org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke(ProxyMethodHandler.java:106)
 at org.dcm4che3.conf.api.AutoCloseable$Closeable$DicomConfiguration$892238696$Proxy$_$$_WeldClientProxy.merge(Unknown Source)
 at org.dcm4chee.arc.conf.rs.ConfigurationRS.updateDevice(ConfigurationRS.java:317)
 at org.dcm4chee.arc.conf.rs.ConfigurationRS$Proxy$_$$_WeldClientProxy.updateDevice(Unknown Source)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:483)
 at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:140)
 at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:511)
 at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:402)

**Comment by karthickDhanapal** [comment]
@gunterze  Do you have any idea on this part

**Comment by vrindanayak** [comment]
objectclass _**dcmarchivedevice**_ is nowhere present in any of the ldif files, it should be rather _**dcmArchiveDevice**_. 

Issue is not reproducible. Please use [dcm4che User Forum](https://groups.google.com/forum/#!forum/dcm4che) for questions.

**Comment by karthickDhanapal** [comment]
@gunterze  Thank you
