### ISSUE TITLE
Fail to load keycloak server configuration with password

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4chee-arc-light#1918]
Fail to load [keycloak server](https://dcm4chee-arc-cs.readthedocs.io/en/latest/networking/config/keycloakServer.html) configuration with password:
```
2019-04-10 11:43:15,138 ERROR [org.jboss.as.ejb3.invocation] (default task-3) WFLYEJB0034: EJB Invocation failed on component ArchiveServiceImpl for method public abstract void org.dcm4chee.arc.ArchiveService.re
load(javax.servlet.http.HttpServletRequest) throws java.lang.Exception: javax.ejb.EJBException: java.lang.ClassCastException: class [B cannot be cast to class java.lang.String ([B and java.lang.String are in mod
ule java.base of loader 'bootstrap')
:
Caused by: java.lang.ClassCastException: class [B cannot be cast to class java.lang.String ([B and java.lang.String are in module java.base of loader 'bootstrap')
        at org.dcm4che.conf.ldap@5.16.2//org.dcm4che3.conf.ldap.LdapUtils.stringValue(LdapUtils.java:428)
        at deployment.dcm4chee-arc-ear-5.16.2-psql.ear//org.dcm4chee.arc.conf.ldap.LdapArchiveConfiguration.loadKeycloakServers(LdapArchiveConfiguration.java:3002)
        at deployment.dcm4chee-arc-ear-5.16.2-psql.ear//org.dcm4chee.arc.conf.ldap.LdapArchiveConfiguration.loadChilds(LdapArchiveConfiguration.java:965)
        at org.dcm4che.conf.ldap@5.16.2//org.dcm4che3.conf.ldap.LdapDicomConfiguration.loadChilds(LdapDicomConfiguration.java:1238)
        at org.dcm4che.conf.ldap@5.16.2//org.dcm4che3.conf.ldap.LdapDicomConfiguration.loadDevice(LdapDicomConfiguration.java:1208)
        at org.dcm4che.conf.ldap@5.16.2//org.dcm4che3.conf.ldap.LdapDicomConfiguration.findDevice(LdapDicomConfiguration.java:340)
:
```
Related #1364

**Comment by vrindanayak** [comment]
https://github.com/dcm4che/dcm4che/commit/5411678597b37671ed019e7f8280acbb8689f3e9
