### ISSUE TITLE
failed to upload file with stow-rs

### ISSUE THREAD

**Issue by OrNot** [dcm4che/dcm4chee-arc-light#194]
OS:   ubuntu 16.04 LTS 
Version : 5.4.1
Command line: curl -H "Content-Type: multipart/related; type=\"application/dicom\"" -F "content=@test.dcm; type=application/dicom" -X POST http://localhost:8080/dcm4chee-arc/aets/DCM4CHEE/rs/studies

Test file can be downloaded from here:   http://pan.baidu.com/s/1jIhgKfG

18:41:08,988 WARN  [org.dcm4che3.io.DicomInputStream] (default task-2) IOException during read of (000F,0016) #262158 @ 131218: java.io.EOFException
	at org.dcm4che3.util.StreamUtils.readFully(StreamUtils.java:74)
	at org.dcm4che3.io.DicomInputStream.readFully(DicomInputStream.java:400)
	at org.dcm4che3.io.DicomInputStream.readValue(DicomInputStream.java:741)
	at org.dcm4che3.io.DicomInputStream.readValue(DicomInputStream.java:574)
	at org.dcm4che3.imageio.codec.Transcoder$1.readValue(Transcoder.java:314)
	at org.dcm4che3.io.DicomInputStream.readAttributes(DicomInputStream.java:545)
	at org.dcm4che3.imageio.codec.Transcoder.transcode(Transcoder.java:295)
	at org.dcm4chee.arc.store.org.dcm4chee.archive.store.impl.StoreServiceImpl.store(StoreServiceImpl.java:94)
	at org.dcm4chee.arc.store.org.dcm4chee.archive.store.impl.StoreServiceImpl$Proxy$_$$_WeldClientProxy.store(Unknown Source)
	at org.dcm4chee.arc.stow.StowRS.storeDicomObject(StowRS.java:366)
	at org.dcm4chee.arc.stow.StowRS.access$400(StowRS.java:91)
	at org.dcm4chee.arc.stow.StowRS$Input$1.readBodyPart(StowRS.java:330)
	at org.dcm4chee.arc.stow.StowRS$2.bodyPart(StowRS.java:268)
	at org.dcm4che3.mime.MultipartParser.parse(MultipartParser.java:76)
	at org.dcm4chee.arc.stow.StowRS.store(StowRS.java:259)
	at org.dcm4chee.arc.stow.StowRS.storeInstancesXML(StowRS.java:131)
	at org.dcm4chee.arc.stow.StowRS$Proxy$_$$_WeldClientProxy.storeInstancesXML(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:139)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:295)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:249)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:236)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:395)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:202)
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:221)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:85)
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131)
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
	at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:284)
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:263)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:174)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:202)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:793)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

18:41:08,990 WARN  [org.dcm4chee.arc.store.org.dcm4chee.archive.store.impl.StoreServiceImpl] (default task-2) null@127.0.0.1->DCM4CHEE: Failed to encode received object:: java.io.EOFException
	at org.dcm4che3.util.StreamUtils.readFully(StreamUtils.java:74)
	at org.dcm4che3.io.DicomInputStream.readFully(DicomInputStream.java:400)
	at org.dcm4che3.io.DicomInputStream.readValue(DicomInputStream.java:741)
	at org.dcm4che3.io.DicomInputStream.readValue(DicomInputStream.java:574)
	at org.dcm4che3.imageio.codec.Transcoder$1.readValue(Transcoder.java:314)
	at org.dcm4che3.io.DicomInputStream.readAttributes(DicomInputStream.java:545)
	at org.dcm4che3.imageio.codec.Transcoder.transcode(Transcoder.java:295)
	at org.dcm4chee.arc.store.org.dcm4chee.archive.store.impl.StoreServiceImpl.store(StoreServiceImpl.java:94)
	at org.dcm4chee.arc.store.org.dcm4chee.archive.store.impl.StoreServiceImpl$Proxy$_$$_WeldClientProxy.store(Unknown Source)
	at org.dcm4chee.arc.stow.StowRS.storeDicomObject(StowRS.java:366)
	at org.dcm4chee.arc.stow.StowRS.access$400(StowRS.java:91)
	at org.dcm4chee.arc.stow.StowRS$Input$1.readBodyPart(StowRS.java:330)
	at org.dcm4chee.arc.stow.StowRS$2.bodyPart(StowRS.java:268)
	at org.dcm4che3.mime.MultipartParser.parse(MultipartParser.java:76)
	at org.dcm4chee.arc.stow.StowRS.store(StowRS.java:259)
	at org.dcm4chee.arc.stow.StowRS.storeInstancesXML(StowRS.java:131)
	at org.dcm4chee.arc.stow.StowRS$Proxy$_$$_WeldClientProxy.storeInstancesXML(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:139)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:295)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:249)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:236)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:395)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:202)
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:221)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:85)
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131)
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
	at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:284)
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:263)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:174)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:202)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:793)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

18:41:09,020 INFO  [org.dcm4chee.arc.stow.StowRS] (default task-2) null@127.0.0.1->DCM4CHEE: Failed to store ?: org.dcm4che3.net.service.DicomServiceException: java.io.EOFException
	at org.dcm4chee.arc.store.org.dcm4chee.archive.store.impl.StoreServiceImpl.store(StoreServiceImpl.java:97)
	at org.dcm4chee.arc.store.org.dcm4chee.archive.store.impl.StoreServiceImpl$Proxy$_$$_WeldClientProxy.store(Unknown Source)
	at org.dcm4chee.arc.stow.StowRS.storeDicomObject(StowRS.java:366)
	at org.dcm4chee.arc.stow.StowRS.access$400(StowRS.java:91)
	at org.dcm4chee.arc.stow.StowRS$Input$1.readBodyPart(StowRS.java:330)
	at org.dcm4chee.arc.stow.StowRS$2.bodyPart(StowRS.java:268)
	at org.dcm4che3.mime.MultipartParser.parse(MultipartParser.java:76)
	at org.dcm4chee.arc.stow.StowRS.store(StowRS.java:259)
	at org.dcm4chee.arc.stow.StowRS.storeInstancesXML(StowRS.java:131)
	at org.dcm4chee.arc.stow.StowRS$Proxy$_$$_WeldClientProxy.storeInstancesXML(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:139)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:295)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:249)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:236)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:395)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:202)
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:221)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:85)
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131)
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
	at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:284)
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:263)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:174)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:202)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:793)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.EOFException
	at org.dcm4che3.util.StreamUtils.readFully(StreamUtils.java:74)
	at org.dcm4che3.io.DicomInputStream.readFully(DicomInputStream.java:400)
	at org.dcm4che3.io.DicomInputStream.readValue(DicomInputStream.java:741)
	at org.dcm4che3.io.DicomInputStream.readValue(DicomInputStream.java:574)
	at org.dcm4che3.imageio.codec.Transcoder$1.readValue(Transcoder.java:314)
	at org.dcm4che3.io.DicomInputStream.readAttributes(DicomInputStream.java:545)
	at org.dcm4che3.imageio.codec.Transcoder.transcode(Transcoder.java:295)
	at org.dcm4chee.arc.store.org.dcm4chee.archive.store.impl.StoreServiceImpl.store(StoreServiceImpl.java:94)
	... 50 more

**Comment by gunterze** [comment]
You have to encapsulate the image in a multipart/related MIME message and specify the corresponding boundary in the HTTP header! S. [RFC2387](https://tools.ietf.org/html/rfc2387)

**Comment by OrNot** [comment]
Suppose I use curl command line as in this case, could you please show me an example?  Thanks a lot

Sent from Yahoo Mail on Android 
 
  On Wed, Jun 22, 2016 at 14:56, Gunter Zeilinger<notifications@github.com> wrote:   
You have to encapsulate the image in a multipart/related MIME message and specify the corresponding boundary in the HTTP header! S. RFC2387

**Comment by gunterze** [comment]
```
echo -ne "--myboundary\r\nContent-Type: application/dicom\r\n\r\n" > mime-multi-part.head
echo -ne "\r\n--myboundary--" > mime-multi-part.tail
cat mime-multi-part.head image.dcm mime-multi-part.tail > image.mime-multi-part
curl -v -H "Content-type: multipart/related; type=application/dicom; boundary=myboundary" http://localhost:8080/dcm4chee-arc/aets/DCM4CHEE/rs/studies --data-binary @image.mime-multi-part
```

**Comment by OrNot** [comment]
I followed your post strictly but failed again.

**Comment by gunterze** [comment]
I cannot reproduce the problem:
```
$ cat mime.head /tmp/test.dcm mime.tail | curl -H "Content-Type: multipart/related; type=application/dicom; boundary=myboundary" \
>      http://localhost:8080/dcm4chee-arc/aets/DCM4CHEE/rs/studies --data-binary @-
<?xml version="1.0" encoding="UTF-8"?><NativeDicomModel xml:space="preserve"><DicomAttribute keyword="RetrieveURL" tag="00081190" vr="UR"><Value number="1">http://localhost:8080/dcm4chee-arc/aets/DCM4CHEE/rs/studies/1.2.840.113619.2.5.1762583153.215519.978957063.78</Value></DicomAttribute><DicomAttribute keyword="ReferencedSOPSequence" tag="00081199" vr="SQ"><Item number="1"><DicomAttribute keyword="ReferencedSOPClassUID" tag="00081150" vr="UI"><Value number="1">1.2.840.10008.5.1.4.1.1.4</Value></DicomAttribute><DicomAttribute keyword="ReferencedSOPInstanceUID" tag="00081155" vr="UI"><Value number="1">1.2.840.113619.2.5.1762583153.215519.978957063.80</Value></DicomAttribute><DicomAttribute keyword="RetrieveURL" tag="00081190" vr="UR"><Value number="1">http://localhost:8080/dcm4chee-arc/aets/DCM4CHEE/rs/studies/1.2.840.113619.2.5.1762583153.215519.978957063.78/series/1.2.840.113619.2.5.1762583153.215519.978957063.79/instances/1.2.840.113619.2.5.1762583153.215519.978957063.80</Value></DicomAttribute></Item></DicomAttribute></NativeDicomModel>
```
```
17:30:34,043 INFO  [org.dcm4chee.arc.stow.StowRS] (default task-57) Process POST /dcm4chee-arc/aets/DCM4CHEE/rs/studies from null@127.0.0.1
17:30:34,049 INFO  [org.dcm4chee.arc.stow.StowRS] (default task-57) storeInstances: Extract Part #1{content-type=[application/dicom]}
17:30:34,127 INFO  [org.dcm4chee.arc.store.org.dcm4chee.archive.store.impl.StoreServiceImpl] (default task-57) null@127.0.0.1->DCM4CHEE: Create Study[pk=452, uid=1.2.840.113619.2.5.1762583153.215519.978957063.78, id=5801]
17:30:34,128 INFO  [org.dcm4chee.arc.store.org.dcm4chee.archive.store.impl.StoreServiceImpl] (default task-57) null@127.0.0.1->DCM4CHEE: Create Series[pk=1379, uid=1.2.840.113619.2.5.1762583153.215519.978957063.79, no=1, mod=MR]
17:30:34,130 INFO  [org.dcm4chee.arc.store.org.dcm4chee.archive.store.impl.StoreServiceImpl] (default task-57) null@127.0.0.1->DCM4CHEE: Create Instance[pk=45015, uid=1.2.840.113619.2.5.1762583153.215519.978957063.80, class=1.2.840.10008.5.1.4.1.1.4, no=1]
```
Please post further questions to https://groups.google.com/forum/#!forum/dcm4che
