### ISSUE TITLE
changing the AET crashes CalculateStudySize exporter

### ISSUE THREAD

**Issue by mbakhoff** [dcm4che/dcm4chee-arc-light#2122]
I followed the wiki guide and changed the AET from "DCM4CHEE" to "MY_AE"
https://github.com/dcm4che/dcm4chee-arc-light/wiki/AE-Title(s)-of-the-Archive

Now I'm seeing some errors in the log:
```
11:27:41,840 WARN  [org.dcm4chee.arc.export.mgt.impl.ExportManagerEJB] (EE-ManagedScheduledExecutorService-default-Thread-1) Failed to query Export Task Info for ExportTask[pk=7076, exporterID=CalculateStudySize, studyUID=1.2.3.4, seriesUID=*, objectUID=*] - : java.lang.NullPointerException
    at deployment.dcm4chee-arc-ear-5.16.2-psql.ear.dcm4chee-arc-query-5.16.2.jar//org.dcm4chee.arc.query.impl.QueryServiceImpl.queryExportTaskInfo(QueryServiceImpl.java:267)
    at deployment.dcm4chee-arc-ear-5.16.2-psql.ear.dcm4chee-arc-query-5.16.2.jar//org.dcm4chee.arc.query.impl.QueryServiceImpl$Proxy$_$$_WeldClientProxy.queryExportTaskInfo(Unknown Source)
    at deployment.dcm4chee-arc-ear-5.16.2-psql.ear.dcm4chee-arc-export-mgt-5.16.2.jar//org.dcm4chee.arc.export.mgt.impl.ExportManagerEJB.scheduleExportTask(ExportManagerEJB.java:252)
    at deployment.dcm4chee-arc-ear-5.16.2-psql.ear.dcm4chee-arc-export-mgt-5.16.2.jar//org.dcm4chee.arc.export.mgt.impl.ExportManagerEJB.scheduleExportTasks(ExportManagerEJB.java:195)
```

The relevant snippet from scheduleExportTask:
```
Attributes attrs = queryService.queryExportTaskInfo(
        exportTask.getStudyInstanceUID(),
        exportTask.getSeriesInstanceUID(),
        exportTask.getSopInstanceUID(),
        device.getApplicationEntity(exporter.getAETitle(), true)); // getApplicationEntity returns null
```

If the exporter is not configured with a specific AET (it isn't by default), then "DCM4CHEE" is used as the default AET without checking if it even exists. It might be useful to improve the warning logged in scheduleExportTask and/or update the wiki with instructions on how to ensure the configuration stays valid.

The issue can be worked around by adding DCM4CHEE as dcmOtherAETitle to the freshly renamed MY_AE with ldapmodify or via the GUI.
```
dn: dicomAETitle=MY_AE,dicomDeviceName=dcm4chee-arc,cn=Devices,cn=DICOM Configuration,dc=dcm4che,dc=org
changetype: modify
add: dcmOtherAETitle
dcmOtherAETitle: DCM4CHEE
```

**Comment by gunterze** [comment]
Duplicates #1673
