### ISSUE TITLE
Provide ID Service to create sequential IDs according a configurable pattern

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4chee-arc-light#215]
Required for #168.
```java
public class ArchiveDeviceExtension extends DeviceExtension {
:
    public IDGenerator getIDGenerator(IDGenerator.Name name) {..}

    public void addIDGenerator(IDGenerator generator) {..}

    public void removeIDGenerator(IDGenerator generator) {.. }
:
```
```java
public class IDGenerator {
    public enum Name {
        PatientID,
        AccessionNumber,
        RequestedProcedureID,
        ScheduledProcedureStepID
    }
    private Name name;
    private String format;
    private int initialValue = 1;
:
}
```

**Comment by gunterze** [comment]
```
Running org.dcm4chee.arc.conf.ArchiveDeviceJsonConfigurationTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.256 sec <<< FAILURE! - in org.dcm4chee.arc.conf.ArchiveDeviceJsonConfigurationTest
testJsonPersist(org.dcm4chee.arc.conf.ArchiveDeviceJsonConfigurationTest)  Time elapsed: 0.255 sec  <<< ERROR!
java.lang.UnsupportedOperationException: null
	at java.util.AbstractCollection.add(AbstractCollection.java:262)
	at org.dcm4chee.arc.conf.json.JsonArchiveConfiguration.loadIDGenerators(JsonArchiveConfiguration.java:1014)
	at org.dcm4chee.arc.conf.json.JsonArchiveConfiguration.loadFrom(JsonArchiveConfiguration.java:587)
	at org.dcm4chee.arc.conf.json.JsonArchiveConfiguration.loadDeviceExtension(JsonArchiveConfiguration.java:382)
	at org.dcm4che3.conf.json.JsonConfiguration.loadDeviceExtension(JsonConfiguration.java:308)
	at org.dcm4che3.conf.json.JsonConfiguration.loadDeviceFrom(JsonConfiguration.java:294)
	at org.dcm4chee.arc.conf.ArchiveDeviceJsonConfigurationTest.testJsonPersist(ArchiveDeviceJsonConfigurationTest.java:93)

Running org.dcm4chee.arc.conf.ArchiveDeviceConfigurationTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.545 sec <<< FAILURE! - in org.dcm4chee.arc.conf.ArchiveDeviceConfigurationTest
testPersist(org.dcm4chee.arc.conf.ArchiveDeviceConfigurationTest)  Time elapsed: 0.545 sec  <<< ERROR!
org.dcm4che3.conf.api.ConfigurationException: javax.naming.directory.InvalidAttributeValueException: Malformed 'dcmIDGeneratorName' attribute value; remaining name 'dcmIDGeneratorName=PatientID,dicomDeviceName=dcm4chee-arc,cn=Devices,cn=DICOM Configuration,dc=dcm4che,dc=org'
	at com.sun.jndi.ldap.LdapClient.encodeAttribute(LdapClient.java:982)
	at com.sun.jndi.ldap.LdapClient.add(LdapClient.java:1030)
	at com.sun.jndi.ldap.LdapCtx.c_createSubcontext(LdapCtx.java:808)
	at com.sun.jndi.toolkit.ctx.ComponentDirContext.p_createSubcontext(ComponentDirContext.java:341)
	at com.sun.jndi.toolkit.ctx.PartialCompositeDirContext.createSubcontext(PartialCompositeDirContext.java:268)
	at com.sun.jndi.toolkit.ctx.PartialCompositeDirContext.createSubcontext(PartialCompositeDirContext.java:256)
	at javax.naming.directory.InitialDirContext.createSubcontext(InitialDirContext.java:197)
	at org.dcm4che3.conf.ldap.ReconnectDirContext.createSubcontextAndClose(ReconnectDirContext.java:82)
	at org.dcm4che3.conf.ldap.LdapDicomConfiguration.createSubcontext(LdapDicomConfiguration.java:586)
	at org.dcm4chee.arc.conf.ldap.LdapArchiveConfiguration.storeIDGenerators(LdapArchiveConfiguration.java:1282)
	at org.dcm4chee.arc.conf.ldap.LdapArchiveConfiguration.storeChilds(LdapArchiveConfiguration.java:334)
	at org.dcm4che3.conf.ldap.LdapDicomConfiguration.storeChilds(LdapDicomConfiguration.java:505)
	at org.dcm4che3.conf.ldap.LdapDicomConfiguration.persist(LdapDicomConfiguration.java:465)
	at org.dcm4chee.arc.conf.ArchiveDeviceConfigurationTest.testPersist(ArchiveDeviceConfigurationTest.java:122)
```
