### ISSUE TITLE
Use different Export Delay of Export rules triggering calculation of Query Attributes and Study Size in default configuration to avoid concurrency issues 

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4chee-arc-light#2161]
Change value for **Export Delay** of [Export Rule](https://dcm4chee-arc-cs.readthedocs.io/en/latest/networking/config/exportRule.html) `CalculateStudySize` in the default configuration from 5 (=`PT5M`) to 6 (`PT6M`) minutes.

_Rationale:_
Using the same value for Export Delay of Export rules triggering calculation of Query Attributes and Study Size causes concurrency issues on inserts into DB table `study_query_attrs` :
```
019-09-04 12:12:49,448 WARN  [org.dcm4chee.arc.export.mgt.impl.ExportManagerEJB] (EE-ManagedScheduledExecutorService-default-Thread-1) Failed to query Export Task Info for ExportTask[pk=4926, exporterID=CalculateStudySize, studyUID=1.2.826.0.1.3680043.2.1237.680599246919.20190815155153.1.709, seriesUID=*, objectUID=*] - : javax.ejb.EJBTransactionRolledbackException: javax.persistence.PersistenceException: org.hibernate.exception.ConstraintViolationException: could not execute statement
Caused by: javax.ejb.EJBException: javax.persistence.PersistenceException: org.hibernate.exception.ConstraintViolationException: could not execute statement
Caused by: javax.persistence.PersistenceException: org.hibernate.exception.ConstraintViolationException: could not execute statement
Caused by: org.hibernate.exception.ConstraintViolationException: could not execute statement
Caused by: java.sql.SQLIntegrityConstraintViolationException: (conn=200) Duplicate entry 'hideRejected-2222' for key 'UK_prn4qt6d42stw0gfi1yce1fap'
Caused by: java.sql.SQLException: Duplicate entry 'hideRejected-2222' for key 'UK_prn4qt6d42stw0gfi1yce1fap'
```

Related #1357

**Comment by sgala** [comment]
Hi, we are still seeing this problem in a configuration with some volume. We are using 5.19.0 with MariaDB/MySQL. This error pops up quite frequently, rolling back exporters. We also have accumulated more than 1 million each "Calculate Size" and "Calculate Query Attributes" Tasks in the TO_SCHEDULE state, which I can't see any way to remove.

I wonder in particular if https://github.com/dcm4che/dcm4chee-arc-light/issues/2222  and https://github.com/dcm4che/dcm4chee-arc-light/issues/2306 could somehow be also related with this issue and if there is some workaround while we can upgrade this deployment to a more recent version.

**Comment by vrindanayak** [comment]
I assume you have configured delays for `Calculate Study Size` and `Calculate Query Attributes` to different values as indicated in this issue. We too have installations with millions of records and so far we have not faced issues related to it. Also, try to schedule them in different queues to balance the load.
If you want to remove the `TO_SCHEDULE` tasks, you could simply use `Delete all matching tasks` (optionally setting filters as required) from `All Actions` dropdown on `Monitoring page -> Export tab`.

#2306 facilitates you to explicitly schedule the `TO_SCHEDULE` tasks before being picked by the scheduler to schedule them.
#2222 makes the export scheduler more robust in terms of processing of scheduled export tasks.

It is always recommended to keep the archive version updated to the latest version

**Comment by sgala** [comment]
We have been asking for an upgrade window for a long time, but things don't always work as we want.

The question is that even with different delays and in different queues no single Calculate Study Size and Calculate Query Attributes task run. They just accumulate, not a single one gets scheduled.

I'm hoping for a quick upgrade fixing the issue, but it will take at least another week.

**Comment by vrindanayak** [comment]
- What value do you see for `scheduled_time` for these export tasks in your database?
- Are you seeing any exception the server.log related to https://github.com/dcm4che/dcm4chee-arc-light/issues/2499

**Comment by sgala** [comment]
The scheduled_time is like:

CreatedTime:       2020-07-03T11:21:57.000-0500
UpdatedTime:      2020-07-03T11:22:05.000-0500
ScheduledTime:  2020-07-03T11:24:05.000-0500

And they stay forever like this, as they never get scheduled.

No exceptions that I can relate, I see a steady flow of:

`2020-07-03 11:32:03,084 INFO  [org.dcm4chee.arc.export.mgt.impl.ExportManagerEJB] (EE-ManagedExecutorService-default-Thread-28072) Create ExportTask[pk=4384665, exporterID=CalculateQueryAttributes, studyUID=<StudyInstanceUID>, seriesUID=*, objectUID=*]
2020-07-03 11:32:03,104 INFO  [org.dcm4chee.arc.export.mgt.impl.ExportManagerEJB] (EE-ManagedExecutorService-default-Thread-28072) Create ExportTask[pk=4384666, exporterID=CalculateStudySize, studyUID=<StudyInstanceUID>, seriesUID=*, objectUID=*]
`

**Comment by vrindanayak** [comment]
Not reproducible on my side as I don't see a reason why the export tasks wouldn't get scheduled, unless except one of the following is true
- There is no value set for `Export Task Polling Interval` in LDAP configuration.
- The LDAP configuration for archive device name associated with export tasks is not found or `scheduled_time` is not yet reached. 
- #2499 as a cause, due to which scheduling of export tasks gets aborted.

Do you see the following in your server.log ?
````
11:09:22,773 INFO  [org.dcm4chee.arc.export.mgt.impl.ExportScheduler] (EE-ManagedScheduledExecutorService-default-Thread-1) start ExportScheduler.execute()
11:09:22,776 INFO  [org.dcm4chee.arc.export.mgt.impl.ExportScheduler] (EE-ManagedScheduledExecutorService-default-Thread-1) finished ExportScheduler.execute()
````
and if anything in between these 2 lines.

Also if possible, activate the hibernate logging in your wildfly and then see if you find following database query (corresponding to mysql dialect) in your server.log 
````
select o.pk from ExportTask o where o.deviceName=?1 and o.scheduledTime < current_timestamp and o.queueMessage is null
````

**Comment by sgala** [comment]
Now this is a thing... You gave me a good hint I found in the logs:

* ... start ExportScheduler.execute()
* -> ExportScheduler throws two exceptions
* finished ExportScheduler.execute()

The exceptions are ( snipped by `egrep "(^Caused by)|\ ExportScheduler.execute|org.dcm4chee.arc.export.mgt.impl.ExportScheduler"` ):

```
2020-07-04 01:53:36,397 INFO  [org.dcm4chee.arc.export.mgt.impl.ExportScheduler] (EE-ManagedScheduledExecutorService-default-Thread-1) start ExportScheduler.execute()
        at deployment.dcm4chee-arc-ear-5.19.0-mysql.ear.dcm4chee-arc-export-mgt-5.19.0.jar//org.dcm4chee.arc.export.mgt.impl.ExportScheduler.execute(ExportScheduler.java:50)
Caused by: javax.persistence.PersistenceException: org.hibernate.exception.ConstraintViolationException: could not execute statement
Caused by: org.hibernate.exception.ConstraintViolationException: could not execute statement
Caused by: java.sql.SQLIntegrityConstraintViolationException: Duplicate entry 'hideRejected-240761' for key 'UK_prn4qt6d42stw0gfi1yce1fap'
        at deployment.dcm4chee-arc-ear-5.19.0-mysql.ear.dcm4chee-arc-export-mgt-5.19.0.jar//org.dcm4chee.arc.export.mgt.impl.ExportScheduler.execute(ExportScheduler.java:50)
Caused by: javax.ejb.EJBException: javax.persistence.PersistenceException: org.hibernate.exception.ConstraintViolationException: could not execute statement
Caused by: javax.persistence.PersistenceException: org.hibernate.exception.ConstraintViolationException: could not execute statement
Caused by: org.hibernate.exception.ConstraintViolationException: could not execute statement
Caused by: java.sql.SQLIntegrityConstraintViolationException: Duplicate entry 'hideRejected-240761' for key 'UK_prn4qt6d42stw0gfi1yce1fap'
        at deployment.dcm4chee-arc-ear-5.19.0-mysql.ear.dcm4chee-arc-export-mgt-5.19.0.jar//org.dcm4chee.arc.export.mgt.impl.ExportScheduler.execute(ExportScheduler.java:50)
Caused by: javax.ejb.EJBException: javax.persistence.PersistenceException: org.hibernate.exception.ConstraintViolationException: could not execute statement
Caused by: javax.persistence.PersistenceException: org.hibernate.exception.ConstraintViolationException: could not execute statement
Caused by: org.hibernate.exception.ConstraintViolationException: could not execute statement
Caused by: java.sql.SQLIntegrityConstraintViolationException: Duplicate entry 'hideRejected-240761' for key 'UK_prn4qt6d42stw0gfi1yce1fap'
        at deployment.dcm4chee-arc-ear-5.19.0-mysql.ear.dcm4chee-arc-export-mgt-5.19.0.jar//org.dcm4chee.arc.export.mgt.impl.ExportScheduler.execute(ExportScheduler.java:50)
Caused by: javax.persistence.TransactionRequiredException: WFLYJPA0060: Transaction is required to perform this operation (either use a transaction or extended persistence context)
        at deployment.dcm4chee-arc-ear-5.19.0-mysql.ear.dcm4chee-arc-export-mgt-5.19.0.jar//org.dcm4chee.arc.export.mgt.impl.ExportScheduler.execute(ExportScheduler.java:50)
Caused by: javax.persistence.TransactionRequiredException: WFLYJPA0060: Transaction is required to perform this operation (either use a transaction or extended persistence context)
2020-07-04 01:53:36,876 WARN  [org.dcm4chee.arc.export.mgt.impl.ExportScheduler] (EE-ManagedScheduledExecutorService-default-Thread-1) ExportScheduler.execute() throws:
        at deployment.dcm4chee-arc-ear-5.19.0-mysql.ear.dcm4chee-arc-export-mgt-5.19.0.jar//org.dcm4chee.arc.export.mgt.impl.ExportScheduler.execute(ExportScheduler.java:50)
Caused by: javax.persistence.TransactionRequiredException: WFLYJPA0060: Transaction is required to perform this operation (either use a transaction or extended persistence context)
2020-07-04 01:53:36,876 INFO  [org.dcm4chee.arc.export.mgt.impl.ExportScheduler] (EE-ManagedScheduledExecutorService-default-Thread-1) finished ExportScheduler.execute()
```

I can't make sense of the exception but this is what I'm getting.

**Comment by sgala** [comment]
Further info, for the information of people checking here: these kind of errors were constant with 5.19.0. When we updated to 5.22.3 they stopped happening and the handling of the Exports seems to be perfect up to now.
