### ISSUE TITLE
WARNING while executing Export Task

### ISSUE THREAD

**Issue by mokbelt** [dcm4che/dcm4chee-arc-light#2274]
Ver 5.17.1

While execturing export task, I am getting the below warning in log.
The export tasks anyway execute succesfully and can be seen as COMPLETED in the Monitoring>Export list.

The error:
2019-11-22 10:58:02,115 WARN  [org.dcm4chee.arc.export.mgt.impl.ExportManagerEJB] (EE-ManagedScheduledExecutorService-default-Thread-2) Failed to query Export Task Info for ExportTask[pk=367, exporterID=CalculateQueryAttributes, studyUID=2.25.73328893483652304200050953946158721416, seriesUID=*, objectUID=*] - : java.lang.NullPointerException
	at org.dcm4chee.arc.query.impl.QueryServiceImpl.queryExportTaskInfo(QueryServiceImpl.java:267)
	at org.dcm4chee.arc.query.impl.QueryServiceImpl$Proxy$_$$_WeldClientProxy.queryExportTaskInfo(Unknown Source)
	at org.dcm4chee.arc.export.mgt.impl.ExportManagerEJB.scheduleExportTask(ExportManagerEJB.java:260)
	at org.dcm4chee.arc.export.mgt.impl.ExportManagerEJB.scheduleExportTasks(ExportManagerEJB.java:195)
	at sun.reflect.GeneratedMethodAccessor93.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.as.ee.component.ManagedReferenceMethodInterceptor.processInvocation(ManagedReferenceMethodInterceptor.java:52)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.invocation.InterceptorContext$Invocation.proceed(InterceptorContext.java:509)
	at org.jboss.as.weld.interceptors.Jsr299BindingsInterceptor.delegateInterception(Jsr299BindingsInterceptor.java:79)
	at org.jboss.as.weld.interceptors.Jsr299BindingsInterceptor.doMethodInterception(Jsr299BindingsInterceptor.java:89)
	at org.jboss.as.weld.interceptors.Jsr299BindingsInterceptor.processInvocation(Jsr299BindingsInterceptor.java:102)
	at org.jboss.as.ee.component.interceptors.UserInterceptorFactory$1.processInvocation(UserInterceptorFactory.java:63)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.as.ejb3.component.invocationmetrics.ExecutionTimeInterceptor.processInvocation(ExecutionTimeInterceptor.java:43)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.as.jpa.interceptor.SBInvocationInterceptor.processInvocation(SBInvocationInterceptor.java:47)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.as.ee.concurrent.ConcurrentContextInterceptor.processInvocation(ConcurrentContextInterceptor.java:45)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.invocation.InitialInterceptor.processInvocation(InitialInterceptor.java:40)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.invocation.ChainedInterceptor.processInvocation(ChainedInterceptor.java:53)
	at org.jboss.as.ee.component.interceptors.ComponentDispatcherInterceptor.processInvocation(ComponentDispatcherInterceptor.java:52)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.as.ejb3.component.pool.PooledInstanceInterceptor.processInvocation(PooledInstanceInterceptor.java:51)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.as.ejb3.component.interceptors.AdditionalSetupInterceptor.processInvocation(AdditionalSetupInterceptor.java:54)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.as.ejb3.tx.CMTTxInterceptor.invokeInOurTx(CMTTxInterceptor.java:237)
	at org.jboss.as.ejb3.tx.CMTTxInterceptor.required(CMTTxInterceptor.java:362)
	at org.jboss.as.ejb3.tx.CMTTxInterceptor.processInvocation(CMTTxInterceptor.java:144)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.invocation.InterceptorContext$Invocation.proceed(InterceptorContext.java:509)
	at org.jboss.weld.module.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:81)
	at org.jboss.as.weld.ejb.EjbRequestScopeActivationInterceptor.processInvocation(EjbRequestScopeActivationInterceptor.java:89)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.as.ejb3.component.interceptors.CurrentInvocationContextInterceptor.processInvocation(CurrentInvocationContextInterceptor.java:41)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.as.ejb3.component.invocationmetrics.WaitTimeInterceptor.processInvocation(WaitTimeInterceptor.java:47)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.as.ejb3.security.SecurityContextInterceptor.processInvocation(SecurityContextInterceptor.java:100)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.as.ejb3.deployment.processors.StartupAwaitInterceptor.processInvocation(StartupAwaitInterceptor.java:22)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.as.ejb3.component.interceptors.ShutDownInterceptorFactory$1.processInvocation(ShutDownInterceptorFactory.java:64)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.as.ejb3.component.interceptors.LoggingInterceptor.processInvocation(LoggingInterceptor.java:67)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.as.ee.component.NamespaceContextInterceptor.processInvocation(NamespaceContextInterceptor.java:50)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.invocation.ContextClassLoaderInterceptor.processInvocation(ContextClassLoaderInterceptor.java:60)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.invocation.InterceptorContext.run(InterceptorContext.java:438)
	at org.wildfly.security.manager.WildFlySecurityManager.doChecked(WildFlySecurityManager.java:618)
	at org.jboss.invocation.AccessCheckingInterceptor.processInvocation(AccessCheckingInterceptor.java:57)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.invocation.ChainedInterceptor.processInvocation(ChainedInterceptor.java:53)
	at org.jboss.as.ee.component.ViewService$View.invoke(ViewService.java:198)
	at org.jboss.as.ee.component.ViewDescription$1.processInvocation(ViewDescription.java:185)
	at org.jboss.as.ee.component.ProxyInvocationHandler.invoke(ProxyInvocationHandler.java:81)
	at org.dcm4chee.arc.export.mgt.ExportManager$$$view57.scheduleExportTasks(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor92.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.weld.util.reflection.Reflections.invokeAndUnwrap(Reflections.java:410)
	at org.jboss.weld.module.ejb.EnterpriseBeanProxyMethodHandler.invoke(EnterpriseBeanProxyMethodHandler.java:134)
	at org.jboss.weld.bean.proxy.EnterpriseTargetBeanInstance.invoke(EnterpriseTargetBeanInstance.java:56)
	at org.jboss.weld.module.ejb.InjectionPointPropagatingEnterpriseTargetBeanInstance.invoke(InjectionPointPropagatingEnterpriseTargetBeanInstance.java:68)
	at org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke(ProxyMethodHandler.java:106)
	at org.dcm4chee.arc.export.mgt.impl.ExportManager$1469038282$Proxy$_$$_Weld$EnterpriseProxy$.scheduleExportTasks(Unknown Source)
	at org.dcm4chee.arc.export.mgt.impl.ExportScheduler.execute(ExportScheduler.java:50)
	at org.dcm4chee.arc.Scheduler.run(Scheduler.java:77)
	at org.jboss.as.ee.concurrent.ControlPointUtils$ControlledScheduledRunnable.run(ControlPointUtils.java:158)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at org.glassfish.enterprise.concurrent.internal.ManagedScheduledThreadPoolExecutor$ManagedScheduledFutureTask.access$201(ManagedScheduledThreadPoolExecutor.java:383)
	at org.glassfish.enterprise.concurrent.internal.ManagedScheduledThreadPoolExecutor$ManagedScheduledFutureTask.run(ManagedScheduledThreadPoolExecutor.java:534)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at org.glassfish.enterprise.concurrent.ManagedThreadFactoryImpl$ManagedThread.run(ManagedThreadFactoryImpl.java:250)

2019-11-22 10:58:02,147 INFO  [org.dcm4chee.arc.export.mgt.impl.ExportManagerEJB] (EE-ManagedScheduledExecutorService-default-Thread-2) Schedule ExportTask[pk=368, exporterID=CalculateStudySize, studyUID=2.25.73328893483652304200050953946158721416, seriesUID=*, objectUID=*]
2019-11-22 10:58:02,162 INFO  [org.dcm4chee.arc.qmgt.impl.QueueManagerEJB] (EE-ManagedScheduledExecutorService-default-Thread-2) Schedule Task[id=ID:306cc19e-0d06-11ea-aa89-00155d01b000] at Queue Export4
2019-11-22 10:58:02,162 WARN  [org.dcm4chee.arc.export.mgt.impl.ExportManagerEJB] (EE-ManagedScheduledExecutorService-default-Thread-2) Failed to query Export Task Info for ExportTask[pk=368, exporterID=CalculateStudySize, studyUID=2.25.73328893483652304200050953946158721416, seriesUID=*, objectUID=*] - : java.lang.NullPointerException
	at org.dcm4chee.arc.query.impl.QueryServiceImpl.queryExportTaskInfo(QueryServiceImpl.java:267)
	at org.dcm4chee.arc.query.impl.QueryServiceImpl$Proxy$_$$_WeldClientProxy.queryExportTaskInfo(Unknown Source)
	at org.dcm4chee.arc.export.mgt.impl.ExportManagerEJB.scheduleExportTask(ExportManagerEJB.java:260)
	at org.dcm4chee.arc.export.mgt.impl.ExportManagerEJB.scheduleExportTasks(ExportManagerEJB.java:195)
	at sun.reflect.GeneratedMethodAccessor93.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.as.ee.component.ManagedReferenceMethodInterceptor.processInvocation(ManagedReferenceMethodInterceptor.java:52)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.invocation.InterceptorContext$Invocation.proceed(InterceptorContext.java:509)
	at org.jboss.as.weld.interceptors.Jsr299BindingsInterceptor.delegateInterception(Jsr299BindingsInterceptor.java:79)
	at org.jboss.as.weld.interceptors.Jsr299BindingsInterceptor.doMethodInterception(Jsr299BindingsInterceptor.java:89)
	at org.jboss.as.weld.interceptors.Jsr299BindingsInterceptor.processInvocation(Jsr299BindingsInterceptor.java:102)
	at org.jboss.as.ee.component.interceptors.UserInterceptorFactory$1.processInvocation(UserInterceptorFactory.java:63)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.as.ejb3.component.invocationmetrics.ExecutionTimeInterceptor.processInvocation(ExecutionTimeInterceptor.java:43)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.as.jpa.interceptor.SBInvocationInterceptor.processInvocation(SBInvocationInterceptor.java:47)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.as.ee.concurrent.ConcurrentContextInterceptor.processInvocation(ConcurrentContextInterceptor.java:45)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.invocation.InitialInterceptor.processInvocation(InitialInterceptor.java:40)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.invocation.ChainedInterceptor.processInvocation(ChainedInterceptor.java:53)
	at org.jboss.as.ee.component.interceptors.ComponentDispatcherInterceptor.processInvocation(ComponentDispatcherInterceptor.java:52)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.as.ejb3.component.pool.PooledInstanceInterceptor.processInvocation(PooledInstanceInterceptor.java:51)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.as.ejb3.component.interceptors.AdditionalSetupInterceptor.processInvocation(AdditionalSetupInterceptor.java:54)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.as.ejb3.tx.CMTTxInterceptor.invokeInOurTx(CMTTxInterceptor.java:237)
	at org.jboss.as.ejb3.tx.CMTTxInterceptor.required(CMTTxInterceptor.java:362)
	at org.jboss.as.ejb3.tx.CMTTxInterceptor.processInvocation(CMTTxInterceptor.java:144)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.invocation.InterceptorContext$Invocation.proceed(InterceptorContext.java:509)
	at org.jboss.weld.module.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:81)
	at org.jboss.as.weld.ejb.EjbRequestScopeActivationInterceptor.processInvocation(EjbRequestScopeActivationInterceptor.java:89)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.as.ejb3.component.interceptors.CurrentInvocationContextInterceptor.processInvocation(CurrentInvocationContextInterceptor.java:41)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.as.ejb3.component.invocationmetrics.WaitTimeInterceptor.processInvocation(WaitTimeInterceptor.java:47)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.as.ejb3.security.SecurityContextInterceptor.processInvocation(SecurityContextInterceptor.java:100)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.as.ejb3.deployment.processors.StartupAwaitInterceptor.processInvocation(StartupAwaitInterceptor.java:22)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.as.ejb3.component.interceptors.ShutDownInterceptorFactory$1.processInvocation(ShutDownInterceptorFactory.java:64)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.as.ejb3.component.interceptors.LoggingInterceptor.processInvocation(LoggingInterceptor.java:67)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.as.ee.component.NamespaceContextInterceptor.processInvocation(NamespaceContextInterceptor.java:50)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.invocation.ContextClassLoaderInterceptor.processInvocation(ContextClassLoaderInterceptor.java:60)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.invocation.InterceptorContext.run(InterceptorContext.java:438)
	at org.wildfly.security.manager.WildFlySecurityManager.doChecked(WildFlySecurityManager.java:618)
	at org.jboss.invocation.AccessCheckingInterceptor.processInvocation(AccessCheckingInterceptor.java:57)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.invocation.ChainedInterceptor.processInvocation(ChainedInterceptor.java:53)
	at org.jboss.as.ee.component.ViewService$View.invoke(ViewService.java:198)
	at org.jboss.as.ee.component.ViewDescription$1.processInvocation(ViewDescription.java:185)
	at org.jboss.as.ee.component.ProxyInvocationHandler.invoke(ProxyInvocationHandler.java:81)
	at org.dcm4chee.arc.export.mgt.ExportManager$$$view57.scheduleExportTasks(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor92.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.weld.util.reflection.Reflections.invokeAndUnwrap(Reflections.java:410)
	at org.jboss.weld.module.ejb.EnterpriseBeanProxyMethodHandler.invoke(EnterpriseBeanProxyMethodHandler.java:134)
	at org.jboss.weld.bean.proxy.EnterpriseTargetBeanInstance.invoke(EnterpriseTargetBeanInstance.java:56)
	at org.jboss.weld.module.ejb.InjectionPointPropagatingEnterpriseTargetBeanInstance.invoke(InjectionPointPropagatingEnterpriseTargetBeanInstance.java:68)
	at org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke(ProxyMethodHandler.java:106)
	at org.dcm4chee.arc.export.mgt.impl.ExportManager$1469038282$Proxy$_$$_Weld$EnterpriseProxy$.scheduleExportTasks(Unknown Source)
	at org.dcm4chee.arc.export.mgt.impl.ExportScheduler.execute(ExportScheduler.java:50)
	at org.dcm4chee.arc.Scheduler.run(Scheduler.java:77)
	at org.jboss.as.ee.concurrent.ControlPointUtils$ControlledScheduledRunnable.run(ControlPointUtils.java:158)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at org.glassfish.enterprise.concurrent.internal.ManagedScheduledThreadPoolExecutor$ManagedScheduledFutureTask.access$201(ManagedScheduledThreadPoolExecutor.java:383)
	at org.glassfish.enterprise.concurrent.internal.ManagedScheduledThreadPoolExecutor$ManagedScheduledFutureTask.run(ManagedScheduledThreadPoolExecutor.java:534)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at org.glassfish.enterprise.concurrent.ManagedThreadFactoryImpl$ManagedThread.run(ManagedThreadFactoryImpl.java:250)

**Comment by gunterze** [comment]
verify if it also occurs with 5.19.1.

**Comment by mokbelt** [comment]
I planning the upgrade, I am stuck with the procedure of "If one made structural changes - e.g. by adding/removing Network Application Entities or by configuring multiple Archive devices - to the provided default configuration, one has to adjust the provided update-data-VERSION.ldif files in $DCM4CHEE_ARC/ldap":
In fact I added several AET, but I cannot find a file called update**-data-**VERSION.ldif, only the update-config-xxx.ldif.
Please clarify; need to make sure no AET data is lost during upgrade.

**Comment by gunterze** [comment]
```
$ docker exec <container-name> update-data <VERSION>
```
applies  `update-data-<VERSION>.ldif` - s. https://github.com/dcm4che-dockerfiles/slapd-dcm4chee/blob/master/bin/update-data

Also, only the update of the LDAP schema is required, Updating the archive configuration is not mandatory for upgrading the archive version. It's typically only needed for using new features - e.g. accepting UPS services on Association requests.

**Comment by mokbelt** [comment]
Kindly clarify for windows about the update-data-xxx.ldif

**Comment by gunterze** [comment]
`update-data-xxx.ldif` is just a typo at https://github.com/dcm4che/dcm4chee-arc-light/wiki/Upgrade#update-ldap-data . Fixed to `update-config-xxx.ldif`

**Comment by mokbelt** [comment]
Trying to update, at first step (DB update from 5.17.1 to 5.18) I got this error:

mysql -u root -pXXX smlpacs < C:\SMLPACS\PACS\dcm4chee-arc-5.19.1-mysql\sql\update-5.18-mysql.sql

mysql: [Warning] Using a password on the command line interface can be insecure.
*ERROR 1364 (HY000) at line 15: Field 'pk' doesn't have a default value*

**Comment by gunterze** [comment]
https://github.com/dcm4che/dcm4chee-arc-light/issues/2275

Seems, `auto_increment` for the pk is missing in the create table statement...

**Comment by vrindanayak** [comment]
#2275 is fixed. Please try with the updated [update-5.18-mysql.sql](https://raw.githubusercontent.com/wiki/dcm4che/dcm4chee-arc-light/mysql/update-5.18-mysql.sql) file

**Comment by mokbelt** [comment]
SQL update passed succesfully, and I deleted the *ou=objectclasses* of *ou=schema
+ cn=dcm4chee*, *ou=schema + cn=dcm4chee-archive* and *ou=schema + cn=dcm4chee-archive-ui* and then deleted the whole entries themselves.

Howehver I was stuck in the step of *Update LDAP Data*, using LDIF Import funtion, it successfully passed the update-config-5.18.0.LDIF and update-config-5.18.1.LDIF but failed on update-config-5.19.0.LDIF (and 5.19.1) giving this error:

_Error while importing LDIF
 - [LDAP: error code 32 - NO_SUCH_OBJECT: failed for MessageType : ADD_REQUES
java.lang.Exception: [LDAP: error code 32 - NO_SUCH_OBJECT: failed for MessageType : ADD_REQUEST
Message ID : 1209
    Add Request :
Entry
    dn: cn=RT Radiation Set Storage SCP,dicomAETitle=DCM4CHEE,dicomDeviceName=dcm4chee-arc,cn=Devices,cn=DICOM Configuration,dc=dcm4che,dc=org
    objectClass: dicomTransferCapability
    objectClass: dcmTransferCapability
    dicomSOPClass: 1.2.840.10008.5.1.4.1.1.481.12
    dicomTransferRole: SCP
    cn: RT Radiation Set Storage SCP
    dicomTransferSyntax: 1.2.840.10008.1.2
    dicomTransferSyntax: 1.2.840.10008.1.2.1
: ERR_251_PARENT_NOT_FOUND Parent dicomAETitle=DCM4CHEE,dicomDeviceName=dcm4chee-arc,cn=Devices,cn=DICOM Configuration,dc=dcm4che,dc=org not found]
	at org.apache.directory.studio.connection.core.io.api.DirectoryApiConnectionWrapper.checkResponse(DirectoryApiConnectionWrapper.java:1278)
	at org.apache.directory.studio.connection.core.io.api.DirectoryApiConnectionWrapper.access$9(DirectoryApiConnectionWrapper.java:1246)
	at org.apache.directory.studio.connection.core.io.api.DirectoryApiConnectionWrapper$6.run(DirectoryApiConnectionWrapper.java:926)
	at org.apache.directory.studio.connection.core.io.api.DirectoryApiConnectionWrapper.runAndMonitor(DirectoryApiConnectionWrapper.java:1173)
	at org.apache.directory.studio.connection.core.io.api.DirectoryApiConnectionWrapper.checkConnectionAndRunAndMonitor(DirectoryApiConnectionWrapper.java:1107)
	at org.apache.directory.studio.connection.core.io.api.DirectoryApiConnectionWrapper.createEntry(DirectoryApiConnectionWrapper.java:948)
	at org.apache.directory.studio.ldapbrowser.core.jobs.ImportLdifRunnable.importLdifRecord(ImportLdifRunnable.java:465)
	at org.apache.directory.studio.ldapbrowser.core.jobs.ImportLdifRunnable.importLdif(ImportLdifRunnable.java:272)
	at org.apache.directory.studio.ldapbrowser.core.jobs.ImportLdifRunnable.run(ImportLdifRunnable.java:218)
	at org.apache.directory.studio.connection.core.jobs.StudioConnectionJob.run(StudioConnectionJob.java:109)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)_

**Comment by gunterze** [comment]
Did you renamed the default AET "DCM4CHEE" in your installation? In that case you have to rename the AET in the update-config-xxx.ldif files accordingly. You may use `sed` according https://github.com/dcm4che-dockerfiles/slapd-dcm4chee/blob/master/bin/update-data . You may run the script for each of your added AETs, using `ldapmodify -c` to continue on failures caused by existing objects added by a previous run.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by mokbelt** [comment]
Done and passed successfully.
Now ApacheDS is no longer starting (also standalone.bat -c), giving this error (apacheDS):

[15:58:30] ERROR [org.apache.directory.api.ldap.model.entry.DefaultAttribute] - ERR_13215_VALUE_EXPECT_STRING The value is expected to be a String
[15:58:30] ERROR [org.apache.directory.api.ldap.schema.loader.LdifSchemaLoader] - ERR_16009_LDIF_LOAD_FAIL Failed to load schema LDIF file cn=dcm4che.ldif
org.apache.directory.api.ldap.model.exception.LdapInvalidAttributeValueException: ERR_13215_VALUE_EXPECT_STRING The value is expected to be a String

**Comment by mokbelt** [comment]
Above issue was fixed: The LDIF files (cn=dcm4che.ldif, cn=dcm4chee-archive.ldif and cn=dcm4chee-archive-ui.ldif) had some special characters that were replaced by "creatorsName: uid=admin,ou=system" and the ApacheDS started successfully.

Continuing, The procedure  (upgrading from 5.17.1) **failed in adding the jms queues** as below, and successful in undeploying and deploying. The UI started successfully.
Howhever, the previously created AET in 5.17.1 appeared inside "Configuration" on UI but didn't appear in the "Web App Service" while querying Studies and MWL on the UI.

Please advise what was missed.

JBOSS:
[standalone@localhost:9990 /]
[standalone@localhost:9990 /] jms-queue add --queue-address=StgVerTasks --entries=java:/jms/queue/StgVerTasks
WFLYCTL0212: Duplicate resource [
    ("subsystem" => "messaging-activemq"),
    ("server" => "default"),
    ("jms-queue" => "StgVerTasks")
]

[standalone@localhost:9990 /] jms-queue add --queue-address=Retrieve1 --entries=java:/jms/queue/Retrieve1
WFLYCTL0212: Duplicate resource [
    ("subsystem" => "messaging-activemq"),
    ("server" => "default"),
    ("jms-queue" => "Retrieve1")
]

[standalone@localhost:9990 /] jms-queue remove --queue-address=CMoveSCU
WFLYCTL0216: Management resource '[
    ("subsystem" => "messaging-activemq"),
    ("server" => "default"),
    ("jms-queue" => "CMoveSCU")
]' not found

[standalone@localhost:9990 /] jms-queue remove --queue-address=CMoveSCU
WFLYCTL0216: Management resource '[
    ("subsystem" => "messaging-activemq"),
    ("server" => "default"),
    ("jms-queue" => "CMoveSCU")
]' not found

[standalone@localhost:9990 /] undeploy dcm4chee-arc-ear-5.17.1-mysql.ear

[standalone@localhost:9990 /] deploy C:\SMLPACS\PACS\dcm4chee-arc-5.19.1-mysql\deploy\dcm4chee-arc-ear-5.19.1-mysql.ear
[standalone@localhost:9990 /]

**Comment by mokbelt** [comment]
Referring to above post: The previously modified AET on 5.17.1
![image](https://user-images.githubusercontent.com/56265911/69700237-9d92e000-10f2-11ea-8210-85f0adf197e2.png)
and the actual Web App Services on 5.19.1
![image](https://user-images.githubusercontent.com/56265911/69700271-b7ccbe00-10f2-11ea-92e2-48f2cb957769.png)

**Comment by gunterze** [comment]
Guess you never changed the default of the Web Application names, which becomes now visible with the new "Study" page. You may rename it using the UI: dcm4chee-arc > Device Extension > Child Objects > Web Applications > DCM4CHEE
s.o. #1967

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by mokbelt** [comment]
Did it, the AET now appearing in Study UI, bu while querying, it is giving error:

2019-11-27 10:39:35,742 INFO  [org.dcm4chee.arc.export.mgt.impl.ExportScheduler] (EE-ManagedScheduledExecutorService-default-Thread-2) start ExportScheduler.execute()
2019-11-27 10:39:35,742 INFO  [org.dcm4chee.arc.export.mgt.impl.ExportScheduler] (EE-ManagedScheduledExecutorService-default-Thread-2) finished ExportScheduler.execute()
2019-11-27 10:39:43,766 INFO  [org.dcm4chee.arc.qido.QidoRS] (default task-17) Process GET /dcm4chee-arc/aets/DCM4CHEE/rs/studies?offset=0 from null@127.0.0.1

**Comment by gunterze** [comment]
You also have to adjust the **Web Service Path** do reflect the changed AET!

**Comment by mokbelt** [comment]
During the upgrade progress, shall stop mysql, jboss, wildfly ??

**Comment by gunterze** [comment]
Please post further question at https://groups.google.com/forum/#!forum/dcm4che
