### ISSUE TITLE
Update Study Attributes fails

### ISSUE THREAD

**Issue by vrindanayak** [dcm4che/dcm4chee-arc-light#234]
17:13:52,953 INFO  [org.dcm4chee.arc.iocm.rs.UpdateAttributes] (default task-120) Process /dcm4chee-arc/aets/DCM4CHEE/rs/patients/-/studies/1.3.12.2.1107.5.1.4.50640.30000008060417464325000000001 from null@127.0.0.1
17:14:09,107 ERROR [org.jboss.resteasy.resteasy_jaxrs.i18n] (default task-120) RESTEASY002010: Failed to execute: javax.ws.rs.WebApplicationException: missing Study Instance UID in message body
        at org.dcm4chee.arc.iocm.rs.UpdateAttributes.updateStudy(UpdateAttributes.java:217)
        at org.dcm4chee.arc.iocm.rs.UpdateAttributes$Proxy$_$$_WeldClientProxy.updateStudy(Unknown Source)

**Comment by vrindanayak** [comment]
Fixed by #235
