### ISSUE TITLE
ConcurrentModificationException onStore 522.3

### ISSUE THREAD

**Issue by sgala** [dcm4che/dcm4chee-arc-light#2678]
**Describe the bug**
I found a number of cases of this exception in logs

' ' ' 
Caused by: java.util.ConcurrentModificationException
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1660)
        at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:735)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
        at deployment.dcm4chee-arc-ear-5.22.3-mysql-secure.ear.dcm4chee-arc-ups-5.22.3.jar//org.dcm4chee.arc.ups.impl.UPSServiceImpl
.onStore(UPSServiceImpl.java:338)
        at jdk.internal.reflect.GeneratedMethodAccessor96.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.jboss.weld.core@3.1.4.Final//org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.ja
va:95)
        at org.jboss.weld.core@3.1.4.Final//org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.ja
va:85)
        at org.jboss.weld.core@3.1.4.Final//org.jboss.weld.injection.MethodInvocationStrategy$SimpleMethodInvocationStrategy.invoke(
MethodInvocationStrategy.java:168)
        at org.jboss.weld.core@3.1.4.Final//org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:330)
        at org.jboss.weld.core@3.1.4.Final//org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:308)
        at org.jboss.weld.core@3.1.4.Final//org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:286)
        at javax.enterprise.api//javax.enterprise.inject.spi.ObserverMethod.notify(ObserverMethod.java:124)
        at org.jboss.weld.core@3.1.4.Final//org.jboss.weld.util.Observers.notify(Observers.java:166)
        at org.jboss.weld.core@3.1.4.Final//org.jboss.weld.event.ObserverNotifier.notifySyncObservers(ObserverNotifier.java:285)
        at org.jboss.weld.core@3.1.4.Final//org.jboss.weld.event.ObserverNotifier.notify(ObserverNotifier.java:273)
        at org.jboss.weld.core@3.1.4.Final//org.jboss.weld.event.EventImpl.fire(EventImpl.java:96)
        at deployment.dcm4chee-arc-ear-5.22.3-mysql-secure.ear.dcm4chee-arc-store-5.22.3.jar//org.dcm4chee.arc.store.impl.StoreServi
ceImpl.fireStoreEvent(StoreServiceImpl.java:394)
        ... 27 more
```

**To Reproduce**
Not sure it is easy to reproduce, as any thread-safety bug

I think that code inspection should be the way

**Expected behavior**
We are not using or have configured anything related with UPS, we upgraded 5.19.0 because it was giving lots of problems with exports. Now this works much better, but I found this one. We don't expect anything related to UPS to interfere with reception of messages.

**Comment by gunterze** [comment]
May be caused by reload of the configuration - e.g. triggered by UI Configuration - during receive of objects. Look for
```
19:04:23,249 INFO  [org.dcm4chee.arc.ctrl.ArchiveCtrl] (default task-7) Process POST /dcm4chee-arc/ctrl/reload from null@192.168.0.143
```
in `server.log`.

**Comment by sgala** [comment]
I have not seen the problem again after the day I reported, so it probably was due to me changing configuration while a number of  tasks were running.
