### ISSUE TITLE
Could not get main file: dcm4chee-arc-oidc.xml

### ISSUE THREAD

**Issue by MinaroShikuchi** [dcm4che/dcm4chee-arc-light#2742]
**Describe the bug**
I'm running "[secured archive services on a single host](https://github.com/dcm4che/dcm4chee-arc-light/wiki/Run-minimum-set-of-archive-services-on-a-single-host)" on local, with example docker compose file
Each container are running exept _dcm4che/dcm4chee-arc-psql:5.22.4-secure_ which is faiiling with this message

```
arc_1       | Importing keystore /opt/wildfly/standalone/configuration/keystores/cacerts.jks to /usr/local/openjdk-11/lib/security/cacerts...
arc_1       | Entry for alias mykey successfully imported.
arc_1       | Import command completed:  1 entries successfully imported, 0 entries failed or cancelled
arc_1       | Waiting for ldap:389 ...
arc_1       | done
arc_1       | Waiting for db:5432 ...
arc_1       | done
arc_1       | Starting Wildfly 20.0.1.Final
arc_1       | =========================================================================
arc_1       | 
arc_1       |   JBoss Bootstrap Environment
arc_1       | 
arc_1       |   JBOSS_HOME: /opt/wildfly
arc_1       | 
arc_1       |   JAVA: /usr/local/openjdk-11/bin/java
arc_1       | 
arc_1       |   JAVA_OPTS:  -server -Xms64m -Xmx512m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true -Djboss.modules.system.pkgs=org.jboss.byteman -Djava.awt.headless=true  --add-exports=java.base/sun.nio.ch=ALL-UNNAMED --add-exports=jdk.unsupported/sun.misc=ALL-UNNAMED --add-exports=jdk.unsupported/sun.reflect=ALL-UNNAMED
arc_1       | 
arc_1       | =========================================================================
arc_1       | 
arc_1       | java.lang.IllegalStateException: WFLYCTL0214: Could not get main file: dcm4chee-arc-oidc.xml. Specified files must be relative to the configuration dir: /opt/wildfly/standalone/configuration
arc_1       |   at org.jboss.as.controller@12.0.3.Final//org.jboss.as.controller.persistence.ConfigurationFile.determineMainFile(ConfigurationFile.java:341)
arc_1       |   at org.jboss.as.controller@12.0.3.Final//org.jboss.as.controller.persistence.ConfigurationFile.<init>(ConfigurationFile.java:179)
arc_1       |   at org.jboss.as.server@12.0.3.Final//org.jboss.as.server.ServerEnvironment.<init>(ServerEnvironment.java:538)
arc_1       |   at org.jboss.as.server@12.0.3.Final//org.jboss.as.server.Main.determineEnvironment(Main.java:388)
arc_1       |   at org.jboss.as.server@12.0.3.Final//org.jboss.as.server.Main.main(Main.java:96)
arc_1       |   at org.jboss.modules.Module.run(Module.java:352)
arc_1       |   at org.jboss.modules.Module.run(Module.java:320)
arc_1       |   at org.jboss.modules.Main.main(Main.java:617)
secured-archive_arc_1 exited with code 1
```

**To Reproduce**
Just copy the docker-compose.yml and docker-compose.yml .env form the example and run `docker-compose up`

**Expected behavior**
Each container should run normally

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.1 LTS (Focal Fossa)
 - Docker version 19.03.8,
 - Browser Version 1.8.95 Chromium: 81.0.4044.138 (Official Build) (64-bit)

**Additional context**
I've checked in `/var/local/dcm4chee-arc/wildfly` and the file `dcm4chee-arc-oidc.xml` does not exist

**Comment by gunterze** [comment]
Not reproducible:
```
$ ls /var/local/dcm4chee-arc/wildfly/configuration/
application-roles.properties    mgmt-users.properties
application-users.properties    standalone-full-ha.xml
dcm4chee-arc                    standalone-full.xml
dcm4chee-arc-logstash.xml       standalone-ha.xml
dcm4chee-arc-oidc-logstash.xml  standalone-load-balancer.xml
dcm4chee-arc-oidc.xml           standalone-microprofile-ha.xml
dcm4chee-arc.xml                standalone-microprofile.xml
keystores                       standalone.xml
logging.properties              standalone_xml_history
mgmt-groups.properties
```
Guess there was already a directory `configuration` in the host directory mounted to `/opt/wildfly/standalone` before the container started.
