### ISSUE TITLE
Invalid audit spool file generated for WADO URI event may cause NullPointerException

### ISSUE THREAD

**Issue by vrindanayak** [dcm4che/dcm4chee-arc-light#2786]
````
2020-09-28 10:00:08,354 INFO  [org.dcm4chee.arc.audit.EventID] (EE-ManagedScheduledExecutorService-default-Thread-3) Invalid patient mismatch code: 0
2020-09-28 10:00:08,354 WARN  [org.dcm4chee.arc.audit.AuditService] (EE-ManagedScheduledExecutorService-default-Thread-3) Failed to process [AuditSpoolFile=/opt/wildfly/standalone/data/audit-spool/Audit+Logger/WADO___URI-172.17.0.1-DEVJ4C-1.2.276.0.7230010.3.1.2.296485376.1.1484917366.62818] of [AuditLogger=Audit Logger].
: java.lang.NullPointerException
        at deployment.j4dcm4chee-arc-ear-5.22.5-psql-secure.ear//org.dcm4chee.arc.audit.EventID$Event.<init>(EventID.java:135)
        at deployment.j4dcm4chee-arc-ear-5.22.5-psql-secure.ear//org.dcm4chee.arc.audit.EventID.toEventIdentification(EventID.java:66)
        at deployment.j4dcm4chee-arc-ear-5.22.5-psql-secure.ear//org.dcm4chee.arc.audit.AuditService.auditWADORetrieve(AuditService.java:609)
        at deployment.j4dcm4chee-arc-ear-5.22.5-psql-secure.ear//org.dcm4chee.arc.audit.AuditService.auditStoreOrWADORetrieve(AuditService.java:591)
        at deployment.j4dcm4chee-arc-ear-5.22.5-psql-secure.ear//org.dcm4chee.arc.audit.AuditService.aggregateAuditMessage(AuditService.java:127)
        at deployment.j4dcm4chee-arc-ear-5.22.5-psql-secure.ear//org.dcm4chee.arc.audit.AuditService.auditAndProcessFile(AuditService.java:381)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.jboss.weld.core@3.1.4.Final//org.jboss.weld.bean.proxy.AbstractBeanInstance.invoke(AbstractBeanInstance.java:38)
        at org.jboss.weld.core@3.1.4.Final//org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke(ProxyMethodHandler.java:106)
        at deployment.j4dcm4chee-arc-ear-5.22.5-psql-secure.ear//org.dcm4chee.arc.audit.AuditService$Proxy$_$$_WeldClientProxy.auditAndProcessFile(Unknown Source)
        at deployment.j4dcm4chee-arc-ear-5.22.5-psql-secure.ear//org.dcm4chee.arc.audit.AuditScheduler.execute(AuditScheduler.java:116)
        at deployment.j4dcm4chee-arc-ear-5.22.5-psql-secure.ear.dcm4chee-arc-service-5.22.5.jar//org.dcm4chee.arc.Scheduler.run(Scheduler.java:78)
        at org.jboss.as.ee@20.0.1.Final//org.jboss.as.ee.concurrent.ControlPointUtils$ControlledScheduledRunnable.run(ControlPointUtils.java:158)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
        at org.glassfish.javax.enterprise.concurrent//org.glassfish.enterprise.concurrent.internal.ManagedScheduledThreadPoolExecutor$ManagedScheduledFutureTask.access$201(ManagedScheduledThreadPoolExecutor.java:360)
        at org.glassfish.javax.enterprise.concurrent//org.glassfish.enterprise.concurrent.internal.ManagedScheduledThreadPoolExecutor$ManagedScheduledFutureTask.run(ManagedScheduledThreadPoolExecutor.java:511)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
        at org.glassfish.javax.enterprise.concurrent//org.glassfish.enterprise.concurrent.ManagedThreadFactoryImpl$ManagedThread.run(ManagedThreadFactoryImpl.java:227)

2020-09-28 10:00:08,358 WARN  [org.dcm4chee.arc.audit.AuditService] (EE-ManagedScheduledExecutorService-default-Thread-3) Failed to mark [AuditSpoolFile=/opt/wildfly/standalone/data/audit-spool/Audit+Logger/WADO___URI-172.17.0.1-DEVJ4C-1.2.276.0.7230010.3.1.2.296485376.1.1484917366.62818] of [AuditLogger=Audit Logger] as failed.
: java.lang.NullPointerException
        at deployment.j4dcm4chee-arc-ear-5.22.5-psql-secure.ear//org.dcm4chee.arc.audit.EventID$Event.<init>(EventID.java:135)
        at deployment.j4dcm4chee-arc-ear-5.22.5-psql-secure.ear//org.dcm4chee.arc.audit.EventID.toEventIdentification(EventID.java:66)
        at deployment.j4dcm4chee-arc-ear-5.22.5-psql-secure.ear//org.dcm4chee.arc.audit.AuditService.auditWADORetrieve(AuditService.java:609)
        at deployment.j4dcm4chee-arc-ear-5.22.5-psql-secure.ear//org.dcm4chee.arc.audit.AuditService.auditStoreOrWADORetrieve(AuditService.java:591)
        at deployment.j4dcm4chee-arc-ear-5.22.5-psql-secure.ear//org.dcm4chee.arc.audit.AuditService.aggregateAuditMessage(AuditService.java:127)
        at deployment.j4dcm4chee-arc-ear-5.22.5-psql-secure.ear//org.dcm4chee.arc.audit.AuditService.auditAndProcessFile(AuditService.java:381)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.jboss.weld.core@3.1.4.Final//org.jboss.weld.bean.proxy.AbstractBeanInstance.invoke(AbstractBeanInstance.java:38)
        at org.jboss.weld.core@3.1.4.Final//org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke(ProxyMethodHandler.java:106)
        at deployment.j4dcm4chee-arc-ear-5.22.5-psql-secure.ear//org.dcm4chee.arc.audit.AuditService$Proxy$_$$_WeldClientProxy.auditAndProcessFile(Unknown Source)
        at deployment.j4dcm4chee-arc-ear-5.22.5-psql-secure.ear//org.dcm4chee.arc.audit.AuditScheduler.execute(AuditScheduler.java:116)
        at deployment.j4dcm4chee-arc-ear-5.22.5-psql-secure.ear.dcm4chee-arc-service-5.22.5.jar//org.dcm4chee.arc.Scheduler.run(Scheduler.java:78)
        at org.jboss.as.ee@20.0.1.Final//org.jboss.as.ee.concurrent.ControlPointUtils$ControlledScheduledRunnable.run(ControlPointUtils.java:158)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
        at org.glassfish.javax.enterprise.concurrent//org.glassfish.enterprise.concurrent.internal.ManagedScheduledThreadPoolExecutor$ManagedScheduledFutureTask.access$201(ManagedScheduledThreadPoolExecutor.java:360)
        at org.glassfish.javax.enterprise.concurrent//org.glassfish.enterprise.concurrent.internal.ManagedScheduledThreadPoolExecutor$ManagedScheduledFutureTask.run(ManagedScheduledThreadPoolExecutor.java:511)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
        at org.glassfish.javax.enterprise.concurrent//org.glassfish.enterprise.concurrent.ManagedThreadFactoryImpl$ManagedThread.run(ManagedThreadFactoryImpl.java:227)
````

[spool-dir.zip](https://github.com/dcm4che/dcm4chee-arc-light/files/5291662/spool-dir.zip)

**Comment by petrkalina** [comment]
```
