### ISSUE TITLE
Prefer matching issuer record containing Universal Entity for partially qualified issuer records in DB when incoming object contains fully qualified issuer

### ISSUE THREAD

**Issue by vrindanayak** [dcm4che/dcm4chee-arc-light#2966]
Test scenario : 
DB contains partially qualified issuer records for eg. 
```
$ psql pacsdb pacs -c "select * from issuer join patient_id pi on issuer.pk = pi.issuer_fk"
Password for user pacs: 
 pk | entity_id | entity_uid | entity_uid_type | pk |  pat_id  | pat_id_type_code | version | issuer_fk 
----+-----------+--------------+-----------------+----+----------+------------------+---------+-----------
  1 | AAA       |                 |                 |  1 | FUJI00014  |                  |       0 |         1
  2 |           |    1.2.3        |    ISO          |  2 | FUJI00007  |                  |       0 |         2
(2 rows)
```

Incoming object contains fully qualified issuer for eg. 

```
storescu -s IssuerOfPatientID=BBB -s IssuerOfPatientIDQualifiersSequence/UniversalEntityID=1.2.3.4.5 -s IssuerOfPatientIDQualifiersSequence/UniversalEntityIDType=ISO -c DCM4CHEE@localhost:11112 ~/Downloads/testData/DICOM/modality/CR/TANAKA\^HANAKO/
```

previously upto 5.22.6 this failed with 
```
Caused by: javax.persistence.NonUniqueResultException: query did not return a unique result: 2
        at org.hibernate@5.3.17.Final//org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:128)
        at org.hibernate@5.3.17.Final//org.hibernate.query.internal.AbstractProducedQuery.getSingleResult(AbstractProducedQuery.java:1561)
        at deployment.dcm4chee-arc-ear-5.22.6-psql.ear.dcm4chee-arc-issuer-5.22.6.jar//org.dcm4chee.arc.issuer.impl.IssuerServiceEJB.find(IssuerServiceEJB.java:109)
        at deployment.dcm4chee-arc-ear-5.22.6-psql.ear.dcm4chee-arc-issuer-5.22.6.jar//org.dcm4chee.arc.issuer.impl.IssuerServiceEJB.mergeOrCreate(IssuerServiceEJB.java:77)
```

instead select the issuer record containing Universal Entity information and merge the corresponding record with additional information (i.e. Local Namespace Entity ID) and reflect this issuer record in `patient_id` record by it's `issuer_fk`

**Comment by vrindanayak** [comment]
Fixed by #2950 commits
