### ISSUE TITLE
org.dcm4chee.arc.entity.BlobCorruptedException: org.dcm4che3.io.DicomStreamException: Not a DICOM Stream at deployment.dcm4chee-arc-ear-5.22.6-

### ISSUE THREAD

**Issue by oliverfchen** [dcm4che/dcm4chee-arc-light#3172]
After delete WML using REST API, can't show WML. The "count" did display 14 items.

**Comment by oliverfchen** [comment]
Error detail
org.dcm4chee.arc.entity.BlobCorruptedException: org.dcm4che3.io.DicomStreamException: Not a DICOM Stream at deployment.dcm4chee-arc-ear-5.22.6-psql.ear//org.dcm4chee.arc.entity.AttributesBlob.decodeAttributes(AttributesBlob.java:128) at deployment.dcm4chee-arc-ear-5.22.6-psql.ear.dcm4chee-arc-query-5.22.6.jar//org.dcm4chee.arc.query.impl.MWLQuery.toAttributes(MWLQuery.java:91) at deployment.dcm4chee-arc-ear-5.22.6-psql.ear.dcm4chee-arc-query-5.22.6.jar//org.dcm4chee.arc.query.impl.AbstractQuery.nextMatch(AbstractQuery.java:140) at deployment.dcm4chee-arc-ear-5.22.6-psql.ear.dcm4chee-arc-query-5.22.6.jar//org.dcm4chee.arc.query.impl.MWLQuery.nextMatch(MWLQuery.java:59) at deployment.dcm4chee-arc-ear-5.22.6-psql.ear.dcm4chee-arc-war-5.22.6-unsecure.war//org.dcm4chee.arc.qido.QidoRS.matches(QidoRS.java:794) at deployment.dcm4chee-arc-ear-5.22.6-psql.ear.dcm4chee-arc-war-5.22.6-unsecure.war//org.dcm4chee.arc.qido.QidoRS.writeJSON(QidoRS.java:757) at deployment.dcm4chee-arc-ear-5.22.6-psql.ear.dcm4chee-arc-war-5.22.6-unsecure.war//org.dcm4chee.arc.qido.QidoRS.access$500(QidoRS.java:94) at deployment.dcm4chee-arc-ear-5.22.6-psql.ear.dcm4chee-arc-war-5.22.6-unsecure.war//org.dcm4chee.arc.qido.QidoRS$Output$2.entity(QidoRS.java:704) at deployment.dcm4chee-arc-ear-5.22.6-psql.ear.dcm4chee-arc-war-5.22.6-unsecure.war//org.dcm4chee.arc.qido.QidoRS.search(QidoRS.java:447) at deployment.dcm4chee-arc-ear-5.22.6-psql.ear.dcm4chee-arc-war-5.22.6-unsecure.war//org.dcm4chee.arc.qido.QidoRS.searchForSPS(QidoRS.java:275) at deployment.dcm4chee-arc-ear-5.22.6-psql.ear.dcm4chee-arc-war-5.22.6-unsecure.war//org.dcm4chee.arc.qido.QidoRS$Proxy$_$$_WeldClientProxy.searchForSPS(Unknown Source) at jdk.internal.reflect.GeneratedMethodAccessor139.invoke(Unknown Source) at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.base/java.lang.reflect.Method.invoke(Method.java:566) at org.jboss.resteasy.resteasy-jaxrs@3.12.1.Final//org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:138) at org.jboss.resteasy.resteasy-jaxrs@3.12.1.Final//org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:543) at org.jboss.resteasy.resteasy-jaxrs@3.12.1.Final//org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:432) at org.jboss.resteasy.resteasy-jaxrs@3.12.1.Final//org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$0(ResourceMethodInvoker.java:393) at org.jboss.resteasy.resteasy-jaxrs@3.12.1.Final//org.jboss.resteasy.core.interception.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:358) at org.jboss.resteasy.resteasy-jaxrs@3.12.1.Final//org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:395) at org.jboss.resteasy.resteasy-jaxrs@3.12.1.Final//org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:364) at org.jboss.resteasy.resteasy-jaxrs@3.12.1.Final//org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:337) at org.jboss.resteasy.resteasy-jaxrs@3.12.1.Final//org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:440) at org.jboss.resteasy.resteasy-jaxrs@3.12.1.Final//org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:229) at org.jboss.resteasy.resteasy-jaxrs@3.12.1.Final//org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:135) at org.jboss.resteasy.resteasy-jaxrs@3.12.1.Final//org.jboss.resteasy.core.interception.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:358) at org.jboss.resteasy.resteasy-jaxrs@3.12.1.Final//org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:138) at org.jboss.resteasy.resteasy-jaxrs@3.12.1.Final//org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:215) at org.jboss.resteasy.resteasy-jaxrs@3.12.1.Final//org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:245) at org.jboss.resteasy.resteasy-jaxrs@3.12.1.Final//org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:61) at org.jboss.resteasy.resteasy-jaxrs@3.12.1.Final//org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56) at javax.servlet.api@2.0.0.Final//javax.servlet.http.HttpServlet.service(HttpServlet.java:590) at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74) at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129) at io.undertow.websocket@2.1.3.Final//io.undertow.websockets.jsr.JsrWebSocketFilter.doFilter(JsrWebSocketFilter.java:173) at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) at io.opentracing.contrib.opentracing-jaxrs2//io.opentracing.contrib.jaxrs2.server.SpanFinishingFilter.doFilter(SpanFinishingFilter.java:52) at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84) at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62) at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68) at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36) at org.wildfly.extension.undertow@20.0.1.Final//org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78) at io.undertow.core@2.1.3.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68) at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:132) at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57) at io.undertow.core@2.1.3.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) at io.undertow.core@2.1.3.Final//io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46) at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64) at io.undertow.core@2.1.3.Final//io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60) at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77) at io.undertow.core@2.1.3.Final//io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50) at io.undertow.core@2.1.3.Final//io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43) at io.undertow.core@2.1.3.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) at org.wildfly.extension.undertow@20.0.1.Final//org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61) at io.undertow.core@2.1.3.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) at org.wildfly.extension.undertow@20.0.1.Final//org.wildfly.extension.undertow.deployment.GlobalRequestControllerHandler.handleRequest(GlobalRequestControllerHandler.java:68) at io.undertow.core@2.1.3.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:269) at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:78) at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:133) at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:130) at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48) at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43) at org.wildfly.extension.undertow@20.0.1.Final//org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105) at org.wildfly.extension.undertow@20.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530) at org.wildfly.extension.undertow@20.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530) at org.wildfly.extension.undertow@20.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530) at org.wildfly.extension.undertow@20.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530) at org.wildfly.extension.undertow@20.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530) at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:249) at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:78) at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:99) at io.undertow.core@2.1.3.Final//io.undertow.server.Connectors.executeRootHandler(Connectors.java:370) at io.undertow.core@2.1.3.Final//io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830) at org.jboss.threads@2.3.3.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35) at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1982) at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486) at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377) at java.base/java.lang.Thread.run(Thread.java:834) Caused by: org.dcm4che3.io.DicomStreamException: Not a DICOM Stream at org.dcm4che.core@5.22.6//org.dcm4che3.io.DicomInputStream.guessTransferSyntax(DicomInputStream.java:862) at org.dcm4che.core@5.22.6//org.dcm4che3.io.DicomInputStream.<init>(DicomInputStream.java:141) at deployment.dcm4chee-arc-ear-5.22.6-psql.ear//org.dcm4chee.arc.entity.AttributesBlob.decodeAttributes(AttributesBlob.java:123) ... 82 more

**Comment by gunterze** [comment]
Would need the exported BLOB from the DB to analyze the issue:
Locate the corrupted MWL by 
- select all Study Instance UIDs by SQL:
  ```
  $ psql pacsdb pacs -c "select study_iuid from mwl_item"
  ```
- probe each of them as filter in the UI MWL tab 
- take the Study Instance UID used as  filter till shows the failure, to export the blob to a file (e.g.):
  ```
  $ psql pacsdb pacs -c "copy (select dicomattrs.attrs from dicomattrs join mwl_item on dicomattrs.pk = mwl_item.dicomattrs_fk where study_iuid='1.113654.3.13.1026') to STDOUT binary" > /tmp/attrs.blob
  ```

**Comment by vrindanayak** [comment]
Just to note : A related [issue](https://github.com/dcm4che/dcm4chee-arc-light/issues/3173) was found in [hl7-order2dcm stylesheet](https://github.com/dcm4che/dcm4chee-arc-light/blob/master/dcm4chee-arc-conf-data/src/main/resources/hl7-order2dcm.xsl) where `(0040,1003) Requested Procedure Priority` had an incorrect VR (CS instead of SH). However, even with incorrect VR, the MWL query did not throw the above exception. 

Before applying fix

![image](https://user-images.githubusercontent.com/15785031/116575588-12cd9a80-a90f-11eb-818e-2c50fc024b10.png)

After applying fix

![image](https://user-images.githubusercontent.com/15785031/116575683-2aa51e80-a90f-11eb-8a97-dc32ca96e110.png)

You may choose to update the stylesheet in your environment as per the [fix](https://github.com/dcm4che/dcm4chee-arc-light/commit/86638409b3526262d653dde97ee1dea000602f87)

**Comment by gunterze** [comment]
After detecting the _Study Instance UID_ of affected studies as described above, you may restore the corrupted BLOBs by re-import of the study by
```
$ curl -v -X POST http://<archive-host>:8080/dcm4chee-arc/aets/DCM4CHEE/rs/studies/<Study Ubstabce UID>/reimport
```
s. #2983
s.o. #3192 included in next release 5.23.3.
