### ISSUE TITLE
DICOM UL Services User Identity Negotiation fails with org.keycloak.jose.jws.JWSInputException: java.lang.NullPointerException

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4chee-arc-light#3236]
```
2021-06-02 16:19:02,576 INFO  [org.dcm4chee.arc.impl.ArchiveAssociationHandler] (EE-ManagedExecutorService-default-Thread-5) DCM4CHEE<-STORESCU(1): validation of   UserIdentity[
    type: 2 - Username and passcode
    username: admin
    passcode: ********
  ] failed:
{}: org.keycloak.jose.jws.JWSInputException: java.lang.NullPointerException
        at org.keycloak.keycloak-core@11.0.3//org.keycloak.jose.jws.JWSInput.<init>(JWSInput.java:58)
        at deployment.dcm4chee-arc-ear-5.23.3-psql-secure.ear//org.dcm4chee.arc.keycloak.AccessTokenRequestor.verifyUsernamePasscode(AccessTokenRequestor.java:161)
        at deployment.dcm4chee-arc-ear-5.23.3-psql-secure.ear//org.dcm4chee.arc.keycloak.AccessTokenRequestor$Proxy$_$$_WeldClientProxy.verifyUsernamePasscode(Unknown Source)
        at deployment.dcm4chee-arc-ear-5.23.3-psql-secure.ear.dcm4chee-arc-service-5.23.3.jar//org.dcm4chee.arc.impl.ArchiveAssociationHandler.validateUserIdentity(ArchiveAssociationHandler.java:114)
        at deployment.dcm4chee-arc-ear-5.23.3-psql-secure.ear.dcm4chee-arc-service-5.23.3.jar//org.dcm4chee.arc.impl.ArchiveAssociationHandler.validateUserIdentity(ArchiveAssociationHandler.java:96)
        at deployment.dcm4chee-arc-ear-5.23.3-psql-secure.ear.dcm4chee-arc-service-5.23.3.jar//org.dcm4chee.arc.impl.ArchiveAssociationHandler.makeAAssociateAC(ArchiveAssociationHandler.java:79)
        at org.dcm4che.net@5.23.3//org.dcm4che3.net.AssociationHandler.negotiate(AssociationHandler.java:94)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.jboss.weld.core@3.1.6.Final//org.jboss.weld.bean.proxy.AbstractBeanInstance.invoke(AbstractBeanInstance.java:38)
        at org.jboss.weld.core@3.1.6.Final//org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke(ProxyMethodHandler.java:106)
        at deployment.dcm4chee-arc-ear-5.23.3-psql-secure.ear.dcm4chee-arc-service-5.23.3.jar//org.dcm4chee.arc.impl.ArchiveAssociationHandler$Proxy$_$$_WeldClientProxy.negotiate(Unknown Source)
        at org.dcm4che.net@5.23.3//org.dcm4che3.net.Association.handle(Association.java:621)
        at org.dcm4che.net@5.23.3//org.dcm4che3.net.State$2.onAAssociateRQ(State.java:75)
        at org.dcm4che.net@5.23.3//org.dcm4che3.net.Association.onAAssociateRQ(Association.java:613)
        at org.dcm4che.net@5.23.3//org.dcm4che3.net.PDUDecoder.nextPDU(PDUDecoder.java:169)
        at org.dcm4che.net@5.23.3//org.dcm4che3.net.Association$2.run(Association.java:571)
        at org.jboss.as.ee@23.0.2.Final//org.jboss.as.ee.concurrent.ControlPointUtils$ControlledRunnable.run(ControlPointUtils.java:125)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at org.glassfish.javax.enterprise.concurrent//org.glassfish.enterprise.concurrent.internal.ManagedFutureTask.run(ManagedFutureTask.java:117)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
        at org.glassfish.javax.enterprise.concurrent//org.glassfish.enterprise.concurrent.ManagedThreadFactoryImpl$ManagedThread.run(ManagedThreadFactoryImpl.java:227)
Caused by: java.lang.NullPointerException
        at org.keycloak.keycloak-core@11.0.3//org.keycloak.jose.jws.JWSInput.<init>(JWSInput.java:44)
        ... 26 more
```
Related #2703

**Comment by gunterze** [comment]
Workaround:
```
$ rm -r $WILDFLY_HOME/modules/system/layers/base/org/jboss/resteasy/resteasy-json-binding-provider
```
