### ISSUE TITLE
fail to cancel rescheduled UPS when there are subscriptions

### ISSUE THREAD

**Issue by codepage949** [dcm4che/dcm4chee-arc-light#3345]
**Describe the bug**

UPS made by `createOnStore` doesn't have `Specific Character Set` attribute. but UPS made by `reschedule` does.

i don't know whether`Specific Character Set` can be included in UPS. anyway, that `Specific Character Set` is included causes an error like below while reporting to subscribers and fails to change.

```
...
Caused by: org.dcm4che3.data.IncompatibleSpecificCharacterSetException: Specific Character Sets [] and [ISO_IR 192] not compatible
	at org.dcm4che.core@5.23.0//org.dcm4che3.data.Attributes.add(Attributes.java:2323)
	at org.dcm4che.core@5.23.0//org.dcm4che3.data.Attributes.addSelected(Attributes.java:2279)
	at org.dcm4che.core@5.23.0//org.dcm4che3.data.Attributes.addSelected(Attributes.java:2262)
	at deployment.dcm4chee-arc-ear-5.23.0-psql-secure.ear.dcm4chee-arc-ups-5.23.0.jar//org.dcm4chee.arc.ups.impl.UPSServiceEJB.stateReportOf(UPSServiceEJB.java:487)
	at deployment.dcm4chee-arc-ear-5.23.0-psql-secure.ear.dcm4chee-arc-ups-5.23.0.jar//org.dcm4chee.arc.ups.impl.UPSServiceEJB.changeUPSState(UPSServiceEJB.java:407)
...
```

**To Reproduce**
1. subscribe UPS
2. make a UPS
3. reschedule the UPS
4. try to change the status of rescheduled UPS to CANCELED

**Expected behavior**
rescheduled UPS was CANCELED

**Desktop (please complete the following information):**
 - OS: linux ubuntu 21.04
 - Browser: chrome 92.0
 - dcm4chee-arc-light: 5.23.0

**Comment by vrindanayak** [comment]
Fixed by #3780
