### ISSUE TITLE
Export of Prior Studies may fail caused by concurrent calculation of Query Attributes for a particular Study or Series

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4chee-arc-light#3356]
```
2021-09-10 17:01:24,021 WARN  [org.dcm4chee.arc.export.mgt.impl.ExportPriorsScheduler] (EE-ManagedExecutorService-default-Thread-35710)
CUFVNAA_FWMOD<-CUFVNAB(409511): Failed to apply ExportPriorsRule{cn=ATS Prefetch Priors on Store, conditions={ReceivingApplicationEntity
Title=CUFVNAA_MOD.*|CUFVNAB_MOD_.*|CUFVNAA_FWMOD|CUFVNAB_FWMOD}, schedules=[], exporterIDs=[ATS Prefetch - QIDO Study Instances, ATS Pre
fetch - QIDO Study Series, ATS Prefetch - Series Metadata, ATS Prefetch - Series Thumbnails], suppressDups=P1D, entitySelectors=[], expo
rtReoccurredInstances=REPLACE}:
: javax.ejb.EJBTransactionRolledbackException: javax.transaction.RollbackException: ARJUNA016053: Could not commit transaction.
        at org.jboss.as.ejb3@23.0.2.Final//org.jboss.as.ejb3.tx.CMTTxInterceptor.endTransaction(CMTTxInterceptor.java:117)
        at org.jboss.as.ejb3@23.0.2.Final//org.jboss.as.ejb3.tx.CMTTxInterceptor.invokeInOurTx(CMTTxInterceptor.java:284)
        at org.jboss.as.ejb3@23.0.2.Final//org.jboss.as.ejb3.tx.CMTTxInterceptor.requiresNew(CMTTxInterceptor.java:416)
        at org.jboss.as.ejb3@23.0.2.Final//org.jboss.as.ejb3.tx.CMTTxInterceptor.processInvocation(CMTTxInterceptor.java:162)
        at org.jboss.invocation@1.6.0.Final//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
    ...
     at deployment.j4dcm4chee-arc-ear-5.23.3-psql-secure.ear.dcm4chee-arc-query-5.23.3.jar//org.dcm4chee.arc.query.impl.QueryAttributesEJB$$$view31.calculateStudyQueryAttributes(Unknown Source)
        at jdk.internal.reflect.GeneratedMethodAccessor309.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
...
        at deployment.j4dcm4chee-arc-ear-5.23.3-psql-secure.ear.dcm4chee-arc-query-5.23.3.jar//org.dcm4chee.arc.query.impl.QueryAttribut
esEJB$Proxy$_$$_Weld$EnterpriseProxy$.calculateStudyQueryAttributes(Unknown Source)
        at deployment.j4dcm4chee-arc-ear-5.23.3-psql-secure.ear.dcm4chee-arc-query-5.23.3.jar//org.dcm4chee.arc.query.impl.QueryServiceI
mpl.calculateStudyQueryAttributes(QueryServiceImpl.java:285)
        at deployment.j4dcm4chee-arc-ear-5.23.3-psql-secure.ear.dcm4chee-arc-query-5.23.3.jar//org.dcm4chee.arc.query.impl.StudyQuery.to
Attributes(StudyQuery.java:163)
        at deployment.j4dcm4chee-arc-ear-5.23.3-psql-secure.ear.dcm4chee-arc-query-5.23.3.jar//org.dcm4chee.arc.query.impl.AbstractQuery.nextMatch(AbstractQuery.java:146)
        at deployment.j4dcm4chee-arc-ear-5.23.3-psql-secure.ear.dcm4chee-arc-export-mgt-5.23.3.jar//org.dcm4chee.arc.export.mgt.impl.ExportPriorsScheduler.export(ExportPriorsScheduler.java:246)
        at deployment.j4dcm4chee-arc-ear-5.23.3-psql-secure.ear.dcm4chee-arc-export-mgt-5.23.3.jar//org.dcm4chee.arc.export.mgt.impl.ExportPriorsScheduler.lambda$export$4(ExportPriorsScheduler.java:162)
        at java.base/java.util.HashMap.forEach(HashMap.java:1336)
        at deployment.j4dcm4chee-arc-ear-5.23.3-psql-secure.ear.dcm4chee-arc-export-mgt-5.23.3.jar//org.dcm4chee.arc.export.mgt.impl.ExportPriorsScheduler.export(ExportPriorsScheduler.java:161)
        at deployment.j4dcm4chee-arc-ear-5.23.3-psql-secure.ear.dcm4chee-arc-export-mgt-5.23.3.jar//org.dcm4chee.arc.export.mgt.impl.ExportPriorsScheduler.lambda$onStore$1(ExportPriorsScheduler.java:117)
 ...
        at deployment.j4dcm4chee-arc-ear-5.23.3-psql-secure.ear.dcm4chee-arc-export-mgt-5.23.3.jar//org.dcm4chee.arc.export.mgt.impl.ExportPriorsScheduler.onStore(ExportPriorsScheduler.java:116)
...
mpl.fireStoreEvent(StoreServiceImpl.java:421)
        at deployment.j4dcm4chee-arc-ear-5.23.3-psql-secure.ear.dcm4chee-arc-store-5.23.3.jar//org.dcm4chee.arc.store.impl.StoreServiceImpl.store(StoreServiceImpl.java:217)
        at deployment.j4dcm4chee-arc-ear-5.23.3-psql-secure.ear.dcm4chee-arc-store-5.23.3.jar//org.dcm4chee.arc.store.impl.StoreServiceImpl.store(StoreServiceImpl.java:179)
        at deployment.j4dcm4chee-arc-ear-5.23.3-psql-secure.ear.dcm4chee-arc-store-5.23.3.jar//org.dcm4chee.arc.store.impl.StoreServiceImpl$Proxy$_$$_WeldClientProxy.store(Unknown Source)
        at deployment.j4dcm4chee-arc-ear-5.23.3-psql-secure.ear//org.dcm4chee.arc.store.scp.CStoreSCP.store(CStoreSCP.java:36)
        at org.dcm4che.net@5.24.0//org.dcm4che3.net.service.BasicCStoreSCP.onDimseRQ(BasicCStoreSCP.java:72)
...
        at deployment.j4dcm4chee-arc-ear-5.23.3-psql-secure.ear//org.dcm4che3.net.service.DicomService2093826759$Proxy$_$$_WeldClientProxy.onDimseRQ(Unknown Source)
        at org.dcm4che.net@5.24.0//org.dcm4che3.net.service.DicomServiceRegistry.onDimseRQ(DicomServiceRegistry.java:86)
        at org.dcm4che.net@5.24.0//org.dcm4che3.net.ApplicationEntity.onDimseRQ(ApplicationEntity.java:474)
        at org.dcm4che.net@5.24.0//org.dcm4che3.net.Association.onDimseRQ(Association.java:755)
        at org.dcm4che.net@5.24.0//org.dcm4che3.net.PDUDecoder.decodeDIMSE(PDUDecoder.java:466)
        at org.dcm4che.net@5.24.0//org.dcm4che3.net.Association.handlePDataTF(Association.java:738)
        at org.dcm4che.net@5.24.0//org.dcm4che3.net.State$4.onPDataTF(State.java:108)
        at org.dcm4che.net@5.24.0//org.dcm4che3.net.Association.onPDataTF(Association.java:734)
        at org.dcm4che.net@5.24.0//org.dcm4che3.net.PDUDecoder.nextPDU(PDUDecoder.java:177)
        at org.dcm4che.net@5.24.0//org.dcm4che3.net.Association$2.run(Association.java:571)
        at org.jboss.as.ee@23.0.2.Final//org.jboss.as.ee.concurrent.ControlPointUtils$ControlledRunnable.run(ControlPointUtils.java:125)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
...
        Suppressed: javax.transaction.RollbackException: WFTXN0061: Transaction is marked rollback-only
 ...
Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "uk_t1uhb1suiiqffhsv9eaopeevs"
  Detail: Key (view_id, series_fk)=(hideRejected, 19991472) already exists.
        at org.postgresql@42.2.18//org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2553)
```

**Comment by gunterze** [comment]
Still occurs on concurrent calculation of StudyQueryAttributes:
```
2021-11-24 10:00:19,117 WARN  [org.dcm4chee.arc.export.mgt.impl.ExportPriorsScheduler] (EE-ManagedExecutorService-default-Thread-48082) CUFVNAA_FWMOD<-CUFVNAB(376048): Failed to apply Export
PriorsRule{cn=ATS Prefetch Priors on Store, conditions={IssuerOfPatientID=JMS, ReceivingApplicationEntityTitle=CUFVNAA_MOD.*|CUFVNAB_MOD.*|CUFVNAA_PWS.*|CUFVNAB_PWS.*|CUFVNAA_FWMOD|CUFVNAB_F
WMOD}, schedules=[], exporterIDs=[ATS Prefetch NG - QIDO Study Instances, ATS Prefetch NG - QIDO Study Series, ATS Prefetch NG - Series WADO Metadata, ATS Prefetch NG - Series Thumbnails], s
uppressDups=PT5M, entitySelectors=[], exportReoccurredInstances=REPLACE}:
: javax.ejb.EJBTransactionRolledbackException: javax.transaction.RollbackException: ARJUNA016053: Could not commit transaction.
...
Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "uk_prn4qt6d42stw0gfi1yce1fap"
  Detail: Key (view_id, study_fk)=(hideRejected, 6615828) already exists.
...
```

**Comment by gunterze** [comment]
Still occurs on concurrent calculation of SeriesQueryAttributes:
```
2022-01-14 14:00:06,462 WARN  [org.dcm4chee.arc.export.mgt.impl.ExportPriorsScheduler] (EE-ManagedExecutorService-default-Thread-144699) CUFVNAA_FWMOD<-CUFVNAB(826811): Failed to apply ExportPriorsRule{cn=ATS Prefetch Priors on Store, conditions={IssuerOfPatientID=JMS, ReceivingApplicationEntityTitle=CUFVNAA_MOD.*|CUFVNAB_MOD.*|CUFVNAA_PWS.*|CUFVNAB_PWS.*|CUFVNAA_FWMOD|CUFVNAB_FWMOD}, schedules=[], exporterIDs=[ATS Prefetch NG - QIDO Study Instances, ATS Prefetch NG - QIDO Study Series, ATS Prefetch NG - Series WADO Metadata, ATS Prefetch NG - Series Thumbnails], suppressDups=PT5M, entitySelectors=[], exportReoccurredInstances=REPLACE}:
: javax.ejb.EJBTransactionRolledbackException: javax.transaction.RollbackException: ARJUNA016053: Could not commit transaction.
...
Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "uk_t1uhb1suiiqffhsv9eaopeevs" 
  Detail: Key (view_id, series_fk)=(hideRejected, 32895696) already exists.
```
```

**Comment by gunterze** [comment]
Retrying according configured 

Name | Type | Description (LDAP Attribute)
-- | -- | --
Store Update DB Maximum Number of Retries | integer | Maximum number of retries to update the database on storage. (dcmStoreUpdateDBMaxRetries)
Minimal Store Update DB Delay of Retry | integer | Minimal Delay in ms between retries to update the database on storage. (dcmStoreUpdateDBMinRetryDelay)
Maximal Store Update DB Delay of Retry | integer | Maximal Delay in ms between retries to update the database on storage. (dcmStoreUpdateDBMaxRetryDelay)
