### ISSUE TITLE
WADO-RS: Retrieve of DICOM Video objects fails with 500 Internal Server Error

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4chee-arc-light#3608]
Retrieve of DICOM Video objects fails with 500 Internal Server Error.
 
 `server.log`:
 ```
 16:16:15,445 ERROR [org.jboss.resteasy.resteasy_jaxrs.i18n] (default task-11) RESTEASY002020: Unhandled asynchronous exception, sending back 500: org.jboss.resteasy.spi.UnhandledException: java.lang.UnsupportedOperationException: Unsupported Transfer Syntax: 1.2.840.10008.1.2.4.102
	at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:356)
	at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:193)
	at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.SynchronousDispatcher.asynchronousExceptionDelivery(SynchronousDispatcher.java:511)
	at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.AbstractAsynchronousResponse.internalResume(AbstractAsynchronousResponse.java:222)
	at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.AbstractAsynchronousResponse.internalResume(AbstractAsynchronousResponse.java:204)
	at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.plugins.server.servlet.Servlet3AsyncHttpRequest$Servlet3ExecutionContext$Servle3AsychronousResponse.resume(Servlet3AsyncHttpRequest.java:89)
	at deployment.dcm4chee-arc-ear-5.26.0-psql.ear.dcm4chee-arc-war-5.26.0-unsecure.war//org.dcm4chee.arc.wado.WadoRS.buildResponse(WadoRS.java:695)
	at deployment.dcm4chee-arc-ear-5.26.0-psql.ear.dcm4chee-arc-war-5.26.0-unsecure.war//org.dcm4chee.arc.wado.WadoRS.retrieve(WadoRS.java:619)

 ```

**Comment by gunterze** [comment]
You may workaround by explicit specifying
```
Accept: application/zip; transfer-syntax=*
``` 
but that should not be necessary according [DICOM PS 3.18](https://dicom.nema.org/medical/dicom/current/output/html/part18.html#sect_8.7.3.5.2):
> The wildcard value "*" indicates that the user agent will accept any Transfer Syntax. This allows, for example, the origin server to respond without needing to transcode an existing representation to a new Transfer Syntax, or to respond with the Explicit VR Little Endian Transfer Syntax regardless of the Transfer Syntax stored, **unless the origin server has only access to the pixel data in lossy compressed form** or the pixel data in a lossless compressed form that is of such length that it cannot be encoded in the Explicit VR Little Endian Transfer Syntax.
