### ISSUE TITLE
Fresh clean startup of dockerized 5.29.1 setup fails if AE_TITLE_WORKLIST and AE_TITLE env variables have equal values

### ISSUE THREAD

**Issue by vrindanayak** [dcm4che/dcm4chee-arc-light#3938]
````
2023-01-27 13:36:53,743 INFO  [org.wildfly.extension.undertow] (ServerService Thread Pool -- 78) WFLYUT0021: Registered web context: '/dcm4chee-arc' for server 'default-server'
2023-01-27 13:36:53,842 ERROR [org.dcm4chee.arc.impl.ArchiveDeviceProducer] (ServerService Thread Pool -- 94) Missing Configuration for Device 'dcm4chee-arc' - you may change the Device name by System Property 'dcm4chee-arc.DeviceName'
2023-01-27 13:36:53,850 ERROR [org.jboss.msc.service.fail] (ServerService Thread Pool -- 94) MSC000001: Failed to start service jboss.deployment.subunit."dcm4chee-arc-ear-5.29.1-psql.ear"."dcm4chee-arc-service-5.29.1.jar".component.ArchiveServiceImpl.START: org.jboss.msc.service.StartException in service jboss.deployment.subunit."dcm4chee-arc-ear-5.29.1-psql.ear"."dcm4chee-arc-service-5.29.1.jar".component.ArchiveServiceImpl.START: java.lang.IllegalStateException: WFLYEE0042: Failed to construct component instance
        at org.jboss.as.ee@26.1.2.Final//org.jboss.as.ee.component.ComponentStartService$1.run(ComponentStartService.java:57)
        .............
        .............
        at java.base/java.lang.Thread.run(Thread.java:829)
        at org.jboss.threads@2.4.0.Final//org.jboss.threads.JBossThread.run(JBossThread.java:513)
Caused by: java.lang.IllegalStateException: WFLYEE0042: Failed to construct component instance
        at org.jboss.as.ee@26.1.2.Final//org.jboss.as.ee.component.BasicComponent.constructComponentInstance(BasicComponent.java:170)
        .............
        .............
        at org.jboss.as.ejb3@26.1.2.Final//org.jboss.as.ejb3.component.singleton.SingletonComponent.start(SingletonComponent.java:141)
        at org.jboss.as.ee@26.1.2.Final//org.jboss.as.ee.component.ComponentStartService$1.run(ComponentStartService.java:54)
        ... 8 more
Caused by: javax.ejb.EJBException: org.jboss.weld.exceptions.WeldException: WELD-000049: Unable to invoke private void org.dcm4chee.arc.impl.ArchiveDeviceProducer.init() on org.dcm4chee.arc.impl.ArchiveDeviceProducer@ea1616c
        at org.jboss.as.ejb3@26.1.2.Final//org.jboss.as.ejb3.tx.CMTTxInterceptor.invokeInOurTx(CMTTxInterceptor.java:268)
        .............
        .............
        at org.jboss.invocation@1.7.0.Final//org.jboss.invocation.ChainedInterceptor.processInvocation(ChainedInterceptor.java:53)
        at org.jboss.as.ee@26.1.2.Final//org.jboss.as.ee.component.BasicComponent.constructComponentInstance(BasicComponent.java:168)
        ... 13 more
Caused by: org.jboss.weld.exceptions.WeldException: WELD-000049: Unable to invoke private void org.dcm4chee.arc.impl.ArchiveDeviceProducer.init() on org.dcm4chee.arc.impl.ArchiveDeviceProducer@ea1616c
        at org.jboss.weld.core@3.1.9.Final//org.jboss.weld.injection.producer.DefaultLifecycleCallbackInvoker.invokeMethods(DefaultLifecycleCallbackInvoker.java:85)
        .............
        .............
        at org.jboss.invocation@1.7.0.Final//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
        at org.jboss.as.ejb3@26.1.2.Final//org.jboss.as.ejb3.tx.CMTTxInterceptor.invokeInOurTx(CMTTxInterceptor.java:254)
        ... 28 more
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        .............
        .............
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.jboss.weld.core@3.1.9.Final//org.jboss.weld.injection.producer.DefaultLifecycleCallbackInvoker.invokeMethods(DefaultLifecycleCallbackInvoker.java:83)
        ... 68 more
Caused by: java.lang.RuntimeException: org.dcm4che3.conf.api.ConfigurationNotFoundException: Device with specified name not found
        at deployment.dcm4chee-arc-ear-5.29.1-psql.ear.dcm4chee-arc-service-5.29.1.jar//org.dcm4chee.arc.impl.ArchiveDeviceProducer.init(ArchiveDeviceProducer.java:116)
        ... 73 more
Caused by: org.dcm4che3.conf.api.ConfigurationNotFoundException: Device with specified name not found
        at org.dcm4che.conf.ldap@5.29.1//org.dcm4che3.conf.ldap.LdapDicomConfiguration.loadDevice(LdapDicomConfiguration.java:1350)
        at org.dcm4che.conf.ldap@5.29.1//org.dcm4che3.conf.ldap.LdapDicomConfiguration.findDevice(LdapDicomConfiguration.java:382)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        .............
        .............
        at deployment.dcm4chee-arc-ear-5.29.1-psql.ear//org.dcm4che3.conf.api.DicomConfiguration$Closeable$AutoCloseable$165381740$Proxy$_$$_WeldClientProxy.findDevice(Unknown Source)
        at deployment.dcm4chee-arc-ear-5.29.1-psql.ear.dcm4chee-arc-service-5.29.1.jar//org.dcm4chee.arc.impl.ArchiveDeviceProducer.findDevice(ArchiveDeviceProducer.java:169)
        at deployment.dcm4chee-arc-ear-5.29.1-psql.ear.dcm4chee-arc-service-5.29.1.jar//org.dcm4chee.arc.impl.ArchiveDeviceProducer.init(ArchiveDeviceProducer.java:109)
        ... 73 more
Caused by: javax.naming.NameNotFoundException: [LDAP: error code 32 - No Such Object]; remaining name 'dicomDeviceName=dcm4chee-arc,cn=Devices,cn=DICOM Configuration,dc=dcm4che,dc=org'
        at java.naming/com.sun.jndi.ldap.LdapCtx.mapErrorCode(LdapCtx.java:3284)
        .............
        .............
        at java.naming/javax.naming.directory.InitialDirContext.getAttributes(InitialDirContext.java:137)
        at org.dcm4che.conf.ldap@5.29.1//org.dcm4che3.conf.ldap.ReconnectDirContext.getAttributes(ReconnectDirContext.java:48)
        at org.dcm4che.conf.ldap@5.29.1//org.dcm4che3.conf.ldap.LdapDicomConfiguration.getAttributes(LdapDicomConfiguration.java:1364)
        at org.dcm4che.conf.ldap@5.29.1//org.dcm4che3.conf.ldap.LdapDicomConfiguration.loadDevice(LdapDicomConfiguration.java:1340)
        ... 83 more
````

Reported in https://groups.google.com/g/dcm4che/c/Ny-tqZvEUEw

**Comment by gunterze** [comment]
You have to configure different AETs for all Archive AEs!
