### ISSUE TITLE
Delete Study Permanently RS service fails for study with multiple referenced instance locations

### ISSUE THREAD

**Issue by vrindanayak** [dcm4che/dcm4chee-arc-light#4036]
For any study which was copied or moved to another study / linked to MWL, invoking [Delete Study Permanently](https://petstore.swagger.io/index.html?url=https://dcm4che.github.io/dcm4chee-arc-light/swagger/openapi.json#/IOCM-RS/DeleteStudy) REST service fails with 

````
javax.ejb.EJBException: java.lang.IllegalArgumentException: Removing a detached instance org.dcm4chee.arc.entity.Location#392
............
............
............
    at deployment.dcm4chee-arc-ear-5.30.0-psql.ear.dcm4chee-arc-store-5.30.0.jar//org.dcm4chee.arc.store.impl.StoreServiceEJB$$$view25.removeOrMarkLocationAs(Unknown Source)
............
............
    at deployment.dcm4chee-arc-ear-5.30.0-psql.ear.dcm4chee-arc-store-5.30.0.jar//org.dcm4chee.arc.store.impl.StoreServiceEJB$Proxy$_$$_Weld$EnterpriseProxy$.removeOrMarkLocationAs(Unknown Source)
    at deployment.dcm4chee-arc-ear-5.30.0-psql.ear.dcm4chee-arc-delete-5.30.0.jar//org.dcm4chee.arc.delete.impl.DeletionServiceEJB.removeOrMarkLocationAs(DeletionServiceEJB.java:457)
    at deployment.dcm4chee-arc-ear-5.30.0-psql.ear.dcm4chee-arc-delete-5.30.0.jar//org.dcm4chee.arc.delete.impl.DeletionServiceEJB.deleteStudy(DeletionServiceEJB.java:287)
............
............
    at deployment.dcm4chee-arc-ear-5.30.0-psql.ear.dcm4chee-arc-delete-5.30.0.jar//org.dcm4chee.arc.delete.impl.DeletionServiceEJB$$$view6.deleteStudy(Unknown Source)
............
............
    at deployment.dcm4chee-arc-ear-5.30.0-psql.ear.dcm4chee-arc-delete-5.30.0.jar//org.dcm4chee.arc.delete.impl.DeletionServiceEJB$Proxy$_$$_Weld$EnterpriseProxy$.deleteStudy(Unknown Source)
    at deployment.dcm4chee-arc-ear-5.30.0-psql.ear.dcm4chee-arc-delete-5.30.0.jar//org.dcm4chee.arc.delete.impl.DeletionServiceImpl.deleteStudy(DeletionServiceImpl.java:229)
    at deployment.dcm4chee-arc-ear-5.30.0-psql.ear.dcm4chee-arc-delete-5.30.0.jar//org.dcm4chee.arc.delete.impl.DeletionServiceImpl.deleteStudy(DeletionServiceImpl.java:162)
    at deployment.dcm4chee-arc-ear-5.30.0-psql.ear.dcm4chee-arc-delete-5.30.0.jar//org.dcm4chee.arc.delete.impl.DeletionServiceImpl.deleteStudy(DeletionServiceImpl.java:138)
    at deployment.dcm4chee-arc-ear-5.30.0-psql.ear.dcm4chee-arc-delete-5.30.0.jar//org.dcm4chee.arc.delete.impl.DeletionServiceImpl$Proxy$_$$_WeldClientProxy.deleteStudy(Unknown Source)
    at deployment.dcm4chee-arc-ear-5.30.0-psql.ear.dcm4chee-arc-war-5.30.0-unsecure.war//org.dcm4chee.arc.iocm.rs.StudyMgtRS.deleteStudy(StudyMgtRS.java:155)
````

**Comment by vrindanayak** [comment]
Fixed previously by [#4035 - commit](https://github.com/dcm4che/dcm4chee-arc-light/commit/b474a3a8fd908787ffa5cc2d17e7e83cd1e4c7b1#diff-1ce764bd767f89eb68e815d4d025a2de4b54e4992741c822ee80b06fa3bf8d82R683)
