### ISSUE TITLE
STOW-RS: Support upload of bzip2 compressed genomic data VCF file as Bulkdata and store it as object of private SOP Class

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4chee-arc-light#4168]
STOW-RS: Support upload of [bzip2 compressed genomic data VCF file](https://www.iana.org/assignments/media-types/application/prs.vcfbzip2) or any bzip2 compressed document as Bulkdata and store it as object of private SOP Class

SOP Class Name | SOP Class UID | Modality (0008,0060) | MIME Type of Encapsulated Document (0042,0012) 
-- | -- | -- | --
Private Dcm4che Encapsulated Bzip2 VCF Storage | 1.2.40.0.13.1.5.1.4.1.1.104.2 | DNA | application/prs.vcfbzip2
Private Dcm4che Encapsulated Bzip2 Document Storage | 1.2.40.0.13.1.5.1.4.1.1.104.3 | OT | application/x-bzip2

Related  #3604, https://github.com/dcm4che/dcm4che/issues/1332

**Comment by gunterze** [comment]
> [prova.vcfbz2](https://redmine.j4care.com:8443/attachments/18403) file upload fails with
> 
> ```
> 17:09:28,920 INFO  [org.dcm4chee.arc.stow.StowRS] (default task-1) Process POST /dcm4chee-arc/aets/DCM4CHEE/rs/studies from null@127.0.0.1:36286
> 17:09:28,939 INFO  [org.dcm4chee.arc.stow.StowRS] (default task-1) storeInstances: Extract Part #1{content-type=[application/dicom+json]}
> 17:09:28,946 INFO  [org.dcm4chee.arc.stow.StowRS] (default task-1) storeInstances: Extract Part #2{content-location=[file/prova.vcfbz2], content-type=[vcfbz2]}
> 17:09:28,952 ERROR [org.jboss.resteasy.resteasy_jaxrs.i18n] (default task-1) RESTEASY002020: Unhandled asynchronous exception, sending back 500: org.jboss.resteasy.spi.UnhandledException: java.lang.IllegalArgumentException: RESTEASY003340: Failure parsing MediaType string: vcfbz2
> .......
> .......
> Caused by: java.lang.IllegalArgumentException: RESTEASY003340: Failure parsing MediaType string: vcfbz2
> .......
> .......
> at deployment.dcm4chee-arc-ear-5.31.0-psql.ear.dcm4chee-arc-war-5.31.0-unsecure.war//org.dcm4chee.arc.stow.StowRS.lambda$store$1(StowRS.java:343)
>         at org.dcm4che.mime@5.31.0//org.dcm4che3.mime.MultipartParser.parse(MultipartParser.java:76)
>         at deployment.dcm4chee-arc-ear-5.31.0-psql.ear.dcm4chee-arc-war-5.31.0-unsecure.war//org.dcm4chee.arc.stow.StowRS.store(StowRS.java:338)
>         at deployment.dcm4chee-arc-ear-5.31.0-psql.ear.dcm4chee-arc-war-5.31.0-unsecure.war//org.dcm4chee.arc.stow.StowRS.storeJSONMetadataAndBulkdataJSON(StowRS.java:307)
>         at deployment.dcm4chee-arc-ear-5.31.0-psql.ear.dcm4chee-arc-war-5.31.0-unsecure.war//org.dcm4chee.arc.stow.StowRS$Proxy$_$$_WeldClientProxy.storeJSONMetadataAndBulkdataJSON(Unknown Source)
> .......
> .......
> ```

Caused by invalid `content-type: vcfbz2` (correct: `application/prs.vcfbzip2`) of second part in `multipart/related` payload

Reopened #4172
