### ISSUE TITLE
Include private attributes with values of DB columns study.ext_retrieve_aet, series.ext_retrieve_aet and instance.ext_retrieve_aet in QIDO-RS response

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4chee-arc-light#4179]
Include private attributes with values of DB columns `study.ext_retrieve_aet`,  `series.ext_retrieve_aet` and `instance.ext_retrieve_aet`  in QIDO-RS response

Attribute Name | Tag | VR | DB column
-- | -- | -- | --
Instance External Retrieve AE Title | (7777, 1043) | AE | `instance.ext_retrieve_aet``
Series External Retrieve AE Title | (7777, 1044) | AE | `series.ext_retrieve_aet``
Study External Retrieve AE Title | (7777, 1045) | AE | `study.ext_retrieve_aet``

**Comment by vrindanayak** [comment]
Series / Instance level queries fail with NullPointerException 

Instance level log
````
java.lang.NullPointerException at deployment.dcm4chee-arc-ear-5.31.0-psql.ear.dcm4chee-arc-query-5.31.0.jar//org.dcm4chee.arc.query.impl.InstanceQuery.toAttributes(InstanceQuery.java:172) 
    at deployment.dcm4chee-arc-ear-5.31.0-psql.ear.dcm4chee-arc-query-5.31.0.jar//org.dcm4chee.arc.query.impl.AbstractQuery.nextMatch(AbstractQuery.java:146) 
    at deployment.dcm4chee-arc-ear-5.31.0-psql.ear.dcm4chee-arc-query-5.31.0.jar//org.dcm4chee.arc.query.impl.InstanceQuery.nextMatch(InstanceQuery.java:348) 
    at deployment.dcm4chee-arc-ear-5.31.0-psql.ear.dcm4chee-arc-war-5.31.0-unsecure.war//org.dcm4chee.arc.qido.QidoRS.matches(QidoRS.java:1008) 
    at deployment.dcm4chee-arc-ear-5.31.0-psql.ear.dcm4chee-arc-war-5.31.0-unsecure.war//org.dcm4chee.arc.qido.QidoRS.writeJSON(QidoRS.java:963) 
    at deployment.dcm4chee-arc-ear-5.31.0-psql.ear.dcm4chee-arc-war-5.31.0-unsecure.war//org.dcm4chee.arc.qido.QidoRS$Output$2.entity(QidoRS.java:904) 
    at deployment.dcm4chee-arc-ear-5.31.0-psql.ear.dcm4chee-arc-war-5.31.0-unsecure.war//org.dcm4chee.arc.qido.QidoRS.search(QidoRS.java:569) 
    at deployment.dcm4chee-arc-ear-5.31.0-psql.ear.dcm4chee-arc-war-5.31.0-unsecure.war//org.dcm4chee.arc.qido.QidoRS.searchForInstancesOfSeries(QidoRS.java:295) 
    at deployment.dcm4chee-arc-ear-5.31.0-psql.ear.dcm4chee-arc-war-5.31.0-unsecure.war//org.dcm4chee.arc.qido.QidoRS$Proxy$_$$_WeldClientProxy.searchForInstancesOfSeries(Unknown Source) 
    ....
````
