### ISSUE TITLE
Module file dcm4chee-arc-xsl-cda-5.31.2.war not found

### ISSUE THREAD

**Issue by esefberfu** [dcm4che/dcm4chee-arc-light#4421]
I successfully built dcm4chee-arc from the source code. I configured it to debug locally using JetBrains IntelliJ IDEA. However, when I run it, WildFly returns the following error.

`Failed to start service jboss.deployment.unit."dcm4chee-arc-ear-5.31.2.ear".STRUCTURE: org.jboss.msc.service.StartException in service jboss.deployment.unit."dcm4chee-arc-ear-5.31.2.ear".STRUCTURE: WFLYSRV0153: Failed to process phase STRUCTURE of deployment "dcm4chee-arc-ear-5.31.2.ear"
	at org.jboss.as.server@22.0.2.Final//org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:178)
	at org.jboss.msc@1.5.2.Final//org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1617)
	at org.jboss.msc@1.5.2.Final//org.jboss.msc.service.ServiceControllerImpl$StartTask.execute(ServiceControllerImpl.java:1580)
	at org.jboss.msc@1.5.2.Final//org.jboss.msc.service.ServiceControllerImpl$ControllerTask.run(ServiceControllerImpl.java:1438)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.jboss.as.server.deployment.DeploymentUnitProcessingException: WFLYEE0031: Unable to process modules in application.xml for EAR ["/content/dcm4chee-arc-ear-5.31.2.ear"], module file dcm4chee-arc-xsl-cda-5.31.2.war not found
	at org.jboss.as.ee@30.0.1.Final//org.jboss.as.ee.structure.EarStructureProcessor.deploy(EarStructureProcessor.java:170)
	at org.jboss.as.server@22.0.2.Final//org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:171)
	... 8 more

17:18:23,406 ERROR [org.jboss.as.controller.management-operation] (management-handler-thread - 1) WFLYCTL0013: Operation ("deploy") failed - address: ([("deployment" => "dcm4chee-arc-ear-5.31.2.ear")]) - failure description: {"WFLYCTL0080: Failed services" => {"jboss.deployment.unit.\"dcm4chee-arc-ear-5.31.2.ear\".STRUCTURE" => "WFLYSRV0153: Failed to process phase STRUCTURE of deployment \"dcm4chee-arc-ear-5.31.2.ear\"
    Caused by: org.jboss.as.server.deployment.DeploymentUnitProcessingException: WFLYEE0031: Unable to process modules in application.xml for EAR [\"/content/dcm4chee-arc-ear-5.31.2.ear\"], module file dcm4chee-arc-xsl-cda-5.31.2.war not found"}}
17:18:23,406 ERROR [org.jboss.as.controller.management-operation] (management-handler-thread - 1) WFLYCTL0013: Operation ("deploy") failed - address: ([("deployment" => "dcm4chee-arc-ear-5.31.2.ear")]) - failure description: {"WFLYCTL0080: Failed services" => {"jboss.deployment.unit.\"dcm4chee-arc-ear-5.31.2.ear\".STRUCTURE" => "WFLYSRV0153: Failed to process phase STRUCTURE of deployment \"dcm4chee-arc-ear-5.31.2.ear\"
    Caused by: org.jboss.as.server.deployment.DeploymentUnitProcessingException: WFLYEE0031: Unable to process modules in application.xml for EAR [\"/content/dcm4chee-arc-ear-5.31.2.ear\"], module file dcm4chee-arc-xsl-cda-5.31.2.war not found"}}
17:18:23,407 ERROR [org.jboss.as.server] (management-handler-thread - 1) WFLYSRV0021: Deploy of deployment "dcm4chee-arc-ear-5.31.2.ear" was rolled back with the following failure message: 
{"WFLYCTL0080: Failed services" => {"jboss.deployment.unit.\"dcm4chee-arc-ear-5.31.2.ear\".STRUCTURE" => "WFLYSRV0153: Failed to process phase STRUCTURE of deployment \"dcm4chee-arc-ear-5.31.2.ear\"
    Caused by: org.jboss.as.server.deployment.DeploymentUnitProcessingException: WFLYEE0031: Unable to process modules in application.xml for EAR [\"/content/dcm4chee-arc-ear-5.31.2.ear\"], module file dcm4chee-arc-xsl-cda-5.31.2.war not found"}}`

**Comment by njiddasalifu** [comment]
Not sure what this issue is about just yet as i am also struggling getting it run faster on docker as a start which there is no success yet.
