### ISSUE TITLE
Handle closure of instances of `org.jboss.resteasy.client.jaxrs.ResteasyClient`

### ISSUE THREAD

**Issue by vrindanayak** [dcm4che/dcm4chee-arc-light#4511]
Archive server logs
```
2024-05-27 11:22:17,773 WARN  [org.jboss.resteasy.client.jaxrs.i18n] (Cleaner-2) RESTEASY004687: Closing a class org.jboss.resteasy.client.jaxrs.engines.ManualClosingApacheHttpClient43Engine$CleanupAction instance for you. Please close clients yourself.
```

**Comment by vrindanayak** [comment]
Handling closure of client before its InvocationBuilder is processed for response throws `IllegalStateException` - `Client is closed`
```
2024-07-18 13:22:38,346 INFO  [org.dcm4chee.arc.qmgt.impl.TaskScheduler] (EE-ManagedExecutorService-default-Thread-128) Start processing Task{taskID=203, deviceName='j4c-arc1', queueName='ATSPrefetchWADO_TENANTX', type=EXPORT, status=IN PROCESS,
 scheduledTime=2024-07-18 13:22:38.276, numberOfFailures=0, exporterID=ATS Prefetch - WADO - Series Thumbnails - TENANTX, studyInstanceUID=2.25.1111111.1, seriesInstanceUID=*, sopInstanceUID=*, localAET=TENANTX1}
2024-07-18 13:22:38,426 DEBUG [org.dcm4chee.arc.export.wado.WadoExporter] (EE-ManagedExecutorService-default-Thread-128) Access token retrieved for Web Application[name=TENANTX1_ATS_RS, KeycloakClient[keycloakClientID=dcm4chee-arc-rs,keycloakServerURL=https://test-auth.lan.j4care.com:8843,keycloakRealm=dcm4che,keycloakGrantType=client_credentials,keycloakClientSecret=changeit,userID=null,password=null,tlsAllowAnyHostname=true,tlsDisableTrustManager=false]] is eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJPWmFvX05reUdVSFhpQlN5Y3VXR2ZDZGg0OFhYRXl4TTcyTV9SV3VvbTBZIn0.eyJleHAiOjE3MjEzMDIwNTgsImlhdCI6MTcyMTMwMTc1OCwianRpIjoiMDVmNmIyZTctZWZkNS00NWJlLTliNWYtNTBiYTE5M2MwN2Y5IiwiaXNzIjoiaHR0cHM6Ly90ZXN0LWF1dGgubGFuLmo0Y2FyZS5jb206ODg0My9yZWFsbXMvZGNtNGNoZSIsInN1YiI6IjYyMzg0NjU4LWMxNGMtNDk0Mi1iYzY0LTI3OGEyNDM0NmYwNyIsInR5cCI6IkJlYXJlciIsImF6cCI6ImRjbTRjaGVlLWFyYy1ycyIsImFjciI6IjEiLCJhbGxvd2VkLW9yaWdpbnMiOlsiaHR0cHM6Ly90ZXN0LXNpdGUxLmxhbi5qNGNhcmUuY29tOjg0NDMiLCJodHRwOi8vdGVzdC1zaXRlMS5sYW4uajRjYXJlLmNvbTo4MDgwIl0sInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJhdXRoIiwicm9vdCIsIm9mZmxpbmVfYWNjZXNzIiwiZGVmYXVsdC1yb2xlcy1kY200Y2hlIiwidW1hX2F1dGhvcml6YXRpb24iXX0sInNjb3BlIjoicHJvZmlsZSBlbWFpbCIsImNsaWVudEhvc3QiOiIxOTIuMTY4LjIuMTk2IiwiY2xpZW50SWQiOiJkY200Y2hlZS1hcmMtcnMiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsInByZWZlcnJlZF91c2VybmFtZSI6InNlcnZpY2UtYWNjb3VudC1kY200Y2hlZS1hcmMtcnMiLCJjbGllbnRBZGRyZXNzIjoiMTkyLjE2OC4yLjE5NiJ9.cUO7H9Mdlr3Ra_5MfywlpLOp06_W3T3tINzryq9pQmPY61G0Um8S-yi-j8_IsUBXxaDY2YEYL5KAJQUaLidSyd_CZ6hQOMbQhfP9IR0XPRo2sRY-7-M_4Sm4NX5dema46-UvX8I4Alc1tO89ceYSCds6QoAqRHbwnzFtmtJpHYGW_c-spMTQySh3hwR3G6NR2tOwZ3IOvLNCptB3285V2qyFt9fRaNn2z0SW-553h112TFZpWQvJ6GzIU6l1gScTPOEbgRJdbi4NcszOokGJMaVHDtOsMRlMzkcarPb46aA8QPS-YPAiaYO4YmYVS23cNxOA2sCH2b3mcoklB53M3w
2024-07-18 13:22:38,440 WARN  [org.dcm4chee.arc.export.mgt.impl.ExportTaskProcessor] (EE-ManagedExecutorService-default-Thread-128) Failed to process Task{taskID=203, deviceName='j4c-arc1', queueName='ATSPrefetchWADO_TENANTX', type=EXPORT, statu
s=IN PROCESS, scheduledTime=2024-07-18 13:22:38.276, numberOfFailures=0, exporterID=ATS Prefetch - WADO - Series Thumbnails - TENANTX, studyInstanceUID=2.25.1111111.1, seriesInstanceUID=*, sopInstanceUID=*, localAET=TENANTX1}: java.lang.IllegalStateException: RESTEASY004510: Client is closed.
        at org.jboss.resteasy.resteasy-client@6.2.8.Final//org.jboss.resteasy.client.jaxrs.internal.ResteasyClientImpl.abortIfClosed(ResteasyClientImpl.java:75)
        at org.jboss.resteasy.resteasy-client@6.2.8.Final//org.jboss.resteasy.client.jaxrs.internal.ResteasyClientImpl.httpEngine(ResteasyClientImpl.java:61)
        at org.jboss.resteasy.resteasy-client@6.2.8.Final//org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:427)
        at org.jboss.resteasy.resteasy-client@6.2.8.Final//org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:71)
        at org.jboss.resteasy.resteasy-client@6.2.8.Final//org.jboss.resteasy.client.jaxrs.internal.ClientInvocationBuilder.get(ClientInvocationBuilder.java:175)
        at deployment.j4dcm4chee-arc-ear-5.32.1-psql-secure.ear//org.dcm4chee.arc.export.wado.WadoExporter.invoke(WadoExporter.java:203)
        at deployment.j4dcm4chee-arc-ear-5.32.1-psql-secure.ear//org.dcm4chee.arc.export.wado.WadoExporter.export(WadoExporter.java:173)
        at deployment.j4dcm4chee-arc-ear-5.32.1-psql-secure.ear.dcm4chee-arc-export-mgt-5.32.1.jar//org.dcm4chee.arc.export.mgt.impl.ExportTaskProcessor.process(ExportTaskProcessor.java:117)
        at deployment.j4dcm4chee-arc-ear-5.32.1-psql-secure.ear.dcm4chee-arc-export-mgt-5.32.1.jar//org.dcm4chee.arc.export.mgt.impl.ExportTaskProcessor$Proxy$_$$_WeldClientProxy.process(Unknown Source)
        at deployment.j4dcm4chee-arc-ear-5.32.1-psql-secure.ear.dcm4chee-arc-qmgt-5.32.1.jar//org.dcm4chee.arc.qmgt.impl.TaskScheduler.processTask(TaskScheduler.java:214)
        at deployment.j4dcm4chee-arc-ear-5.32.1-psql-secure.ear.dcm4chee-arc-qmgt-5.32.1.jar//org.dcm4chee.arc.qmgt.impl.TaskScheduler.processTasksSequential(TaskScheduler.java:149)
        at deployment.j4dcm4chee-arc-ear-5.32.1-psql-secure.ear.dcm4chee-arc-qmgt-5.32.1.jar//org.dcm4chee.arc.qmgt.impl.TaskScheduler.process(TaskScheduler.java:129)
        at deployment.j4dcm4chee-arc-ear-5.32.1-psql-secure.ear.dcm4chee-arc-qmgt-5.32.1.jar//org.dcm4chee.arc.qmgt.impl.TaskScheduler.lambda$process$0(TaskScheduler.java:118)
        ..............
        ..............
```
