### ISSUE TITLE
Failed to process Audit Spool File: java.lang.ArrayIndexOutOfBoundsException: 17

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4chee-arc-light#479]
```
12:45:19,474 WARN  [org.dcm4chee.arc.audit.AuditService] (EE-ManagedScheduledExecutorService-default-Thread-5) Failed to process Audit Spool File - /home/gunter/wildfly-10.1.0.Final/standalone/data/audit-spool/STORE_CREA-STORESCU-DCM4CHEE-1.3.12.2.1107.5.8.1.12345678.199508041416590859569: java.lang.ArrayIndexOutOfBoundsException: 17
	at org.dcm4chee.arc.audit.AuditInfo.getField(AuditInfo.java:105)
	at org.dcm4chee.arc.audit.AuditService.auditStoreOrWADORetrieve(AuditService.java:415)
	at org.dcm4chee.arc.audit.AuditService.aggregateAuditMessage(AuditService.java:120)
	at org.dcm4chee.arc.audit.AuditService.auditAndProcessFile(AuditService.java:293)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.weld.bean.proxy.AbstractBeanInstance.invoke(AbstractBeanInstance.java:38)
	at org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke(ProxyMethodHandler.java:100)
	at org.dcm4chee.arc.audit.AuditService$Proxy$_$$_WeldClientProxy.auditAndProcessFile(Unknown Source)
	at org.dcm4chee.arc.audit.AuditScheduler.execute(AuditScheduler.java:121)
	at org.dcm4chee.arc.Scheduler.run(Scheduler.java:78)
	at org.jboss.as.ee.concurrent.ControlPointUtils$ControlledScheduledRunnable.run(ControlPointUtils.java:158)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at org.glassfish.enterprise.concurrent.internal.ManagedScheduledThreadPoolExecutor$ManagedScheduledFutureTask.access$201(ManagedScheduledThreadPoolExecutor.java:383)
	at org.glassfish.enterprise.concurrent.internal.ManagedScheduledThreadPoolExecutor$ManagedScheduledFutureTask.run(ManagedScheduledThreadPoolExecutor.java:534)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.glassfish.enterprise.concurrent.ManagedThreadFactoryImpl$ManagedThread.run(ManagedThreadFactoryImpl.java:250)
```

**Comment by vrindanayak** [comment]
Also present for Rejection spool files
