### ISSUE TITLE
Generation of metadata for compressed objects received by STOW-RS XML/JSON Metadata and Bulk Data Request causes error in UpdateMetadataScheduler

### ISSUE THREAD

**Issue by vrindanayak** [dcm4che/dcm4chee-arc-light#635]
```
10:23:39,767 ERROR [org.dcm4chee.arc.metadata.UpdateMetadataScheduler] (EE-ManagedScheduledExecutorService-default-Thread-14) MetadataUpdate[seriesPk=488, storageID=null, storagePath=null] failed:
: java.lang.IllegalStateException: JsonParser#getString() is valid only KEY_NAME, VALUE_STRING, VALUE_NUMBER parser states. But current parser state is START_OBJECT
	at org.glassfish.json.JsonParserImpl.getString(JsonParserImpl.java:90)
	at org.dcm4che3.json.JSONReader.getString(JSONReader.java:98)
	at org.dcm4che3.json.JSONReader.readDataFragment(JSONReader.java:346)
	at org.dcm4che3.json.JSONReader.readDataFragments(JSONReader.java:274)
	at org.dcm4che3.json.JSONReader.readAttribute(JSONReader.java:178)
	at org.dcm4che3.json.JSONReader.doReadDataset(JSONReader.java:141)
	at org.dcm4che3.json.JSONReader.readDataset(JSONReader.java:121)
	at org.dcm4chee.arc.retrieve.impl.RetrieveServiceImpl.parseJSON(RetrieveServiceImpl.java:950)
	at org.dcm4chee.arc.retrieve.impl.RetrieveServiceImpl.loadMetadataFromJSONFile(RetrieveServiceImpl.java:940)
	at org.dcm4chee.arc.retrieve.impl.RetrieveServiceImpl.loadMetadata(RetrieveServiceImpl.java:925)
	at org.dcm4chee.arc.retrieve.impl.RetrieveServiceImpl$Proxy$_$$_WeldClientProxy.loadMetadata(Unknown Source)
	at org.dcm4chee.arc.metadata.UpdateMetadataScheduler.loadMetadata(UpdateMetadataScheduler.java:165)
	at org.dcm4chee.arc.metadata.UpdateMetadataScheduler.updateMetadata(UpdateMetadataScheduler.java:146)
	at org.dcm4chee.arc.metadata.UpdateMetadataScheduler.execute(UpdateMetadataScheduler.java:125)
	at org.dcm4chee.arc.Scheduler.run(Scheduler.java:78)
	at org.jboss.as.ee.concurrent.ControlPointUtils$ControlledScheduledRunnable.run(ControlPointUtils.java:158)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at org.glassfish.enterprise.concurrent.internal.ManagedScheduledThreadPoolExecutor$ManagedScheduledFutureTask.access$201(ManagedScheduledThreadPoolExecutor.java:383)
	at org.glassfish.enterprise.concurrent.internal.ManagedScheduledThreadPoolExecutor$ManagedScheduledFutureTask.run(ManagedScheduledThreadPoolExecutor.java:534)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.glassfish.enterprise.concurrent.ManagedThreadFactoryImpl$ManagedThread.run(ManagedThreadFactoryImpl.java:250)
```

**Comment by vrindanayak** [comment]
Also affects `Show Attributes from File` function when tried to View file attributes from archive UI
