### ISSUE TITLE
No compatible connection to AuditRecordRepository error occurs even when audit logging is disabled 

### ISSUE THREAD

**Issue by petrkalina** [dcm4che/dcm4chee-arc-light#691]
I'm using the default LDAP configuration and the `dcm4che/dcm4chee-arc-psql` docker image.

In order to disable the audit logging, I set the `dicomDeviceName=logstash,cn=Devices,cn=DICOM Configuration,dc=dcm4che,dc=org` / `dicomInstalled: FALSE`

I believe that this is expected to disable the audit logging completely. However, I get the following exception in the logs:

    2017-05-11 10:46:05,674 INFO  [org.dcm4che3.net.Connection] (EE-ManagedExecutorService-default-Thread-2) Start TCP Listener on /0.0.0.0:11112
    2017-05-11 10:46:05,818 WARN  [org.dcm4chee.arc.audit.AuditService] (ServerService Thread Pool -- 69) Failed to emit audit message: org.dcm4che3.net.IncompatibleConnectionException: No compatible connection to AuditRecordRepository @ Device logstash available on AuditLogger @ Device dcm4chee-arc
        at org.dcm4che3.net.audit.AuditLogger.activeConnection(AuditLogger.java:906)
        at org.dcm4che3.net.audit.AuditLogger.sendMessage(AuditLogger.java:729)
        at org.dcm4che3.net.audit.AuditLogger.write(AuditLogger.java:706)
        at org.dcm4chee.arc.audit.AuditService.emitAuditMessage(AuditService.java:1089)
        at org.dcm4chee.arc.audit.AuditService.auditApplicationActivity(AuditService.java:165)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

**Comment by gunterze** [comment]
@petrkalina : did you really disable the Audit Logger of the Archive - and not the Audit Record Repository?!

**Comment by petrkalina** [comment]
I have:

    dn: cn=Audit Logger,dicomDeviceName=dcm4chee-arc,cn=Devices,cn=DICOM Configu
     ration,dc=dcm4che,dc=org
    objectClass: dcmAuditLogger
    cn: Audit Logger
    dcmAuditRecordRepositoryDeviceReference: dicomDeviceName=logstash,cn=Devices
     ,cn=DICOM Configuration,dc=dcm4che,dc=org
    dicomNetworkConnectionReference: cn=syslog,dicomDeviceName=dcm4chee-arc,cn=D
     evices,cn=DICOM Configuration,dc=dcm4che,dc=org
    dcmAuditMessageSchemaURI: http://www.dcm4che.org/DICOM/audit-message.rnc
    dcmAuditSourceTypeCode: 4

and 

    dn: dicomDeviceName=logstash,cn=Devices,cn=DICOM Configuration,dc=dcm4che,dc=org
    objectClass: dcmDevice
    objectClass: dicomDevice
    dicomDeviceName: logstash
    dicomInstalled: FALSE
    dicomPrimaryDeviceType: LOG

    dn: cn=syslog,dicomDeviceName=logstash,cn=Devices,cn=DICOM Configuration,dc=
     dcm4che,dc=org
    objectClass: dcmNetworkConnection
    objectClass: dicomNetworkConnection
    dicomHostname: logstash
    cn: syslog
    dcmProtocol: SYSLOG_TLS
    dicomPort: 8514

    dn: cn=Audit Record Repository,dicomDeviceName=logstash,cn=Devices,cn=DICOM 
     Configuration,dc=dcm4che,dc=org
    objectClass: dcmAuditRecordRepository
    cn: Audit Record Repository
    dicomNetworkConnectionReference: cn=syslog,dicomDeviceName=logstash,cn=Devic
     es,cn=DICOM Configuration,dc=dcm4che,dc=org

**Comment by gunterze** [comment]
So you disabled (the Device providing) the Audit Record Repository, so the - not disabled - Audit Logger could not connect to it.

**Comment by petrkalina** [comment]
setting: `cn=Audit Logger,dicomDeviceName=dcm4chee-arc,cn=Devices,cn=DICOM Configuration,dc=dcm4che,dc=org` / `dicomInstalled:FALSE` did the trick!

sorry for confusion and thanks :-)
