### ISSUE TITLE
Adding an AE (without Archive AE extension) to archive device causes NPE in query services

### ISSUE THREAD

**Issue by vrindanayak** [dcm4che/dcm4chee-arc-light#739]
````
Caused by: java.lang.NullPointerException
	at org.dcm4chee.arc.query.util.QueryParam.<init>(QueryParam.java:75)
	at org.dcm4chee.arc.qido.QidoRS.newQueryContext(QidoRS.java:439)
	at org.dcm4chee.arc.qido.QidoRS.search(QidoRS.java:380)
	at org.dcm4chee.arc.qido.QidoRS.searchForPatientsJSON(QidoRS.java:248)
	at org.dcm4chee.arc.qido.QidoRS$Proxy$_$$_WeldClientProxy.searchForPatientsJSON(Unknown Source)
````

**Comment by gunterze** [comment]
Replaced NPE by Configuration Exception
