### ISSUE TITLE
UI: on secure archive and secure ui, on login the aetes and exporters are not loaded

### ISSUE THREAD

**Issue by shral** [dcm4che/dcm4chee-arc-light#759]

**Comment by dbortolz** [comment]
On master @45e053df this bug seems still there. During the first load of the page the AET list is empty because of many `HTTP 400 Bad Request` errors, then doing a refresh (e.g. F5) the list gets filled and no more `HTTP 400`.

I see 3 retries (all failing) of `devicename`, `aets` and `export` and finally a call to an undefined `patients` REST resource:

```
2017-07-25 12:21:13,292 INFO  [org.dcm4chee.arc.qido.QidoRS] (default task-5) Process GET /dcm4chee-arc/aets/undefined/rs/patients?includefield=all&offset=0&limit=21&orderby=PatientNam
e from 08f8af44-587f-4669-83d8-f27d8bbc5648@10.0.0.76
2017-07-25 12:21:13,305 ERROR [org.jboss.resteasy.resteasy_jaxrs.i18n] (default task-5) RESTEASY002010: Failed to execute: javax.ws.rs.WebApplicationException: No such Application Entity: undefined
        at org.dcm4chee.arc.qido.QidoRS.getApplicationEntity(QidoRS.java:405)
        at org.dcm4chee.arc.qido.QidoRS.newQueryContext(QidoRS.java:367)
        at org.dcm4chee.arc.qido.QidoRS.search(QidoRS.java:303)
        at org.dcm4chee.arc.qido.QidoRS.searchForPatientsJSON(QidoRS.java:171)
        at org.dcm4chee.arc.qido.QidoRS$Proxy$_$$_WeldClientProxy.searchForPatientsJSON(Unknown Source)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:139)
        at 
<snip>
```

**Comment by shral** [comment]
https://github.com/dcm4che/dcm4chee-arc-light/issues/923
