### ISSUE TITLE
WADO URI RESTful service : Return 405-Not Allowed when user tries to downlaod uncompressed DICOM object for video files

### ISSUE THREAD

**Issue by vrindanayak** [dcm4che/dcm4chee-arc-light#786]
````
Caused by: java.lang.UnsupportedOperationException: Unsupported Transfer Syntax: 1.2.840.10008.1.2.4.100
	at org.dcm4che3.imageio.codec.Transcoder.initDecompressor(Transcoder.java:255)
	at org.dcm4che3.imageio.codec.Transcoder.setDestinationTransferSyntax(Transcoder.java:235)
	at org.dcm4chee.arc.retrieve.impl.RetrieveServiceImpl.openTranscoder(RetrieveServiceImpl.java:677)
	at org.dcm4chee.arc.wado.DicomObjectOutput.write(DicomObjectOutput.java:71)
	at org.jboss.resteasy.plugins.providers.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:32)
````

**Comment by vrindanayak** [comment]
Resolved by #787
