### ISSUE TITLE
dcm4che-tools-findscu: query params mentioned in dicom binary file or xml file is unused if specified after -m, -i or -r flags

### ISSUE THREAD

**Issue by vrindanayak** [dcm4che/dcm4chee-arc-light#799]
- Caused by `cl.getOptionValues()` used for these flags

````
java.lang.IllegalArgumentException: /work/testdata/1.3.51.5146.1267.20050317.1135946.1.1.1
        at org.dcm4che3.tool.common.CLIUtils.toTag(CLIUtils.java:599)
        at org.dcm4che3.tool.common.CLIUtils.toTags(CLIUtils.java:589)
        at org.dcm4che3.tool.findscu.FindSCU.configureKeys(FindSCU.java:428)
        at org.dcm4che3.tool.findscu.FindSCU.main(FindSCU.java:355)
````

**Comment by gunterze** [comment]
Solved by #832
