### ISSUE TITLE
UI2 Configuration : Adding archive device extension to a device fails

### ISSUE THREAD

**Issue by vrindanayak** [dcm4che/dcm4chee-arc-light#982]
Related #750 

````
org.dcm4che3.conf.api.ConfigurationException: javax.naming.directory.SchemaViolationException: [LDAP: error code 65 - object class 'dcmArchiveDevice' requires attribute 'dcmQueryRetrieveViewID']; remaining name 'dicomDeviceName=dcmqrscp,cn=Devices,cn=DICOM Configuration,dc=dcm4che,dc=org' at 

org.dcm4che3.conf.ldap.LdapDicomConfiguration.merge(LdapDicomConfiguration.java:652) at org.dcm4che3.conf.ldap.LdapDicomConfiguration.merge(LdapDicomConfiguration.java:619) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at 
````

**Comment by vrindanayak** [comment]
Shall be resolved by #1571
